### ISSUE TITLE
Знакомство с проектом Drum Instructor

### ISSUE THREAD

**Issue by dakand** [atls/design#10]
Есть у нас такой проект - школа барабанов. В рамках этого проекта нам потребуется сделать сайт индивидуальных занятий - по сути личный промо-сайт Марины (руководителя школы). Также нужно будет сделать полноценный сайт с курсами и лк. 

Пока что банально ознакомься с проектом и собери свои референсы. 

### Информация
Вот [тут](https://github.com/torin-asakura/drum-in/discussions) информация от заказчика. Там много воды, можешь изучить между строк.
[Это](https://www.figma.com/file/aUDZv2lPVm4fNrtCqC7af0/Brand?node-id=40%3A2), [это](https://www.figma.com/file/qihLK2fcqzvBi0pd8zfjG9/Landing-Online-course?node-id=0%3A1) и [это](https://www.figma.com/file/7FTyeashb3rns6sCdrsz3b/Landing-Lessons?node-id=51%3A1360) то, что осталось от предыдущего дизайнера, который этим занимался. Тут все плохо. Только лого можно юзать наверное.

### Мудборд
Т.к. мы пока не решили проблему с оплатой командной фигмы, создавай проект в личном drafts, пока будем работать в нём. По референсам единственное предпочтение, которое у меня есть - будто бы нужно что-то андерграундное совмещенное со строгой структурой. Всё что касается андерграунда я бы искал на пинтерест, т.к. на дрибле или бихээнсе подобное будет трудно найти.

**Comment by bbbaso** [comment]
@dakand **Приготовил первый [мудборд](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=0%3A1)**

_*тезисы и комментарии расписал внутри_

**Comment by dakand** [comment]
@bbbaso несколькими референсами прям в точку попал. Если ознакомился с инфой от заказчика, а там самое важное - структура, то задачу можешь закрывать.

**Comment by bbbaso** [comment]
@dakand, не наблюдаю структуры в ссылках выше, там есть только бриф (в нём тоже не вижу) и концепты
