### ISSUE TITLE
Atlantis Design [Дизайн внутренних страниц]

### ISSUE THREAD

**Issue by shatiloand** [atls/design#12]
### Страницы:

- [x] Страница кейсов;
- [x] Страница о команде;
- [x] Контакты;
- [x] Правовая страница;
- [x] 404.

### Вишенка:

- [x] Экран бургер-меню;
- [x] Куки;
- [x] Обратная связь;
- [x] Апрув модалки (обратная связь).

### Легаси:

- [Фигма](https://www.figma.com/file/PBmbpTjf6jRHPMR3PNNnDY/Atlantis-Design?node-id=0%3A1)
- [Сайтмап](https://octopus.do/b4udqc5nnyp)
- [Превью](https://www.figma.com/proto/PBmbpTjf6jRHPMR3PNNnDY/Atlantis-Design?page-id=0%3A1&node-id=265%3A1164&viewport=241%2C48%2C0.1&scaling=min-zoom)

**Comment by shatiloand** [comment]
@TorinAsakura @dakand я закончил этот пул. Все ссылки и файлы актуализировал. Чекните пожалуйста завтра. Жду фидбек.

Дальше по плану попробовать собрать это все в мобилке.

**Comment by dakand** [comment]
В фигме оставил комментарии. Выделил несколько основных проблем:
1. Изначально чувствовалась какое-то следование референсу без изменения под наш формат. Чувство шаблона сохраняется и сейчас. Количеством компаний, которые "нам доверяют" мы похвастаться не можем, поэтому блок с лого здесь изначально не особо нужен. Даже, если размещать, то почему лого не взял из прошлого макета. Фотка команды - её нет и пока не может быть. Надо исправить эти моменты и, наверное, добавить что-то ещё на главную (в фигме писал).
2. Мы с Андреем ждали полный десктоп не мало времени. Но страница проекта отсутствует. Мы не можем перейти к адаптацию без такой важной страницы.
3. Техническая часть работы в фигме по прежнему хромает. Во-первых, неправильная группировка элементов (описал в фигме некоторые моменты). Во-вторых, стили цвета также неправильно собраны. Представь, что нам нужно поменять тему сайта. Если бы у нас изначально цвета были сгруппированы правильно, то мы бы сделали это за 10 минут, скопировав группу и поменяв цвета внутри стилей, а не в самих макетах. Посмотри Мисик или ЮС бэкпанель. Там вроде все ок.

Что делаем дальше:
- [ ] Надо внести все правки, описанные выше и все комменты из фигмы.
- [ ] Сделать шаблон страницы проекта (прям отдельным пунктом выношу).
- [ ] Надо что-то сделать для фона hero. Нарисовать, анимировать или предложить что-то, для чего своих навыков недостаточно. Посмотри что можно сделать с помощью spline.
- [ ] Транслитнуть сайт и добавить функцию смены языка.
- [ ] Нарисовать каверы хотя бы для проектов, которые будут на главной.

**Comment by shatiloand** [comment]
@dakand Ответил в фигме.

> Изначально чувствовалась какое-то следование референсу без изменения под наш формат. Чувство шаблона сохраняется и сейчас.

– Честно говоря не очень понял эту формулировку.

> Мы с Андреем ждали полный десктоп не мало времени. Но страница проекта отсутствует. Мы не можем перейти к адаптацию без такой важной страницы.

– Давай разберемся чтобы не было недопонимания и чтобы эта ситуация не выглядела так, будто я чего-то не сделал :)

**В этой задаче описаны страницы, которые я взял в работу.** Если ты посмотришь, там нет "Страница проекта/кейс". Мы обсуждали это с Андреем (еще в самом начале) и частично обсуждали на созвоне с командой, но это все было в контексте следующего этапа/итерации, потому что все хотят классный сторитейлинг и такие страницы не собираются за 1,2 или 3 дня. Тем более мы обсуждали что нужно параллельно создать какой-то дефолтный набор компонентов для создания простых кейсов.

Я достаточно много времени занимался созданием кейсов, шоурилов и очень хорошо представляю сколько времени на это все может уйти. На создание одного кейса я закладывал минимум неделю. А лучше 1-2 на проработку структуры, подготовку текстов, материалов и тд. Такой кейс должен сразу собираться 

> Во-вторых, стили цвета также неправильно собраны.

– Я раз 10 перечитал, так и не понял. У меня просто группы цветов разбиты на оттенки (мне так удобнее). Может ты распишешь модель, как ты собираешь. Потому что в тупую я не вижу разницы. Исключительно кому как удобнее.
