### ISSUE TITLE
Структура сайта 

### ISSUE THREAD

**Issue by dakand** [atls/design#13]
_*Сразу оффтоп. Я уже писал ранее о том, что на выходе нам нужно получить 2 сайта. Мы начинаем именно с сайта курсов._

### Задача
Давай сделаем структуру сайта полностью. Формат структуры: Большой блок (страница) содержащий в себе маленькие блоки (блоки сайта). К каждому блоку нужно добавить короткое описание, касательно содержимого и связей с другими блоками или страницами.

Пока что у нас из страниц - Главная, страница курса, контакты, форма обратной связи, лог ин. В рамках работы со структурой под страницами я подразумеваю любую верхнеуровневую сущность, а в данном случае помимо страниц это модальные окна. Возможно для сокращения некоторых блоков на главной, некоторую информацию нужно будет также отображать в модалке. Это нужно как раз тебе и решить. Давай сделаем в фигме, можешь юзать [пример](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=16%3A11).

P.S. Касательно лог ина. Я не помню описано это в инфе от заказчика, но для сайта курсов у нас будет ЛК. Пока что это будет просто заглушка, но мы его будем развивать уже после того, как спроектируем основной сайт. Т.е. сейчас нам нужна только авторизация/регистрация.

**Comment by bbbaso** [comment]
[Бриф](https://docs.google.com/forms/d/e/1FAIpQLSdyOST77YkGak8bMRdPnKbKZvfi-N10p1PKkl3FOQPbeLH8iA/viewform?usp=sf_link) по Drum Instructor (на 5-7 мин)

**Comment by bbbaso** [comment]
Структуру доработал. Остался один небольшой блок, где нет уникального текста (вставил из аналогичного), но его уже можно докрутить, когда покажем первые варианты концепции.

Свой драфт перенес в фигме в команду.

**Comment by dakand** [comment]
@bbbaso открыл задачу заново. Давай доработаем исходя из того, что я написал в фигме.

**Comment by bbbaso** [comment]
@dakand внёс поправки
