### ISSUE TITLE
Прототипы

### ISSUE THREAD

**Issue by dakand** [atls/design#14]
На данный момент у нас уже есть сформированная структура и прототип. В рамках этой задачи будем дорабатывать прототип до варианта после которого мы можем перейти на дизайн.

Стараемся дискутировать в фигме по всем небольшим правкам. Но тут я выделю 2 проблемы и опишу как мы их решим:

1. Блок "Курсы" на главной. Сейчас ты его увеличил и концептуально это уже лучше, но у меня есть переживания по поводу того, что можно сделать иначе и лучше. В фигме я тебе уже описал аналогию. Давай попробуем найти 3-5 референсов, которые мы бы могли прям скопировать, исходя из того, что нам нужно. Рефы анимированные желательно, поэтому мб лучше на awwwards искать.

2. Блоки "Как проходит обуч" и "Чему вы научитесь". Ты всё же пытаешься страницу курса делать продающей. Но тут работает та же аналогия, что я упомянул в п.1. Мы не продаем билеты в клуб с лозунгами "Приходите к нам, потому что за 500 рублей вы получите безлимит текилы", мы рассказываем про закрытую тусовку таким образом, что люди хотят в ней поучаствовать. Когда я говорю, что блоки нужно объединить я имею ввиду не тупо список из 50 позиций с описанием каждого дня обучения, нет. Я имею ввиду (на примере):
-- Мы познакомим вас с командой (чтобы вы могли понимать кто за что отвечает и, возможно, выделили себе авторитетов).
-- Расскажем и дадим собрать прототип сайта в вебе и сделать адаптив (чтобы вы научились азам html и попрактиковались с гридами)
-- Научим работать со стилями, покажем как создавать сложные анимации (чтобы вы научились css и js)
...
-- Научим планированию и дадим возможность выбирать фреймворки для углубленного изучениея
...

Проще говоря, дай понять ребятам, что они будучи нубами всё равно будут интегрированы в команду. Это и есть, по-настоящему, конкурентное преимущество.

**Comment by dakand** [comment]
Касательно второго пункта. Давай попробуем тоже какие-то рефы поискать. Главное, что рефы нужно искать не от визуальной составляющей, а от формы подачи. Здесь может быть неплохо, если этот блок будет менять ориентацию скрола. Но я это не утверждаю.

**Comment by ArtemHovsky** [comment]
По второму пункту возникают трудности по контенту. 
Я сам не понимаю как будет проходить обучение и что они будут изучать в течении 5-6 месяцев и поэтому не могу сформулировать правильные текста.

Может лучше вместо нескольких абстрактных фраз "Вы изучите", "Мы покажем", составить приблизительный план процесса обучения, в котором будут описаны постепенные этапы например по неделям, что нужно будет учить, делать, создавать. Первая неделя: введение, Вторая: практическая и т.д.

**Comment by TorinAsakura** [comment]
@ArtemHovsky Так это не работает. Кто-то делает быстрее, кто-то медленней. Ставить сроки - ставить рамки, народу от этого некомфортно + это сильно начинает ограничивать нас.

**Comment by ArtemHovsky** [comment]
Хорошо, от процесса отходим.

Тогда нужно понять чему научаться, что будут делать  течении 5-6 месяцев .

**Comment by TorinAsakura** [comment]
@ArtemHovsky Фронты будут учиться фронтовым практикам. Бэкендеры серверным. Ты очень сильно ограничиваешь возможности подобными вопросами.

**Comment by ArtemHovsky** [comment]
Но потенциальному студенту нужно жу знать куда и на что он будет тратить свое время, пусть даже это будет и бесплатно.

**Comment by TorinAsakura** [comment]
@ArtemHovsky - куда: в академию чтобы потом попасть в команду, на зарплату и перспективы
- на что: на обучение, чтобы пройти академию и потом попасть в команду, на зарплату и перспективы

**Comment by dakand** [comment]
@ArtemHovsky резюмирую. То, что я написал выше - не догма, мы не будем это писать в финальной версии. Я просто хотел донести до тебя смысл того как можно объединить "Что вы будете делать" и "Чему вы научитесь". Если у тебя возникают сильный проблемы с формированием текста (бывает) опиши только несколько шагов примитивным языком, мы с Андреем потом напишем финальный. Ты смотришь на коммерческие школы как не на визуальный референс, а как на концептуальный. Повторюсь, мы той же концепции придерживать просто не можем. Ты сейчас находишься в небольшой стагнации, понимаю. Но не переживай. Давай, как я писал ранее - найдем реф для наших блоков и в итоге продублируем его в нашем прототипе.

**Comment by dakand** [comment]
@ArtemHovsky збс. Довнеси то, что я написал в фигме. Наведи порядок в проекте и на будущее - давай привыкать к порядку сразу. _Ещё раз повторюсь... один этап - одна страница. И то, что удобнее так как делал ты -  не правда, это просто твоя привычка. Можно шорткатом переключать страницу с одной на другую в которой уже будет в фокусе нужный тебе объект, а не двигать постоянно мышкой и зумить нужный тебе элемент, что совсем неудобно._

В референсах еще обязательно структурируй всё. У нас есть в целом мудборд, но есть топовые рефы (с ссылками), есть рефы по блокам. Подпиши группы референсов, чтобы мы не терялись в них потом.
