### ISSUE TITLE
Анализ дизайна Banxe 

### ISSUE THREAD

**Issue by dakand** [atls/design#16]
Вот [фигма](https://www.figma.com/file/BkwhmKS1X9O2Zzl2QuA9Q7/Banxe-Digital-Design-(Copy)?node-id=0%3A1) на их проект. Не буду затирать как лучше анализировать, но я бы хотел чтобы ты прошёлся по "Main" и "Help Center" и составил список того, что на твой взгляд явно плохо или что можно сделать лучше (в первую очередь - визуально, во вторую с точки зрения логики).
Более глубоко я посмотрю сам, но как и говорил на созвоне, мне очень поможет твоё мнение. Чем раньше получится это сделать, тем лучше. Не трать на это больше 3-4 часов.

**Comment by shatiloand** [comment]
Ну смотри. Разбирать каждый экран – это тумач, там на каждой странице будет по пачке комментариев, которые будут говорить про одно: очень плохо спроектированная навигация и очень устаревшие подходы в дизайне.

У меня есть некоторая экспертиза в финтехе и около-крипто проектах, постарался максимально глобально посмотреть на всю задачу и сформировать общее мнение. Ссылка на текст: https://docs.google.com/document/d/197nP8YUIuHUeAUiOQWeiiwfhRzdWH0FsTt0PPp5j03I/edit?usp=sharing 

Надеюсь поможет)

**Comment by TorinAsakura** [comment]
@shatiloand сделано неплохо, но, мало конструктива, много эмоций, нужно больше сухого остатка
думаю в этом нам @dakand поможет

**Comment by TorinAsakura** [comment]
Блок про "позиционирование" очень полезный вышел, только эмоций поменьше)

**Comment by dakand** [comment]
@shatiloand  "...позиционируете себя как симбиоз Revolut и традиционной централизованной биржи" почему ты сделал такой вывод (касательно Revolut)?

**Comment by shatiloand** [comment]
@dakand Revolut из обычного нео-банка превратился в финансовый агрегатов (я не знаю как это правильно назвать), где ты можешь держать как обычные деньги (во всех валютах мира), можешь прикупить акций тут же в приложении у брокера и немного крипты для разнообразия и еще куча всего. И да, у них по-моему даже есть своя дебетовая крипто карта (но не уверен).

Banxe по моим ощущениям делают тоже самое, только со стороны криптовалюты, они хотят совместить традиционные финансы и крипту в одном кошельке (приложении) только с элементами уже крипто-стандартов: стейкинг и пулы ликвидности (на сайте они пишут про это просто Crypto Earn), торговлю (возможно то, что ты не увидел традиционного терминала/графиков как раз этим и обусловлено, типа они хотят сделать простую штуку, где ты приходишь и покупаешь просто по рынку в один клик какой-то крипто-актив и тебя не заставляют вникаешь в графики. Ты их просто не видишь), дебетовая карта и тд.

Вообще сейчас появляется тренд говорить что какой-то крипто-проект – это банк. Разумеется без традиционных финансовых институтов. Просто слово "банк" максимально понятна обычному юзеру. Может как раз они и хотят себя позиционировать как крипто-банк но не могут это сформулировать.

Такие дела. К моим таким рассуждениям лучше относиться как к потоку информации :) а дальше уже выдергивать зерно.

**Comment by dakand** [comment]
Пасыбы🔥
