### ISSUE TITLE
YouThink | Редизайн лендинга

### ISSUE THREAD

**Issue by dakand** [atls/design#17]
Про YouThink мы уже рассказывали. У нас есть точка входа - лендинг (вот [фигма](https://www.figma.com/file/hVmJam0jzM9J4Q651e0urR/Youthink-%7C-Landing-page?node-id=0%3A1) на него). Он очень простой, надо его сделать немного интереснее и добавить анимаций. Этот проект в фигме оставим, поэтому в репе YT  создай новый проект "Youthink | Landing page 2.0" и работай в нём. Что нужно сделать:

- [x] Подберём референсы. Не хочется уходить от лёгкости и от светлых оттенков. Нужно добавить небольшие фишечки, определяющие уникальность дизайна (например, неравномерно скруглённые углы на кнопках как у Андрея в Atlantis Design). Смотри рефы с анимациями обязательно, т.к. далее нам их придётся делать.

- [x] Редизайн. Исходя из подобранных рефов и некоторых структурных изменений* переделать лендинг.

- [x] Подготовить текстовый сценарий поведения элементов и переходов при скроле на сайте для дальнейшего анимирования. Для анимации сделаем отдельную задачу.

*Структурные изменения:
1. На первом экране идут преимущества. Кмк, важны только количество респондентов (всего или в день, хз пока), сумма выплат (всего или в день, хз пока), количество клиентов и, возможно, количество опросов, которое проходит средний пользователь за промежуток времени.
2. Добавить примеры опросов.
3. Возле блока или в блоке "Ваше мнение будет влиять на:" нам нужно показать несколько практических кейсов влияния опросов на решения компаний. Кейсы найдём позже, поэтому пока сам придумай от себя кейс. Больше вопрос как хорошо его интегрировать в лендинг. Формат простой - краткое описание кейса и дата реализации.
4. Добавить FAQ.

P.S. Это не обязательно должен быть снова one screen.

**Comment by dakand** [comment]
@sorokoumov [глянь](https://www.figma.com/file/mGfDgpXyT7XhaVw3THPKyk/Youthink-%7C-Landing-page-2.0?node-id=96%3A2701) по структуре, тексту и визуалу

**Comment by dakand** [comment]
@ArtemHovsky немного доработал [лендинг](https://www.figma.com/file/mGfDgpXyT7XhaVw3THPKyk/Youthink-%7C-Landing-page-2.0?node-id=196%3A3044) и оставил тебе комменты, отработай их. Должно быть:
1. Главная страница в статике, состояние секшенов, если их несколько (как в секшене с этапами).
2. Компоненты и фрагменты на отдельной странице в соответствии с нашими правилами.
3. Стили в соответсвии с нашими правилами.

**Comment by dakand** [comment]
@ArtemHovsky После этого нужно будет сделать:

- [ ] Интерактивный прототип страницы. На которой мы как раз покажем как будет загружаться хиро, как будет работать блок с хиро и прочее.
- [ ] Раскадровку анимации для блока с мокапом сервиса. 
- [ ] Адаптив в статике со всеми состояниями.

P.S. Раскадровку делать схематично, можно к прочему делать текстовую раскадровку. Если не делал подобное или не знаешь как - пингани, я расскажу.

**Comment by dakand** [comment]
@ArtemHovsky прежде чем начнёшь делать интерактивный прот, сделай ещё форму обратной связи. Совсем забыл про неё. В ней будет.
1. Почта отправителя.
2. Тема (Регистрация, проблемы со входом, реферальная программа, предложения об улучшении, другое)
3. Описание проблемы.

Ну и соответсвенно саксесс и инвалид состояние отправки формы.

**Comment by dakand** [comment]
@ArtemHovsky лендос ок выглядит. Только надо все компоненты и фрагменты убрать на отдельную. Какие проблемы сейчас у тебя:

**Стили текста:**
Во-первых, у тебя аж 4 body, но в деле я увидел только 2. Даже если они где-то применены, то лучше не делать больше 3 вариантов body. Во-вторых, неправильно сгруппировал стили - у нас может быть body, subtitle, caption, link и т.п. и это разные вещи, а у тебя в рамках body 16 (например), есть стиль с lh 1.2, есть с 1.5. _Кмк, я об этом не один раз говорил и говорил про множество проектов в нашей фигме, на которые можно ориентироваться._

**Стили цветов**
У нас не может быть Black, White, Grey. У нас должно быть primary, secondary, invert и т.п. Об этом я точно не один раз говорил и приводил пример с быстрым инвертированием темы внутри фигмы. Аналогично предыдущему пункту - внутри нашей фигмы есть проекты с примерами.

**Интерактивный прототип**
У нас суть этого этапа, чтобы условно показать как будет выглядеть страница при скроле (как будете вести себя элементы), а у тебя переходы между экранами происходят через затухание. Я делал интерактивный прот для академии, когда делал концепт - принцип тот же.

**Comment by ArtemHovsky** [comment]
@dakand 
Посмотри пожалуйста все макеты, адаптив, интерактивный прототип

**Comment by dakand** [comment]
@ArtemHovsky комменты оставил

**Comment by ArtemHovsky** [comment]
@dakand 
Внес правки, доделал интерактивный прототип. Вроде все готово. Посмотри пожалуйста

**Comment by dakand** [comment]
@ArtemHovsky чутка осталось докрутить, комменты оставил

**Comment by ArtemHovsky** [comment]
@dakand 
Внес правки, посмотри пожалуйста

**Comment by ArtemHovsky** [comment]
@dakand 
Доработал интерактивный прототип

**Comment by dakand** [comment]
@ArtemHovsky красава! Задачу закрываю
