### ISSUE TITLE
Знакомство с проектом Кинорепортёр (КР)

### ISSUE THREAD

**Issue by dakand** [atls/design#18]
Тебе нужно изучит вводные для проекта. Скоро подключу тебя к этапу прототипирования. Нужно:

- [ ] Изучи сайт https://kinoreporter.ru/. Там структура ппростая, все страницы категорий и публикаций шаблонные. Просто нужно понять из чего он состоит.
- [ ] Изучи [информацию](https://www.figma.com/proto/pUWwcuHo61RiwLEzNztoGZ/Web-site?page-id=0%3A1&node-id=16%3A487&viewport=340%2C48%2C0.24&scaling=min-zoom&starting-point-node-id=16%3A487) из первого этапа работы над КР. Там точечный и общий анализ, структура.
- [ ] (Опционально) Составь мне список вопросов, которые тебя интересуют.

**Comment by bbbaso** [comment]
- **Сайт изучил**
- **Ознакомился с анализом**
- **Сделал краткий аудит в [файле](https://www.figma.com/file/cbWdZ8MrqvqxyiVR1SpDSS/%D0%9A%D0%A0?node-id=0%3A1)  (оставил поинты, актуальные на этой стадии, были и точечные недостатки, но их решил пока убрать)**
_*Аудит делал больше для себя, но если есть комменты по поинтам, то велкам_

- **Вопросы там же**

**Comment by dakand** [comment]
Ответы:
1. В конце июня должен быть уже готовый дизайн-проект.
2. https://github.com/torin-asakura/kino-reporter/discussions тут много информации. Из важного можешь посмотреть "Бриф". Всё самое основное помимо брифа есть в анализе, который ты изучил.
3. Они зарабатывают со спонсорства, зарабатывают с журнала. С журнала можно начать зарабатывать больше и качественнее и хоть это не сильно увеличит прибыль, то это даст старт для внедрения новых продуктов. Также улучшение медийной составляющей даст больше возможностей для рекламы.
