### ISSUE TITLE
Дизайн-концепт

### ISSUE THREAD

**Issue by dakand** [atls/design#19]
Давай начнём с концепта, немного пожуём его прежде чем дизайнить весь сайт. Для концепта возьмем первые 2-3 блока главной. Ответственность полностью на тебе, пока лезть не хочу, тем более рефы которые ты собрал более чем. Не бойся копировать что-то. К задаче приступаем сразу после того, как проты доделаем, а там совсем чуть чуть.

**Comment by ArtemHovsky** [comment]
Сделал концепт дизайна v1, посмотри пожалуйста:
https://www.figma.com/file/TRNQoY3DBNRursnvMDwm02/Landing-page?node-id=0%3A1

**Comment by dakand** [comment]
откомментил
