### ISSUE TITLE
аватарки для ботов

### ISSUE THREAD

**Issue by TorinAsakura** [atls/design#20]
У нас периодически пополняется армия ботов. Это могут быть аккаунты на гитхабе, или в телеге.

На данный момент нужны аватары для:
- youthink-bot
- atlantis-bot
- atlantis-payment-bot

**Comment by dakand** [comment]
@bbbaso Ром, задача на тебя. [Вот](https://www.figma.com/file/wC1teRe7FsrQqWGAliXtQF/All-Identity?node-id=358%3A2) наши другие аватары. Делай по тому же принципу. Только аватары для ботов должны быть с одним фоном, но отличаться от темно синего (основные каналы телеги) и светлого (Атлантис основной).

**Comment by dakand** [comment]
@bbbaso переделать надо. Можешь несколько вариантов делать (цвет фона и цвет элемента) на примере одного. Который норм будет, от него и работай.

**Comment by bbbaso** [comment]
@dakand закинул новую порцию

**Comment by TorinAsakura** [comment]
@bbbaso Трабл в том, что это никак не идентифицирует бота. Я предполагал, что там будет какая-то иконка типа мозга, или что-то связанное с принадлежностью субъекта к интеллектуальной автоматизированной системе, а то не понятно что это за иконка и причём тут бот.

Как пример https://www.google.com/search?q=intelligent+icon&tbm=isch&ved=2ahUKEwjo38ydqOv3AhUMx4sKHcqhDlcQ2-cCegQIABAA&oq=intell+icon&gs_lcp=CgNpbWcQARgAMgYIABAeEAcyBggAEB4QBzIGCAAQHhAHMgYIABAeEAcyBggAEB4QBzIGCAAQHhAHMgYIABAeEAcyBggAEB4QBzIGCAAQHhAHMgYIABAeEAc6BAgjECc6BAgAEEM6BQgAEIAEUK8WWLYZYMYlaABwAHgAgAGiAogB4wWSAQU2LjAuMZgBAKABAaoBC2d3cy13aXotaW1nwAEB&sclient=img&ei=bRaGYqj1CYyOrwTKw7q4BQ&bih=1388&biw=2560&client=safari

**Comment by bbbaso** [comment]
Новый завоз

Только используя мозги или "ножки" контактов, появляются лишние детали, и иконки уже отходят от общей стилистики(

**Comment by TorinAsakura** [comment]
@bbbaso @dakand help )

**Comment by TorinAsakura** [comment]
@dakand СЕКС! И такой же, пожалуйста, для i-link, без payments

**Comment by TorinAsakura** [comment]
@dakand up

**Comment by dakand** [comment]
Ниче пока интереснее по мерчу не придумал. Пока [это](https://www.figma.com/file/wC1teRe7FsrQqWGAliXtQF/All-Identity?node-id=1231%3A56) давай юзать.
