### ISSUE TITLE
Дизайн Academy

### ISSUE THREAD

**Issue by dakand** [atls/design#23]
Сделал [концепт](https://www.figma.com/file/TRNQoY3DBNRursnvMDwm02/Landing-page?node-id=927%3A2368) (оставил комменты в фигме) и собрал [интерактивный прототип](https://www.figma.com/proto/TRNQoY3DBNRursnvMDwm02/Landing-page?page-id=887%3A2241&node-id=932%3A11084&viewport=-718%2C261%2C0.08&scaling=min-zoom&starting-point-node-id=932%3A10803) для понимания работы некоторых элементов. 

Продолжаем работу над дизайном сайта. Сначала ознакомься с коментами и пойми как с этим работать. Там есть коммент по шрифту, надо поискать антикву. Для начала сделаем все страницы (в статике), которые есть в прототипе. Дальше будем работать с новыми страницами, стейтами и анимациями. Компоненты интегрируй сразу, стили создавай тоже.

### Страницы:
- [ ] Главная страница
- [ ] Страница курса. _Страница курса у нас будет не просто переходом на другой линк. Страница ккрса будет как бы выезжать снизу. Реф потерял, но в версии Шатило похожий переход на главной._
- [ ] Страница учебного материала. _На примере какого-то сторитела. Там мы будем текстом и картинками раскрывать тему какую-то._
- [ ] Страница всех учебных материалов. _Тут важно учесть что она будет открываться как и с линка на старнице так и с дропдауна в шапке._
- [ ] Форма обратной связи.
---
### Графика:
- [ ] Анимация для главной. _Она сложная из-за блюра, поэтому сам буду моделировать._
- [ ] Для всех учебных материалов нам надо что-то придумать. Мб даже не обязательно 3D. Надо покреативить, посмотреть примеры. Идеально бы было, чтобы одна графика использовалась и в превью и на странице материала.
- [ ] Придумать 3д для блока "5 студентов в группе" на главной.
- [ ] Придумать 3д для блока "процесс обучения" на главной.

**Comment by dakand** [comment]
Смотри какой [референс](https://dribbble.com/shots/18178306-Neuralight-homepage) подходящий под нас нашёл.

**Comment by dakand** [comment]
Оставил тебе некоторые комменты в фигме. Некоторые блоки на главной были доработаны хорошо. Основная претензия в том, что ты почему-то стал изменять некоторые вещи относительно концепта, которые образовывали ту самую стилистику, которую я тебе описывал. В некоторых моментах ты сломал ритмику, изменив размеры отступов. Поэтому надо бы откататиться назад по блокам, которые есть в концепте. Страница проекта сыроватая, но стиль ты определил - это збс. Как это дело улучшить сейчас напишу в чат. Главный коммент я сейчас отредактирую, напишу план действий.

**Comment by dakand** [comment]
@ArtemHovsky пока не получается с дизайном. Проектирование страниц в итоге возьму на себя. Доведи страницу курса до точки (как считаешь нужным, без экспериментов) или просто верни что у тебя было. Перейди к следующим страницам, которые описаны в задаче, допиливай их на свое усмотрение, я потом возьму их за основу.

**Comment by ArtemHovsky** [comment]
Главная страница:
- Доделал блок "Стипендия и хантинг".

Страница курса:
- Сделал блоки: Процесс обучения, Преподаватели, Кейсы.
- Анимация открытия страницы курса, подбор референсов.

Страница материалы:
- Сделал примерный прототип, подобрал референс по анимации.

Форма обратной связи.
Наполнение дизайн системы: Inputs, Dropdowns, Icons, Buttons и все их состояния.

Подбор референсов:
- Анимация главной страницы, скролл, появление блоков, текста.
- 3D референсы для блока "Курсы и материалы", "Процесс обучения"

**Comment by dakand** [comment]
@bbbaso по результату работы у нас уже есть часть сайта, которая перед продакшеном окажется практически неизменной. Изначально проект подразумевался, как сайт для обучения. Т.е. есть ученики у академии, которые будут практиковать свой навык на сайте академии. Для того, чтобы практика была поэтапной как мы и задумывали, мы должны создать 7 этапов проектирования согласно со [списком применённых навыков по этапам](https://github.com/atls-academy/web/wiki/План-разработки-по-этапам-для-студентов).

В списке для каждого этапа есть применённые технологии, а также структурные и визуальные отличия данного этапа. Так, первый экран будет выглядеть как прототип хиро и с каждым этапом страница будет увеличиваться и наполняться деталями.

[Это](https://www.figma.com/file/TRNQoY3DBNRursnvMDwm02/Landing-page?node-id=927%3A2368) конечный макет с которым мы работаем (по сути это 7 этап). [Это](https://www.figma.com/file/Z8m03nUsEoolW0WcLMU93h/Atlantis-Academy-(work-project)?node-id=796%3A8) мини-пример того, что должно получиться. У нас есть страница "1 step" и "2 step", на ней разный вид макетов.

В репе Academy создай новый проект и делай всё в нём. Как будет возможность сообщай о прогрессе, т.к. это АСАП. Мне кажется, что на раздевание десктопа не должно уйти больше дня.

---

P.S. @TorinAsakura только есть одна проблема, которую я не учёл - нет адаптива. После того как Рома сделает это, то сразу приступит к адаптации. Это я к тому, что адаптив будет позже на 1-2 дня.

**Comment by bbbaso** [comment]
@dakand готово 

_*как и обсуждали, некоторые этапы мы скипаем, поэтому их нумерация в файле уже иная_

[Файл](https://www.figma.com/file/SHoss54mn2SZLnI0e3OiJj/Practice?node-id=15%3A376)

**Comment by TorinAsakura** [comment]
> @dakand готово
> 
> _*как и обсуждали, некоторые этапы мы скипаем, поэтому их нумерация в файле уже иная_
> 
> [Файл](https://www.figma.com/file/SHoss54mn2SZLnI0e3OiJj/Practice?node-id=15%3A376)

@TFK70 check

**Comment by TorinAsakura** [comment]
как по мне - что-то уж больно резкий переход и разница между 1 и 2 шагами, а между 2 и 3 только один маленький блок

**Comment by bbbaso** [comment]
@dakand мб тогда сделать как я делал изначально?
каждый новый блок создавать в формате варфрейма и к след этапу уже добавлять цвет

**Comment by dakand** [comment]
> @dakand мб тогда сделать как я делал изначально? каждый новый блок создавать в формате варфрейма и к след этапу уже добавлять цвет

@bbbaso не, так не пойдёт, т.к. по задумке только на первом этапе ученик работает с html и grid, потом он уже стилизует полученный результат и возвращаться к навыкам первого этапа ему не нужно. Давай просто сдвинем добавления блока курсов на 2 этап. Т.е. отличие 1 и 2 будет только в добавлении "цвета". А 2-3 мы уже добавим блок курсов. Соответсвенно, "Process" смещается на 4 этап.

**Comment by dakand** [comment]
@bbbaso дополнительно рядом с каждым макетом добавь описание с тем, что есть и изменилось относительно предыдущего этапа. Можешь даже немного заморочиться и сделать развёрнутое описание со скринами, типа "Добавили скругления на секшенах" и скрин.

**Comment by dakand** [comment]
@bbbaso после этого нужно сделать адаптив. Делаем адаптив конечного макета и потом делим также на этапы.

**Comment by bbbaso** [comment]
@dakand готово

- Добавил каждому этапу фрейм с прогрессом
- Сделал адаптив (компоненты также добавил)

**Comment by dakand** [comment]
> @dakand готово
> 
> * Добавил каждому этапу фрейм с прогрессом
> * Сделал адаптив (компоненты также добавил)

Комменты по адаптиву в фигме оставил, нужно ещё поработать над адаптивом. Если нет идей, ищи рефы.

**Comment by bbbaso** [comment]
@dakand поправил комменты

**Comment by dakand** [comment]
> @dakand поправил комменты

Ещё добавил комменты. Также нужно сделать стили по цветам и тексту. Отдельно для десктопа, отдельно для адаптива, но по опыту КР ты уже знаешь че делать. Но если че пиши.

**Comment by bbbaso** [comment]
@dakand комменты поправил, сделал стили, но есть небольшой затык с цветами (в целом и с ховерами кнопок)

_*p.s. думал подсмотрю UI кит с первого файла, но, честно, так не понял там логики в кнопках_

**Comment by dakand** [comment]
@bbbaso я в Figma оставил комменты. Некоторые комменты имеют рекомендательный характер, некоторые - это твои упущения. Я большинство комментов своих же сам исправил, поэтому они в формате "сделал это, сделал то". Неокторые тебе нужно доисправить. Ну и всё что получиться в итоге должно быть на всех наших 6 этапов.

P.S. Будь внимательнее к деталям. Пока этого не будет, я не смогу давать тебе более ответственные задачи.

**Comment by bbbaso** [comment]
@dakand добил комменты

**Comment by dakand** [comment]
> @dakand добил комменты

один новый коммент добей

**Comment by dakand** [comment]
Временно закрою, чтобы почистить актуальный пул задач.
