### ISSUE TITLE
Дизайн Drum In

### ISSUE THREAD

**Issue by dakand** [atls/design#24]
### [Интерактивный прототип](https://www.figma.com/proto/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?page-id=835%3A2991&node-id=835%3A2991&viewport=1109%2C394%2C0.04&scaling=scale-down-width&starting-point-node-id=1216%3A16839).
---
### Важно
Первое, что нужно обозначить. Концепт это концепция дизайна, а не полноценный дизайн. В рамках концепта достаточно поработать с первыми 2500px (3-4 блока). На выходе мы можем получить несколько вариантов (с разным визуальным оформлением, шрифтами, цветом) но только если в том видит необходимость дизайнер, т.к. в идеале диз должен показать один вариант выбранный им. На концепте важно показать тем, сетку, настроение, цветовую гамму = стиль.

### Что имеем:
1. Первая версия дизайна Ромы. Ром, не нашёл в проекте твою версию. Добавь и прекрепи ссылку.
2. [Концепт от Артёма](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=307%3A147). Тут есть что-то.
3. [Дизайн от Артёма.](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=323%3A109). Из концепта не получилось сделать то, что хотелось бы. Основные ошибки - большие объекты, темп слишком спокойный, структурно страница очень близка к стандартным обучающим сайтам.

### В рамках этой задачи сделаем два пункта:
**Референсы**
Ещё поищем референсы, но уже более точечно. Пока что мы не вытягиваем именно из-за этого. Мы уже определились, что нам нужен андерграунд. Нужно еще накидать примеров использования такой тематики. Также нужно посмотреть рефы по темпу/структуре. Тебе с этим поможет Лёша у которого не только хорошая насмотренность, но он ещё и музыкальный человек.

**Дизайн-концепт**
Их может быть несколько, если ты в этом видишь необходимость. Принцип описал выше.

P.S. Этап сбора рефов постарайтесь согласовать со мной.

**Comment by dakand** [comment]
@bbbaso FYI по концепту. Сейчас твои прототипы выглядят как что-то большее. Увидев твой дизайн я в этом убедился - ты сделал хорошие проты, постарался их сделать не самыми стандартными, но на дизайне всего лишь  стараешься раскрасить элементы, поменять шрифты, при этом оставив форму, расположение элементов, ритмику и сетку сайта неизменной (мб с чем-то я могу ошибиться, т.к. твоего сайта нет перед глазами). Так у нас ничего не выйдет. Именно поэтому я стараюсь не вкладываться в проты с визуальной точки зрения, т.к. я понимаю, что на дизайне я буду экспериментировать (все проты у меня однотипные по стилю).

Пример:
[Вот](https://www.figma.com/file/TRNQoY3DBNRursnvMDwm02/Landing-page?node-id=605%3A171) что у нас было на протах академии, [вот](https://www.figma.com/file/TRNQoY3DBNRursnvMDwm02/Landing-page?node-id=927%3A2368) что получилось на концепте. Абсолютно разные вещи.

**Comment by bbbaso** [comment]
Ошибку понял, учту в будущем. На счет дизайна — ты меня перекинул в КР на стадии концепта, поэтому там и лежит 3 моих макета

**Comment by bbbaso** [comment]
@dakand 
Разобрал старые рефы и добавил новые. Те, что отметил комментом, мне зашли, можно будет применить.

_*траблы пока только с типографикой, мб в  своих концепциях использую Артёма варианты_

Все [тут](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/?node-id=0%3A1)

**Comment by dakand** [comment]
Посмотрел. Из новых рефов мало что зашло. Но в целом я отобрал лучшее на мой взгляд за три подхода подбора рефов. Также сделал небольшой драфт для тебя, чтобы была какая-то точка старта. Все [тут](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=395%3A61).

Все рефы разделил на группы и группы откомментил (что там нравится). Штуки, которые в конечном итоге нам помогут прийти к ожидаемому результату:
1. Палитра. У нас будет темная тема и нужно выбрать контрастный цвет (скорее всего оранжевый, жёлтый или зелёный).
2. Шрифты. Из референса можно подобрать что-то подобное. Если для заголовков будешь юзать гарнитуру с широкими буквами, то для наборного используй обычной ширины (в целом как на главном примере по шрифтам).
3. Больше острых углов и меньше скруглений.
4. Стилистические элементы: граффити, наклейки, стикеры.
5. _Сначала небольшое отступление. В ближайшие полгода мы перестаем делать принципиально новый UI для каждого проекта - нам нужно образовывать узнаваемый стиль. Один из принципов, который этот стиль будет определять - повсеместное использование 3D_. В Drum in нам нужно так же показать "объём" c помощью использования 3д или глубоких градиентов. Чтобы юзать 3д, тебе не нужно моделировать специально. Можешь вырезать картинки из примеров, удалять фон в фотошопе или накладывать с режимом наложения, можешь даже использовать какие-то фигуры, чтобы показать что тут будет модель.

Продолжаем делать концепт на примере первых 3-4 блоков. Пингуй в процессе @sorokoumov.

**Comment by bbbaso** [comment]
**Есть начало новых концептов.** 

Относительно вчерашнего созвона и комментов от Лёши есть вопросы

Касаемо 3Д в проекте:

а) Не понимаю связь между новостью о новом визуальном стиле нашей компании и обязательном внедрении 3Д теперь в каждый проект, тем более когда проект забрифован давно + мы с тобой обсуждали в начале андерграунд стиль и все, что из него вытекает, и от этого у меня диссонанс - между 3Д модельками и подобным стилем. Сайт с NFT крокодилами крутой, тут ниче не скажешь, но стиль там совершенно иной, больше Digital истории гораздо. Не вижу, опять же, связи с граффити, стикерами, скетчами, потертостью и т.п.

_*и для меня сегодня уровень 3Д на том сайте пока "журавль в небе"

б) Даже если внедрять 3Д в проект, то тут у меня второй диссонанс уже с самим курсом. Контент в нём достаточно посредственный, мягко скажем, то есть 8-минутные ролики, снятые в фоновом режиме, где даже нет прямого контакта со зрителем (это единственное, что я берусь судить, так как прекрасно знаю, что такое обучение в музыкалке и обучение онлайн). И поэтому пользователям (я предполагаю) очень странно будет видеть крутой вызывающий крэйзи стиль с 3Д, когда сам курс далеко не такой.

-----------

Поэтому я пытаюсь и предлагаю вытаскивать композицию на сайте за счет типографики, сетки, может горизонтального скролла в каких-то местах и разного шума. Возможно использовать стоковые фотки, так как сам учитель на своих фото не лучшим образом вписывается в андерграунд.

**Comment by dakand** [comment]
@bbbaso неплохо, продолжай в том же духе. Есть какие-то ошибки конечно, но они допустимы на стадии концепта.
Касательно 3д. Ты слишком радикально это воспринимаешь. Банально, можно сделать какой-то градиент или 3д модель, накинуть на неё зерно и добавить на фон с режимом наложения - появится глубина, которая будет нам подходит по стилю. Но это грубый пример. Ты правильно написал за счёт чего вывозить - так и работай. Если ты пока не понимаешь как объединить стили, то работай по своему, а я позже к концу дизайна сам постараюсь внедрить 3д, если увижу в этом необходимость или возможность.

**Comment by bbbaso** [comment]
@dakand есть концепты, комменты внутри

Жду твой фидбэк

**Comment by dakand** [comment]
@bbbaso я оставил тебе комменты по главной. Давай её доведём до конца и потом пойдём дальше. Сейчас опишу шаги.
### Шрифт
Не скажу что мне прям не нравится, но есть ощущение, что можно сделать лучше. Давай сделаем несколько вариантов на сонове первых трёх блоков (до курсов включительно) где-нибудь на другой странице с использованием разных стилей шрифтов:
1. Типа как [тут](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=0%3A1). Хочу увидеть смешение гротеска и декоративной антиквы в заголовках.
2. Сейчас заголовок у тебя condensed, давай наоборот сделаем wide, но также гротеском (montserrat сразу минус).
3. TT Lakes, TT Mussels попробуй вариант с этими шрифтами.
4. Если мы в предыдущих вариантах ни к чему не приходим, то оставляем текущий. Но сами гарнитуры попробуем использовать другие. Вместо roboto condensed можно заюзать din pro, din condensed или других похожие. Для наборного ты сейчас юзаешь такой sf в котором постоянно нужно уменьшать межстрочник. МОжно взять какой-нибудь sf ui display и там всё будет в порядке, но также можно попробовать inter или helvetica.
Как сделаешь варианты с разными гарнитурами - пингани.
### Стили и структура
Если есть заголовок и блок курсов, то они должны быть объединены в один секшен, а базовые элементы внутри должны быть по сетке. Формируй сразу стили шрифтов и цветов (обращу внимание, что цвета нужны только системные, градиенты на фоне такими не являются). Сделай это всё, чтобы потом эти стили применить к другим страницам.
### Интерактивный прототип
Сделай прототип главной, на котором покажи все работу сайта при скроле и, возможно, взаимодействие с некоторыми элементами.

**Comment by dakand** [comment]
@bbbaso как дела со шрифтами?

**Comment by bbbaso** [comment]
@dakand на счет связки гротеска и декоративной антиквы — не нашел подходящую антикву, которая была бы похожа хотя бы отдалённо на реф, все что нахожу, отдаёт чем-то старославянским

На счет **wide** шрифтов — те, что ты предложил, не то что бы wide, **TT LAKES** кстати идентичен шрифту, который я юзал в Concept 2.0 (тебе он не зашел), поэтому остановился на **DRUK**, почти тот же, что юзал Артём. И с wide шрифтом я бы не юзал антикву, т.к. она хороша в связке с condensed (собственно как и на рефе есть)

Наборный взял **sf pro display**

Сейчас делаю два варианта  — с **DRUK** и альтернативу с **DIn Pro** (*немного еще допилю блок курсов, чтобы полноценно тестить шрифты)

**Comment by bbbaso** [comment]
@dakand, **сделал неск вариантов + показал пары с гротеском** (только применить его к макету у меня не выходит, если сможешь, покажи примерно как ты это видишь)

[Файл](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=680%3A4656)

**Comment by dakand** [comment]
@bbbaso я там комменты оставил с твоей отметкой. Чекни, как сядешь. Я мб не смогу рано созвонится.

**Comment by bbbaso** [comment]
@dakand сделал [главную](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=784%3A822) 

Привязал стили, как ты просил + неск элементов в варианты собрал

**Comment by dakand** [comment]
@bbbaso  посомтрел, немного комментов оставил, отработаешь. Основная проблема, которую нужно решить перед тем как переходить к проектированию интерактивного прототипа - плоха структура макета. В одном из комментов я писал что-то, но тут продублирую: В некоторых секшенах у тебя разные паддинги и отступ, в блоке "выберите свой курс" например, тайтл добавлен в автолейаут и на него добавлен левый паддинг, хотя это должно контролироваться настройками материнского секшена. Нужно эти мелочи также исправить и сделать все аккуратно.

Когда перейдешь на проектирование интерактивного прота, то учти, что у нас будет две страницы "Desktop", где все конечные макеты в статике будут и отдельная страница "Interactive prototype", куда мы копируем макет из первой страницы и там уже работаем над интерактивным прототипом.

**Comment by bbbaso** [comment]
@dakand 

1. Навел порядок в структуре
2. Полечил стили, ориентировался на наши предыдущие проекты
3. Сделал прототип (внутри есть пару комментов если что)
*делал с интерактивными компонентами, поэтому можно потыкать на всё (почти)

**Comment by bbbaso** [comment]
@dakand 

Сделал страницу "Большого" курса и 3-х внутренних + примерно показал анимацию.
Но завтра лучше стоит созвониться (не на долго), т.к. комментами скорее всего не обойтись

**Comment by bbbaso** [comment]
@dakand 

Вопрос — модалке обратной связи и оплаты оставить стандартный вид (_белый bg и акцентная кнопка_) или стилизовать их под сайт?

**Comment by dakand** [comment]
@bbbaso стилизовать

**Comment by bbbaso** [comment]
@dakand 

**Внёс правки по блокам (интерактивы обновил также по ним)
Анимацию с менюшкой и FAQ добавил**

_*блок с курсами горизонтальный всё так же виснет при анимации (мб только у меня), хотя градиенты на bg разделил (как ты говорил), скорее всего дело в стикерах, т.к. на них тож много градиентов_

**Comment by dakand** [comment]
@bbbaso я оставил комменты по оформлению, внеси завтра первым делом.

@TorinAsakura проект можно смотреть, ссылки в самом начале добавил. Обязательно посмотри интерактивный прот, Рома постарался и получилось очень хорошо. Завтра он внесёт оставшиеся правки по оформлению и дизайн можно будет считать завершённым.

**Comment by bbbaso** [comment]
@dakand оформление поправил, правки тож починил

**Comment by dakand** [comment]
@bbbaso дофиналь правки новые

**Comment by dakand** [comment]
@TorinAsakura проект готов. @bbbaso красава!

**Comment by TorinAsakura** [comment]
@dakand комменты пожалуйста все порезолвь, от их обилия глаза режет

**Comment by TorinAsakura** [comment]
@dakand там есть элементы "связаться" и "войти", но, я сходу не смог найти результата взаимодействия с ними. Есть что-то по этим вещам?

**Comment by dakand** [comment]
@TorinAsakura коменты отмечу. Связаться - там есть форма обратной связи. Про ЛК говорил. @bbbaso убери пока из фрагмента шапки кнопку "Войти" (но не удаляй).

**Comment by TorinAsakura** [comment]
> @TorinAsakura коменты отмечу. Связаться - там есть форма обратной связи. Про ЛК говорил. @bbbaso убери пока из фрагмента шапки кнопку "Войти" (но не удаляй).

Не говори, что ты о чём-то говорил, раз я об этом спрашиваю снова - лучше напиши, о чём ты мне там говорил…

**Comment by bbbaso** [comment]
@dakand Done

**Comment by TorinAsakura** [comment]
@dakand комменты в фигме

**Comment by dakand** [comment]
@bbbaso Пришли комменты от Марины, нужно отработать их. Это приоритетная задача, остальные задачи пока отложи. Комменты даны только в десктопной версии, нужно учесть на адаптиве в том числе. По некоторым комментам Марины оставлял свои ответы. Все комментарии в основном по тексту, но есть некоторые, которые изменят расположение элементов. Спорить с комментами я вроде не увидел смысла, т.к. они все адекватные. Отработать нужно всё в течении дня.

**Comment by dakand** [comment]
@bbbaso после того как отработаешь всё, поищи на awwwards.com референсы с "падающими" элементами. В нашем случае речь идёт про теги курсов. Нам нужно будет показать этот пример фронту.

**Comment by dakand** [comment]
@TorinAsakura мне кажется, что Марина не смотрела интерактивный прототип. Пусть сделает это, если ещё не посмотрела. И там я на один коммент ей ответил (по поводу альбомов и фестивалей), нужен дополнительный текст.

**Comment by bbbaso** [comment]
@TorinAsakura Марина зашла, но не оставила комментов по альбомам и проектам (в блоке "Основатель школы"), Саня просил тебя пингануть, чтобы ты пинганул её.

@dakand поправил, внутри есть пару моих комментов, глянь их как сможешь.

Вот [тут](https://bridgelanding.qodeinteractive.com/tour/) похоже то, что надо для фронтов по анимации
Скролить надо до этого момента
![8effd82c-36c3-4e5b-aa31-4f47ca28e7f2](https://user-images.githubusercontent.com/103942572/175017887-e65f3ff4-f95d-4922-b5df-b92c85f6a50d.png)

**Comment by dakand** [comment]
@bbbaso по результатам созвона решили как именно будем редактировать дизайн. На примере главной страницы:
1. Нужно отрефакторить блок о преподавателе. Добавить больше информации, ссылок. Сделать его масштабнее, поднять на блок выше.
2. Попробовать поменять акцентный цвет. Наверное, на фиолетовый. 
3. _Опционально._ Возможно добавить больше градиента, по возможности сделать сайт не таким тёмным.
4. _Опционально._ Убрать стилеобразующие элементы типа штрихов и чёрточек. Если без них будет ок выглядеть, то   оставим без них.

---

Надо сделать интерактивный прототип, но без скрола по стрелочкам. Базовый интерактинвый прототип с ховерами на нужные элементы.

---

Потом созваниваемся с Мариной и собираем с неё финальный фидбэк. В четверг по хорошему нужно с ней созвониться с этим.

**Comment by bbbaso** [comment]
@dakand 

Сделал новые варианты главной, [внутри](https://www.figma.com/file/8zVI2XcuXPz7ohCSEEnw94/Drum-Instructor?node-id=835%3A2537) есть комменты

_*чтобы не дублировать основной коммент, написал его там в формате, в котором будет понятно и Марине, т.к. она заходит туда иногда, (видел её сегодня там)_

Тебе наверн уже объяснять решения лишний раз не буду, т.к. мы и на созвоне обсудили все моменты на счёт её "опроса" и "анализа". Поэтому оставлю аргументы уже для созвона с ней, придётся что-то защищать по 2-му кругу, но это норм + я реально постарался услышать то, что она хотела визуально.

**Comment by bbbaso** [comment]
@dakand 

Созвон провели, прошло всё отлично, решения ей зашли, остальное отработал, защитил. Правок толком нет, осталось внутренние страницы просто стилизовать. 

_*Единственное нужно будет интегрировать модалку с видосом по нажатию на кнопку в блоке с преподом_

**Comment by dakand** [comment]
@bbbaso завтра займись стилизацией оставшихся страниц

**Comment by dakand** [comment]
@bbbaso комментов оставил. Давай допилим, там чисто организация. Я днём буду отсутствовать, поэтому как сделаешь драм - сообщи об этом Марине. Пусть посмотрит макеты. И спроси может ли она сегодня посмотреть и дать фидбэк, как бы намекая на то, чтобы она это сделала быстрее.

**Comment by dakand** [comment]
@bbbaso нужно отработать новые комменты Марины.

**Comment by dakand** [comment]
@bbbaso я честно забываю собрать все мысли в кучу, чтобы направить их Марине. Давай поступим таким образом: Внеси все её правки, которые на наш взгляд внести возможно (цвета и какие-то мелочи). После этого, напиши Марине что мы что-то сделали, а что-то сделать не можем и объясни почему, точечно объясни некоторые комменты.  Например, почему не станем менять шрифты. Увидим её ответ, решим, возможно, мы с Андреем подключимся.

---

P.S. делай это параллельно с академией, которой занимаешься сейчас.

**Comment by dakand** [comment]
@bbbaso я собрал весь фидбэк в кучу, с Мариной всё обсудили. В фигме финальные правки. Давай сегодня завершим.
