### ISSUE TITLE
Референсы для КР

### ISSUE THREAD

**Issue by dakand** [atls/design#29]
Собрать референсы для начала работы над дизайн концептом. Преимущественно собирать для мобильной версии. Смотреть стоит на издательства (не кино). Также было бы круто собрать  tone of voice (не сервисы, а что-то графическое).

**Comment by dakand** [comment]
@ArtemHovsky закинь сюда ссылку, если закончил.

**Comment by ArtemHovsky** [comment]
Ссылка на материалы: 
https://www.figma.com/file/pUWwcuHo61RiwLEzNztoGZ/Kinoreporter-%7C-Web-site?node-id=515%3A2839
