### ISSUE TITLE
Дизайн карты лояльности Apple Wallet для шиномонтажа

### ISSUE THREAD

**Issue by dakand** [atls/design#3]
Актуальный [вариант](https://www.figma.com/file/31slVdd8MlDAsNAaxgjPRF/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=48%3A305) карты 

@elizavetapugacheva твоя задача

Нужно спроектировать карту лояльности Apple Wallet для Шинного двора. [Тут](https://www.figma.com/file/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=43%3A0) проект в фигме - там и сайт и печатные материалы. Поэтому логотипы и стиль у тебя есть. Если не делала раньше подобного - прочитай как это делается, там есть определённые правила. но они простые.

**Структура там такая:**
1. background.png Фоновая картинка для карты.
2. footer.png Картинка рядом со штрихкодом.
3. icon.png Иконка для уведомлений и писем.
4. logo.png Логотип карточки. Отображается слева сверху.
5. thumbnail.png Дополнительная картинка.

**Comment by bbbaso** [comment]
@dakand на сайте есть акцентный синий, можем ли его юзать в карте?

**Comment by TorinAsakura** [comment]
> @dakand на сайте есть акцентный синий, можем ли его юзать в карте?

рекомендую посмотреть примеры карточек яблочных, к приложению wallet, ты должен понимать, что это будет на двуцветном фоне iOS

**Comment by bbbaso** [comment]
[тут](https://www.figma.com/file/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=1892%3A3376) в макете единственные сущности, которые у нас есть?

**Comment by TorinAsakura** [comment]
> [тут](https://www.figma.com/file/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=1892%3A3376) в макете единственные сущности, которые у нас есть?

что ты подразумеваешь под сущностями?

**Comment by bbbaso** [comment]
Номер карты, скидка, штрих-код, лого

**Comment by TorinAsakura** [comment]
> Номер карты, скидка, штрих-код, лого

а где ты увидел на макете эти сущности? лого, ок, оно есть везде, а вот остальное?

**Comment by bbbaso** [comment]
![image](https://user-images.githubusercontent.com/103942572/163981083-b3920f53-2b99-4aa6-8372-a7ef28599335.png)

**Comment by TorinAsakura** [comment]
Я вообще не знал о её существовании, но, раз уж такое дело то:
- штрих-код маленький, мы его не считаем ничем
- номер карты тут утилитарен, если есть штрих-код, его можно сделать элементом декора
- выглядит как какой-то кусок мобильной версии

Не очень презентабельная и правильная работа с точки зрения карты лояльности. Собирай референсы.

**Comment by bbbaso** [comment]
![image](https://user-images.githubusercontent.com/103942572/163987716-3d4adf43-7c56-46ef-870f-2b2710cf16a0.png)

Рефы отбирал по нескольким параметрам: а) легко считывается, б) без контрастных и композиционных ошибок

**И еще:** 
  Айдентика и сайт расходятся по акцентным цветам, ты так и не ответил какой юзать здесь?
  
    _*опираясь на [гайды](https://www.passteam.ru/blog/recommendations-for-passes-design), должна быть узнаваемость карточки среди прочих + белая карточка не будет выразительной на белом фоне (если только не ночной режим айфона, там бг черный)_

**Comment by bbbaso** [comment]
И есть ли уровни лояльности? ака Gold, Premium и тд

В таком случае можно будет визуально это тоже обозначить

**Comment by TorinAsakura** [comment]
> И есть ли уровни лояльности? ака Gold, Premium и тд
> 
> В таком случае можно будет визуально это тоже обозначить

Пока уровня планируется 2

**Comment by TorinAsakura** [comment]
> ![image](https://user-images.githubusercontent.com/103942572/163987716-3d4adf43-7c56-46ef-870f-2b2710cf16a0.png)
> 
> Рефы отбирал по нескольким параметрам: а) легко считывается, б) без контрастных и композиционных ошибок
> 
> **И еще:**   Айдентика и сайт расходятся по акцентным цветам, ты так и не ответил какой юзать здесь?        *опираясь на [гайды](https://www.passteam.ru/blog/recommendations-for-passes-design), должна быть узнаваемость карточки среди прочих + белая карточка не будет выразительной на белом фоне (если только не ночной режим айфона, там бг черный)

а где айдентика отличается по акцентным от сайта?

**Comment by bbbaso** [comment]
![image](https://user-images.githubusercontent.com/103942572/163990008-3f9f8290-de81-4341-9dcd-446266806bc7.png)

**Comment by TorinAsakura** [comment]
> ![image](https://user-images.githubusercontent.com/103942572/163990008-3f9f8290-de81-4341-9dcd-446266806bc7.png)

айдентика старая, текущего сайта, а это уже новый продукт получается

**Comment by bbbaso** [comment]
Тогда забыли про желтый, окей.

И можно фидбэк по референсам

**Comment by TorinAsakura** [comment]
> Тогда забыли про желтый, окей.
> 
> И можно фидбэк по референсам

мудборд сделай нормальный в фигме

**Comment by bbbaso** [comment]
[Мудборд](https://www.figma.com/file/31slVdd8MlDAsNAaxgjPRF/%D0%A8%D0%B8%D0%BD%D1%8B%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=0%3A1)

**Comment by TorinAsakura** [comment]
@bbbaso Зелёные оттенки слабо подходят, а вот аерофлот и Dienstausweis очень неплохо + мне по кайфу визуальная "безрамочность"

**Comment by bbbaso** [comment]
**Ок принято**

*рефы больше по структуре собирал, цвет уже вторичный признак был

**Comment by bbbaso** [comment]
**Первые варианты [тут](https://www.figma.com/file/31slVdd8MlDAsNAaxgjPRF/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=0%3A1) вместе с комментариями**

_*не нарыл пока гайдов по размерам, поэтому пока без автолейаута_

**Comment by bbbaso** [comment]
Достал гайды Apple, изменил гарнитуру на SF Pro Display, вариант обновил. 

**Все [тут ](https://www.figma.com/file/31slVdd8MlDAsNAaxgjPRF/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=0%3A1)же**

**Comment by dakand** [comment]
Последний вариант ок. @bbbaso что-то нужно еще для разработки судя по гайдам?

**Comment by dakand** [comment]
Перенеси проект в команду

**Comment by bbbaso** [comment]
Судя по гайдам, больше ничего. На темной версии все останется также.

Перенес еще в понедельник)

**Comment by TorinAsakura** [comment]
@dakand status?

**Comment by dakand** [comment]
@TorinAsakura done
[ссылка](https://www.figma.com/file/31slVdd8MlDAsNAaxgjPRF/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=48%3A305) на акутальный
