### ISSUE TITLE
Дизайн Кинорепортёр

### ISSUE THREAD

**Issue by dakand** [atls/design#30]
Ссылка на [Figma](https://www.figma.com/file/pUWwcuHo61RiwLEzNztoGZ/Kinoreporter-%7C-Web-site?node-id=616%3A2867).

### Основные поинты:
- [x] Концепт дизайна
- [x] Презентация основной части сайта мобильной версии
- [x] Дизайн мобильной версии
- [x] Дизайн десктопной версии
- [x] Формирование дизайн системы и базы компонентов
- [ ] Финальная презентация дизайн-проекта (опционально)

### По срокам:
**До 7 июля** закончить мобильную версию.
**До 15 июля** закончить десктопную версию.
**До 18 июля** для правок или создании финальной презентации.

**Comment by dakand** [comment]
@bbbaso поможешь мне с компонентами. Сейчас на [странице](https://www.figma.com/file/pUWwcuHo61RiwLEzNztoGZ/Kinoreporter-%7C-Web-site?node-id=650%3A4000) есть и фрагменты в перемешку. Твоя задача сделать как в [Youthink | Back Panel](https://www.figma.com/file/ofuBEflZhwVbl3eGV9EXvv/Youthink-%7C-Back-Panel?node-id=123%3A95), а именно: разбить на две страницы, внутри разбить на группы, создать все необходимые состояния.
P.S. По фрагментам пока не делай состояния другие, я этим сам займусь.
P.P.S. Я буду пополнять компоненты и отмечать тебя, когда что-то обновится.

**Comment by dakand** [comment]
@TorinAsakura @taqyon @sorokoumov чекпоинт по КР. Сделали основные макеты, дизайн систему, формируем библиотеку компонентов.
1. [Презентация](https://www.figma.com/proto/pUWwcuHo61RiwLEzNztoGZ/Kinoreporter-%7C-Web-site?page-id=846%3A15883&node-id=846%3A15884&viewport=1621%2C-3194%2C0.99&scaling=min-zoom) для команды КР. Здесь пояснил почему так, как будет работать, показал как пользоваться интерактивным прототипом.
2. [Скринкаст](https://disk.yandex.ru/i/6ZW0IkaPoFFw1g) с примером тестирования дизайн в интерактивном прототипе. Ссылку также есть в презентации.
3. [Интерактивный прототип](https://www.figma.com/proto/pUWwcuHo61RiwLEzNztoGZ/Kinoreporter-%7C-Web-site?page-id=836%3A8643&node-id=838%3A8581&viewport=206%2C243%2C0.16&scaling=min-zoom&starting-point-node-id=838%3A8581&show-proto-sidebar=1).
4. [Актуальные макеты](https://www.figma.com/file/pUWwcuHo61RiwLEzNztoGZ/Kinoreporter-%7C-Web-site?node-id=776%3A3972).

План не меняется, пока двигаемся по срокам.

**Comment by taqyon** [comment]
@dakand отметишь выполненные чекбоксы в теле issue?

**Comment by dakand** [comment]
@bbbaso завтра на связи буду с 13, поэтому заранее напишу с чем предстоит работать. Если ты довёл до какой-либо точки 3д, пока оставь и не нагружай голову реализацией новых вариантов - днём/вечером посмотрим. К слову то, что я увидел для подборки - мне очень зашло, правда чуть ярче надо.
В любом случае для тебя у меня есть ещё несколько задач.
1. Там новые компоненты и фрагменты появились. Нужно их интегрировать в нашу систему. Будь внимателен - все варианты компонентов, которые я добавил нужны, возможно, что для некоторых нужно добавить новый тег (например, у нас есть новый фрагменты кинопремьеры и внутри есть два варианта "Кино" и "Сериал", это property "type", соответсвенно нужно добавить новый property "state").
2. Посмотри все макеты, которые есть сейчас в мобилке и если будут идеи, то напиши, что бы ты изменил или доработал.
3. Разработай десктоп главной страницы на основе мобилки. Эта задача более серьезная, за завтра ты её конечно не выполнишь скорее всего. Но хочу сказать, что не нужно сильно заморачиваться. Мы примерно понимаем как сайт редакции будет выглядеть в десктопе. Сделаешь скетч, доработаем, будем пилить дальше.

**Comment by bbbaso** [comment]
@dakand 

1. Сделал фрагменты и компоненты (есть пару комментов внутри)
2. По макетам оставил комментарии
3. Дескстоп сегодня начать не успел, в Сб или Вскр посижу, накидаю первые варианты

**Comment by dakand** [comment]
@taqyon был фидбэк по последнему этапу от них? А то время уже норм прошло

**Comment by taqyon** [comment]
> @taqyon был фидбэк по последнему этапу от них? А то времени уже норм прошло

Не совсем понял о чем ты. Если о прототипе, то я ничего не показывал еще. Если о чём-то еще, тогда я не понимаю.

**Comment by dakand** [comment]
> @TorinAsakura @taqyon @sorokoumov чекпоинт по КР. Сделали основные макеты, дизайн систему, формируем библиотеку компонентов.
> 
> 1. [Презентация](https://www.figma.com/proto/pUWwcuHo61RiwLEzNztoGZ/Kinoreporter-%7C-Web-site?page-id=846%3A15883&node-id=846%3A15884&viewport=1621%2C-3194%2C0.99&scaling=min-zoom) для команды КР. Здесь пояснил почему так, как будет работать, показал как пользоваться интерактивным прототипом.
> 2. [Скринкаст](https://disk.yandex.ru/i/6ZW0IkaPoFFw1g) с примером тестирования дизайн в интерактивном прототипе. Ссылку также есть в презентации.
> 3. [Интерактивный прототип](https://www.figma.com/proto/pUWwcuHo61RiwLEzNztoGZ/Kinoreporter-%7C-Web-site?page-id=836%3A8643&node-id=838%3A8581&viewport=206%2C243%2C0.16&scaling=min-zoom&starting-point-node-id=838%3A8581&show-proto-sidebar=1).
> 4. [Актуальные макеты](https://www.figma.com/file/pUWwcuHo61RiwLEzNztoGZ/Kinoreporter-%7C-Web-site?node-id=776%3A3972).
> 
> План не меняется, пока двигаемся по срокам.

@taqyon вот 18 дней назад сделали дизайн концепт с прототипами и анимацией. Нужно было, чтобы они дали какой-то фидбэк. Дополнительная работа была не маленькая. Мы заканчиваем мобилку, если они сейчас глобально захотят что-то менять, то для нас это дольше будет. Но так или иначе, думаю, мы свои решения защитить сможем.

**Comment by taqyon** [comment]
> > @TorinAsakura @taqyon @sorokoumov чекпоинт по КР. Сделали основные макеты, дизайн систему, формируем библиотеку компонентов.
> > 
> > 1. [Презентация](https://www.figma.com/proto/pUWwcuHo61RiwLEzNztoGZ/Kinoreporter-%7C-Web-site?page-id=846%3A15883&node-id=846%3A15884&viewport=1621%2C-3194%2C0.99&scaling=min-zoom) для команды КР. Здесь пояснил почему так, как будет работать, показал как пользоваться интерактивным прототипом.
> > 2. [Скринкаст](https://disk.yandex.ru/i/6ZW0IkaPoFFw1g) с примером тестирования дизайн в интерактивном прототипе. Ссылку также есть в презентации.
> > 3. [Интерактивный прототип](https://www.figma.com/proto/pUWwcuHo61RiwLEzNztoGZ/Kinoreporter-%7C-Web-site?page-id=836%3A8643&node-id=838%3A8581&viewport=206%2C243%2C0.16&scaling=min-zoom&starting-point-node-id=838%3A8581&show-proto-sidebar=1).
> > 4. [Актуальные макеты](https://www.figma.com/file/pUWwcuHo61RiwLEzNztoGZ/Kinoreporter-%7C-Web-site?node-id=776%3A3972).
> > 
> > План не меняется, пока двигаемся по срокам.
> 
> @taqyon вот 18 дней назад сделали дизайн концепт с прототипами и анимацией. Нужно было, чтобы они дали какой-то фидбэк. Дополнительная работа была не маленькая. Мы заканчиваем мобилку, если они сейчас глобально захотят что-то менять, то для нас это дольше будет. Но так или иначе, думаю, мы свои решения защитить сможем.

>Нужно было, чтобы они дали какой-то фидбэк.

Окей. Просто о *нужности* фидбека я узнаю прямо сейчас. Чтобы фидбек был плодотворней, я могу сделать созвон на троих: Ты, Говорухин, Я. Что думаешь?

**Comment by dakand** [comment]
@taqyon Вань, если мы будем уточнять такие вещи как отчёт о работе для заказчика, то будет сложно. Мы не просто так всё это презентовали, а отдавать чекпоинт спустя почти 3 недели, когда подходит следующий уже не актуально. Надеюсь это не сильная проблема на данный момент, но в дальнейшем нужно понимать, что отдаём что-либо на проверку СРАЗУ, если есть подтверждение от меня или Андрея. 
Касательно созвона с Говорухиным. Я пока не вижу смысла мне с ним общаться, комменты в фигме он умеет оставлять. Пока прикорми его тем, что есть. В середине недели покажем ему всю мобилку, там уже можно и поговорить.

**Comment by dakand** [comment]
@bbbaso если есть наработки по десктопу добавляй в проект на новую страницу. Я тебе оставил комменты в фигме, план такой:
1. Нужно обновить везде информацию, где плейсхолдеры (и текст и картинки). Комментами пометил.
2. Доверяю тебе дизайн О нас, Авторизация, ЛК. В комментах также написал минимум который должен быть, мб увидишь дополнительные флоу.
3. Нам на страницу журнала нужен 3д бг на фон. Коммент оставил.
4. Доделываем 3д над которыми ты работал. Время уже много прошло, поэтому выкатываем что есть, доделываем без заморочек чего нет. Порой лучшие мысли приходят сразу. 

---

п.1 и п.2 делаем за завтра. п.3 желательно тоже или потом придётся задерживаться. п.4 и правки по п.2 на первую половину вторника. Во второй половине вторника надо начать работать над десктопом.

**Comment by dakand** [comment]
@bbbaso когда формируешь компоненты путаешь стейты **Press** и **Active**. Бывает так, что эти стейты взаимозаменяемые, бывает так что стейт Active выносится отдельным property. Примеры:
1. Стандартная кнопка. Тут стейт Press. Нажали и функция сработала в этот же момент.
2. Фрагмент подкастов. Тут стейт Active, т.к. у нас включается подкаст, а стейт Press подразумевает возвращение к Default.
3. Бургер меню. Тут стейт Active отдельным property. У нас будет [Default - (Default, Hover)] и [Active - (Default, Hover)].

Сейчас ничего не исправляй, это на будущее.

**Comment by bbbaso** [comment]
@dakand Понял, учту

**Comment by taqyon** [comment]
> @TorinAsakura @taqyon @sorokoumov чекпоинт по КР. Сделали основные макеты, дизайн систему, формируем библиотеку компонентов.
> 
>     1. [Презентация](https://www.figma.com/proto/pUWwcuHo61RiwLEzNztoGZ/Kinoreporter-%7C-Web-site?page-id=846%3A15883&node-id=846%3A15884&viewport=1621%2C-3194%2C0.99&scaling=min-zoom) для команды КР. Здесь пояснил почему так, как будет работать, показал как пользоваться интерактивным прототипом.
> 
>     2. [Скринкаст](https://disk.yandex.ru/i/6ZW0IkaPoFFw1g) с примером тестирования дизайн в интерактивном прототипе. Ссылку также есть в презентации.
> 
>     3. [Интерактивный прототип](https://www.figma.com/proto/pUWwcuHo61RiwLEzNztoGZ/Kinoreporter-%7C-Web-site?page-id=836%3A8643&node-id=838%3A8581&viewport=206%2C243%2C0.16&scaling=min-zoom&starting-point-node-id=838%3A8581&show-proto-sidebar=1).
> 
>     4. [Актуальные макеты](https://www.figma.com/file/pUWwcuHo61RiwLEzNztoGZ/Kinoreporter-%7C-Web-site?node-id=776%3A3972).
> 
> 
> План не меняется, пока двигаемся по срокам.

Передал эту информацию Говорухину. Ему понадобится время на ознакомление, это может быть день, а может два-три. Он сообщит мне в лс сколько точно потребуется. 

По редактору немного поболтали, я хочу продолжить рисёрч. Хочу поискать готовые решения, может найду что-то бесплатное :)

**Comment by bbbaso** [comment]
@dakand а как мы показываем авторизацию через соц. сети? Там просто дефолтные формы у каждой

**Comment by dakand** [comment]
> @dakand а как мы показываем авторизацию через соц. сети? Там просто дефолтные формы у каждой

Ты всё правильно сделал. В рамках дизайна показываем только подтверждение перехода.

**Comment by dakand** [comment]
@bbbaso новая вводная. У нас для покупки журнала пользователь должен пройти определённый путь до оплаты. Так что ещё одна задача на тебе. Вся инфа на их текущем сайте есть, только там не очень она оптимизирована. По приоритет после первых двух пунктов [этого](https://github.com/atls/design/issues/30#issuecomment-1173180141) комментария.

**Comment by bbbaso** [comment]
@dakand по поводу оплаты журнала:

1. Нет инфы о стоимости доставки, проверял в чекауте, вроде к цене ничего не добавилось, значит оставляем бесплатной?
2. Если есть акк и есть доставка. то наверн в профиль нужно добавлять адрес/адреса (там еще пункт Юр. лицо, то есть тоже данные, которые нужно сохранять (иначе каждый раз заполнять придется)
3. Стоит ли отдельно делать корзину или сразу можно открывать чекаут?

_*постараюсь допилить сегодня чекаут, остальные пункты из коммента отложу уже на завтра_

**Comment by dakand** [comment]
1. Я думаю доставка может быть платной. Предусмотри два варианта.
2. Согласен
3. Сразу открываем чекаут

> @dakand по поводу оплаты журнала:
> 
> 1. Нет инфы о стоимости доставки, проверял в чекауте, вроде к цене ничего не добавилось, значит оставляем бесплатной?
> 2. Если есть акк и есть доставка. то наверн в профиль нужно добавлять адрес/адреса (там еще пункт Юр. лицо, то есть тоже данные, которые нужно сохранять (иначе каждый раз заполнять придется)
> 3. Стоит ли отдельно делать корзину или сразу можно открывать чекаут?
> 
> _*постараюсь допилить сегодня чекаут, остальные пункты из коммента отложу уже на завтра_

**Comment by bbbaso** [comment]
@dakand

Checkout собрал

**Тезисно, что осталось:**
1. Success стейты пунктов в чекауте (страницу оплаты пока не трогаю)
2. Исправить модалки закладок в страницы
3. Добавить в профиль: **Телефон, Адрес, Данные организации**
4. Допилить некоторые компоненты
5. 3D

**Comment by bbbaso** [comment]
@dakand правки отработал (из хаба и комменты в фигме)
 
1. Чекаут тож обновил, показал состояния при поиске адреса (если ты не видел еще)
2. Заапргрейдил немного инпуты (добавил тайтлы внутрь, чтобы сэкономить место + визуально чище стало)
3. Профиль тож видоизменил (кнопку "редактировать профиль" сделал более нативной + выделил целую страницу для редактирования, так будет меньше вложенности и сами данные лучше считываются)

**Comment by bbbaso** [comment]
@dakand траблы с 3д

Не получается развить мысль для других карточек, ориентируясь на "подборки" + в целом рефы для подобных штук тяжело найти, т.к. не понятно толком по какому тайтлу их искать (тоже самое касается туториалов, т.к. сам я еще не умею реализовывать любой визул в 3д)

По поводу фона для блока с журналом хотелось бы немного идей/примеров услышать, т.к. мне ничего на ум не пришло

_*пишу сразу, чтобы не затягивать это_

**Comment by bbbaso** [comment]
@dakand получилось что-то [такое](https://www.figma.com/file/pUWwcuHo61RiwLEzNztoGZ/Kinoreporter-%7C-Web-site?node-id=1234%3A37553)

**Comment by dakand** [comment]
@bbbaso 

- [ ] Выгрузить 3D в пнг в хайрезе
- [ ] Добавить новые компоненты из страницы Mobile
- [ ] Структурировать фрагменты (добавить в общий фрейм и разделить на группы)
- [ ] Добавить фрагменты и компоненты десктопа. Будет фрейм похожий на фрейм для мобилки, но некоторых комопонентов может не быть или быть больше, чем в мобильной (например, првеью статей).

Оформляй компоненты красиво сразу. Падинги по 40, скругления по 20. Фон можно добавить. Как в ЮТ.

**Comment by bbbaso** [comment]
Модель в альфа-канале [Модель (КР).zip](https://github.com/atls/design/files/9055860/default.zip)

**Comment by dakand** [comment]
@bbbaso Доделал основные 3 макета. Справа от него компоненты и фрагменты, нужно их разобрать. Также есть в макетах стилизованные компоненты мобилки или элементы без компонентов, которые нужно сделать для десктопа. Чтобы ты не искал по макету, я сейчас тебе на каждый элемент коммент поставлю.

**Comment by dakand** [comment]
@bbbaso по окончанию всех тех задач, что были описаны ранее, приступай к десктопу. На странице desktop есть 3 макета - там применены все стили для десктопа, есть новы компоненты, сетка... в общем принцип должен быть понятен. Будем последовательно всё выполнять. Где-то нужно показать больше стейтов относительно мобилки, где-то больше. И чтобы в случае правок не применять изменения ко всей группе макетов (с разными стейтами), мы сначала адаптируем макеты в дефолтном виде. Какие макеты проектируем:

- [ ] Media / Other
- [ ] Articles page (Сollection)
- [ ] Articles page (Review)
- [ ] Film page (Default)
- [ ] Person
- [ ] Film premieres
- [ ] Podacast
- [ ] Magazine
- [ ] About
- [ ] Sign in / Sign up (без флоу)

P.S. я не сделал футер. ПОэтому стоит сначала его адаптировать и добавлять везде на макеты.

P.P.S. Не делать секшены компонентами!!! Исключение: хедер, футер, подписка, журнал.

**Comment by bbbaso** [comment]
@dakand а под Shop ты какую страницу имел ввиду?

**Comment by dakand** [comment]
> @dakand а под Shop ты какую страницу имел ввиду?

Лол я лингвист. Magazine конечно

**Comment by TorinAsakura** [comment]
Актуализируйте чекбоксы, пожалуйста

**Comment by bbbaso** [comment]
@dakand а в каком виде делаем Sign in/Sign up, модалкой или страницей?

**Comment by bbbaso** [comment]
@dakand страницы сделал

_*какие-то элементы у меня уже в компонентах/вариантах, какие-то пока нет, уже как оставишь комменты, тогда наверн правильней будет их довести до ума_

**Comment by dakand** [comment]
@bbbaso работаем дальше:

- [ ] ЛК. Адптировать все уникальные экраны (стейты не нужно). Т.е., например, экраны "Пароль", "Восстановление пароля" и т.п. делаем, стейты валидации пока не делаем.
- [ ] Покупка журнала. Весь флоу адаптируем.
- [ ] Заполнить всё, где сейчас стоят плейсхолдеры.

**Comment by dakand** [comment]
@bbbaso сегодня сможешь закрыть все чекбоксы [тут](https://github.com/atls/design/issues/30#issuecomment-1184049937)?

**Comment by bbbaso** [comment]
@dakand Да, должен вроде

**Comment by bbbaso** [comment]
@dakand правки внёс 

_*оставил неск вариантов страницы актёра под макетами_

**Comment by dakand** [comment]
@bbbaso оставил комментарии, нужно отработать.

**Comment by dakand** [comment]
@bbbaso если работаешь ещё, то нужно дальше оптимизировать компоненты.

**Comment by dakand** [comment]
> @dakand Посмотри пожалуйста предварительный вариант "Поиска"

Оставил комменты

**Comment by bbbaso** [comment]
@dakand адаптировал экраны:

- Sign in
- Sign up
- Password recovery
- Profile (confirm email/password editing)

**Comment by dakand** [comment]
@bbbaso как сядешь за работу, начни с проверки всех плейсхолдеров. Доделываем это и отдаем на ревью. Ещё там компоненты убрать надо, немного новых добавил (комменты поставил).

**Comment by bbbaso** [comment]
@dakand один момент

Разве не нужно отображать сам запрос поиска на странице результатов? Типа "а что мы вообще искали?"
И мб кол-во результатов тоже

**Comment by dakand** [comment]
@taqyon КР можно отдавать на ревью

**Comment by bbbaso** [comment]
@dakand оптимизацию компонентов довёл до условного финиша

_*только есть небольшие затыки с неймингом кнопок Link и Tertiary, т.к. местами они пересекаются, и по некоторым компонентам (искал через плагин по файлу, но безуспешно)_
