### ISSUE TITLE
Учебный материал по Spline

### ISSUE THREAD

**Issue by dakand** [atls/design#34]
Проект [здесь](https://www.figma.com/file/Q8d1p1P4q5doxfWyzIY5Ht/Spline-%E2%80%94-Tutorial?node-id=0%3A1). 
Нам необходимо подробно изучить возможности Spline и варианты его интеграции. Spline я вижу сейчас как самый доступный инструмент для внедрения 3d в наши проекты.

---
Нужно сделать презентацию в фигме в которой необходимо показать:

**1. Моделирование**

Возможности Spline с точки зрения проектирования. Проще говоря показать самые лучшие или сложные на твой взгляд примеры сделанные в программе.

**2. Экспорт**
- Какие форматы бывают и какие чаще всего юзают?
- Можно ли экспортить видео? С альфа-каналом?
- Пример экспорта и интегрирования модели в работающий сайт.
- Возможно ли real-time изменения?

**3. Интегрирование**
Как происходит настройка параметров сцены или модели. Условно у нас есть сцены:
1. Статичная
2. Анимированная по сценарию
3. Анимируется при взаимодействии пользователя с сайтом (скрол, наведение курсора мыши)

**4. Тарифы**
Основные отличия тарифов и субъективное мнение по поводу того стоит ли брать платный тариф на дизайнера или на команду.

---
Твоя текущая подборка верно начата, но она поверхностна. Нам нужно углубиться и четко ответить на те пункты, которые я описал выше. Абсолютно точно вся информация должна быть на русском и желательно прикреплять изображения некоторых примеров помимо ссылок. Этот материал мы потом используем для написания статьи.

**Comment by ArtemHovsky** [comment]
@dakand 
Добавил информацию по интеграции, все что смог найти
Посмотри, может еще что-то нужно добавить
