### ISSUE TITLE
Работа с 3D

### ISSUE THREAD

**Issue by dakand** [atls/design#36]
Продолжаем осваивать Spline.
### Референсы
Первое, что необходимо сделать - собрать мудборд. Нам нужно определить текущие тренды, интересные анимации, показать примеры как простые модели могут быть красивыми.
### Практика
Нужно в spline спроектировать несколько моделей для наших проектов:

- [ ] **Модель для блока подписки на рассылку в КР.** Тут предварительно нужно или найти аналогичный референс или нарисовать скетч, прежде, чем приступать к моделированию.
- [ ] **Модель для Hero в Atlantis.** Тут мы уже знаем, что должно получиться.

**Comment by ArtemHovsky** [comment]
@dakand 
Собрал материал для "КР"
Нужно созвониться обсудить стиль моделей

**Comment by dakand** [comment]
@ArtemHovsky прикрепи ссылку. Не совсем понял почему для КР, ведь в задаче написал, что первое, что нам нужно сделать - собрать мудборд по текущим трендам, которые помогут нам определить общий стиль нашего 3D, а только потом уже искать рефы под КР или рисовать скетчи.

**Comment by ArtemHovsky** [comment]
А какой в этом смысл? Зачем сваливать все в одну кучу, которая ни как не будет полезна.
Для каждой задачи свой стиль и требования. И уже исходя из задачи нужно подбирать референсы.

**Comment by dakand** [comment]
@bbbaso попрактиковаться со Spline. Сделать скетч или найти референс для модели в КР и спроектировать модель для КР в Spline.
