### ISSUE TITLE
Atlantis Design

### ISSUE THREAD

**Issue by dakand** [atls/design#37]
### [Figma](https://www.figma.com/file/EaC9Vjk832R9VSv0dTDFzT/Project-Pages?node-id=2%3A2)

Начинаем со страницы проекта. Сначала оформляем наши проекты в презентацию, чтобы можно было ею подкреплять КП. Потом уже будем работать над сайтом.

@sorokoumov с тебя текстовый прототип презентации. Нужно собрать все проекты, которые мы можем/хотим показать, воедино, тезисно описать процесс проектирования, нестандартные решения применённые в процессе (если они были) и основные метрики (если они интересные).

@ArtemHovsky тебе нужно собрать референсы страниц проектов, такое лучше всего искать на awwwards.com (у них есть отдельная категория). Только референсы собирай отдельно с точки зрения структуры (можешь отдельные понравившиеся куски для блоков вытаскивать) и отдельно с точки зрения UI (тут наоборот, чем больше страница, тем больше примеров применения стиля). Выше с отметкой на Лёху я написал из чего примерно будет состоять преза, чтобы ты понимал какие рефы искать.
Также нам нужно оформить обложки проектов. Сначала собери референсы, @sorokoumov составит список проектов, которые нужно будет добавить в презентацию и для них будем собирать обложки.

P.S. @ArtemHovsky создай новый проект в **Atlantis Design** для всего выше описанного.

**Comment by dakand** [comment]
Возвращаемся сюда. @ArtemHovsky нам нужны топовые обложки для наших проектов:
- YouThink (сервис целиком, в т.ч. мобильное приложение)
- BMW F40 (промо-страница для продажи)
- MINI F60 (промо-страница для продажи)
- BMW Group AS Shop (интернет-магазин с возможностью адаптации под другие бренды группы)
- Beatster (сервис целиком)
- Байкал Сервис (ЛК)
- PUMP (мобильное приложение)
- Восточный банк (мобильное приложение)

----

Информацию, материалы можешь брать [здесь](https://www.figma.com/file/xmaK13lOwzWpz7oy7vnfM1/Projects-Presentation?node-id=0%3A1) и [здесь](https://github.com/atls/design/issues/50), а также все проекты есть в нашей фигме.

----

P.S. Если считаешь, что по шрифтам узнал всю инфу, которую мог - переходи к этой задаче. Задачу делай в новом проекте в Atlantis Design в фигме.

**Comment by TorinAsakura** [comment]
> Возвращаемся сюда. @ArtemHovsky нам нужны топовые обложки для наших проектов:
> 
> * YouThink (сервис целиком, в т.ч. мобильное приложение)
> * BMW F40 (промо-страница для продажи)
> * MINI F60 (промо-страница для продажи)
> * BMW Group AS Shop (интернет-магазин с возможностью адаптации под другие бренды группы)
> * Beatster (сервис целиком)
> * Байкал Сервис (ЛК)
> * PUMP (мобильное приложение)
> * Восточный банк (мобильное приложение)
> 
> Информацию, материалы можешь брать [здесь](https://www.figma.com/file/xmaK13lOwzWpz7oy7vnfM1/Projects-Presentation?node-id=0%3A1) и [здесь](https://github.com/atls/design/issues/50), а также все проекты есть в нашей фигме.
> 
> P.S. Если считаешь, что по шрифтам узнал всю инфу, которую мог - переходи к этой задаче. Задачу делай в новом проекте в Atlantis Design в фигме.

Поправочка - битстер пока не нужен. Он ведь мёртв и так и не был толком запущен в массы.

**Comment by ArtemHovsky** [comment]
> Возвращаемся сюда. @ArtemHovsky нам нужны топовые обложки для наших проектов:
> 
> * YouThink (сервис целиком, в т.ч. мобильное приложение)
> * BMW F40 (промо-страница для продажи)
> * MINI F60 (промо-страница для продажи)
> * BMW Group AS Shop (интернет-магазин с возможностью адаптации под другие бренды группы)
> * Beatster (сервис целиком)
> * Байкал Сервис (ЛК)
> * PUMP (мобильное приложение)
> * Восточный банк (мобильное приложение)
> 
> Информацию, материалы можешь брать [здесь](https://www.figma.com/file/xmaK13lOwzWpz7oy7vnfM1/Projects-Presentation?node-id=0%3A1) и [здесь](https://github.com/atls/design/issues/50), а также все проекты есть в нашей фигме.
> 
> P.S. Если считаешь, что по шрифтам узнал всю инфу, которую мог - переходи к этой задаче. Задачу делай в новом проекте в Atlantis Design в фигме.

Не нашел файл фигмы "Восточный банк"

**Comment by ArtemHovsky** [comment]
https://www.figma.com/file/0UpfeaaX2PKRq9xKHl3ULt/Project-Covers?node-id=2%3A12

**Comment by dakand** [comment]
> https://www.figma.com/file/0UpfeaaX2PKRq9xKHl3ULt/Project-Covers?node-id=2%3A12

Комменты оставил. YT оч зашёл. В целом точно могу сказать, что стоит отказаться от мокапов в их привычном виде (как на мини). Мы можем юзать какие-то мокапы, но с минимальным количеством деталей (как на том же YT).

**Comment by dakand** [comment]
@ArtemHovsky [ссылка](https://www.figma.com/file/KVUCKfIgcdz3F9EI0G0dbp/%D0%92%D0%BE%D1%81%D1%82%D0%BE%D1%87%D0%BD%D1%8B%D0%B9-%D0%B1%D0%B0%D0%BD%D0%BA?node-id=0%3A8018) на Восточный банк. Там в Page 3 всё актуальное вроде.

**Comment by ArtemHovsky** [comment]
@dakand 
Посмотри пожалуйста варианты

**Comment by dakand** [comment]
> @dakand Посмотри пожалуйста варианты

оставил комменты

**Comment by ArtemHovsky** [comment]
> > @dakand Посмотри пожалуйста варианты
> 
> оставил комменты

@dakand 
Внес правки по комментариям, посмотри пожалуйста варианты

**Comment by dakand** [comment]
> > > @dakand Посмотри пожалуйста варианты
> > 
> > 
> > оставил комменты
> 
> @dakand Внес правки по комментариям, посмотри пожалуйста варианты

Классно получилось! Красавчик

**Comment by dakand** [comment]
@bbbaso ищем референсы для страницы проектов. Референсы нам нужны для того чтобы на примере убедиться как лучше презентовать проект - сколько отдавать места для текста и объяснения концепции работы, сколько для всей графики. Также референсы помогут применить что-то не совсем стандартное в презентации. После этого начнём проектировать страницу проекта. Лучше это делать на примере и лучше всего на YouThink. По YouThink созвонимся отдельно как дойдёшь до этого.

**Comment by bbbaso** [comment]
@dakand собрал рефов, старался не собирать типовые (комменты внутри оставил)

1. Нужно понять сколько у нас есть инфы о проектах, сколько мы вообще хотим рассказывать (просто овервью или подробно о анализе, протоипах и тд) 
2. На сколько шаблонно будем оформлять все проекты? (сетка, сами блоки внутри, порядок и тд)

**Comment by dakand** [comment]
> @dakand собрал рефов, старался не собирать типовые (комменты внутри оставил)
> 
> 1. Нужно понять сколько у нас есть инфы о проектах, сколько мы вообще хотим рассказывать (просто овервью или подробно о анализе, протоипах и тд)
> 2. На сколько шаблонно будем оформлять все проекты? (сетка, сами блоки внутри, порядок и тд)

@bbbaso коммент оставил на рефы, которые нам подходят. Они для сайта подходят лучшего всего. Нам не нужно смотреть на проект с точки зрения конкретной инофрмации по проекту. Где-то её меньше, где-то больше, где-то её может вообще не быть. Поэтому нам нужно сделать шаблонные блоки как текстовые, так и для изобрадения. Из них будем лепить проект.

**Comment by bbbaso** [comment]
@dakand спроектировал [страницу](https://www.figma.com/file/AktCgqn7lywnIYjcu4C1HY/Website?node-id=38%3A196), посмотри как сможешь

_*примеры анимации с ссылками внутри_

**Comment by bbbaso** [comment]
@dakand добавил еще интерактивный макет, примерно показал как я вижу анимацию

**Comment by TorinAsakura** [comment]
@dakand ты вот сделал Atlantis Design 2.0, а что в таком случае с 1.0? 2.0 обычно пишут, когда в релизе уже что-то есть, некая 1.0, а у нас пока ничего нет. Или закрой, или вмержи их.

**Comment by TorinAsakura** [comment]
переход в https://github.com/atls/design/issues/79
