### ISSUE TITLE
Обновить презу

### ISSUE THREAD

**Issue by sorokoumov** [atls/design#38]
Сделать ревью презентации,
[Презентация_о_концепции,_структуре_и_визуализации_нового_сайта.pdf](https://github.com/atls/design/files/8939213/_._._._._._._.pdf)

Обновить предыдущую презентацию https://github.com/RFRIT/design/issues/3

**Comment by sorokoumov** [comment]
@TorinAsakura @dakand замечания и предложения можете оставлять на актуальной странице https://www.figma.com/file/MdcDYVf7MVHQX2bbL8piNa/%D0%A0%D0%A4%D0%A0%D0%98%D0%A2-%7C-%D0%9F%D1%80%D0%B5%D0%B7%D0%B5%D0%BD%D1%82%D0%B0%D1%86%D0%B8%D1%8F?node-id=139%3A201

**Comment by sorokoumov** [comment]
@sorokoumov @dakand от тебя нужен будет фастчек

**Comment by sorokoumov** [comment]
Обновленная для @TorinAsakura https://www.figma.com/proto/MdcDYVf7MVHQX2bbL8piNa/%D0%A0%D0%A4%D0%A0%D0%98%D0%A2-%7C-%D0%9F%D1%80%D0%B5%D0%B7%D0%B5%D0%BD%D1%82%D0%B0%D1%86%D0%B8%D1%8F?page-id=139%3A201&node-id=139%3A202&viewport=564%2C4712%2C0.49&scaling=min-zoom

**Comment by TorinAsakura** [comment]
Оставил пачку комментариев. Работа сделана хорошо, однако повествовательно-текстовая часть сильно хромает. Редактура необходима будет какое-то время.

Рекомендую смотреть в историю изменений, там не много, но чот да есть.

Остальное оставил в комментах.


P.S: Почему в задаче нет лейблов, не указаны исполнители?
P.S.S: Если в задаче говорится об продолжении работ над чем-то, что уже делалось - надобно делать рефлинк, если рефлинка нет - описывать, чо мы тут обновляем и что не так с оригиналом который мы обновляем, иначе не понятна суть задачи
P.S.S.S:  Хороший повод дать тебе пизды. ТЧК.

**Comment by sorokoumov** [comment]
Updated

**Comment by TorinAsakura** [comment]
https://www.figma.com/file/MdcDYVf7MVHQX2bbL8piNa?node-id=139:202#213648164
https://www.figma.com/file/MdcDYVf7MVHQX2bbL8piNa?node-id=139:202#213648290
?

**Comment by sorokoumov** [comment]
https://www.figma.com/proto/MdcDYVf7MVHQX2bbL8piNa/%D0%A0%D0%A4%D0%A0%D0%98%D0%A2-%7C-%D0%9F%D1%80%D0%B5%D0%B7%D0%B5%D0%BD%D1%82%D0%B0%D1%86%D0%B8%D1%8F?page-id=192%3A363&node-id=195%3A364&viewport=582%2C959%2C0.26&scaling=min-zoom
