### ISSUE TITLE
Переработка дизайна страницы сервиса

### ISSUE THREAD

**Issue by sorokoumov** [atls/design#39]
Есть старый дизайн.
https://www.figma.com/file/Bq09XHhlhNGnu9NT2Hsw7e/Untitled?node-id=0%3A1

тексты, блоки и т.п. менять не нужно.
Нужно пересобрать в норм дизайн.

Соответственно:
1. Подбор рефов
2. Концепт 2-3 блоков
3. Дизайн полный
4. Дизайн мобилки.

Ожидаю, что будет полный пакет, подготовленный к верстке.

**Comment by ArtemHovsky** [comment]
https://www.figma.com/file/Bq09XHhlhNGnu9NT2Hsw7e/Old?node-id=88%3A1897

Сделал концепт первых 3 блока. Посмотрите пожалуйста

**Comment by ArtemHovsky** [comment]
@sorokoumov 
Доделал полностью страницу, посмотри пожалуйста

**Comment by sorokoumov** [comment]
@ArtemHovsky все ок.
Нужен favicon и sharing-картинка какая-нить

**Comment by ArtemHovsky** [comment]
Сделал, лежит в UI kit

**Comment by ArtemHovsky** [comment]
@sorokoumov 
Сделал адаптив карточки товара. Добавил форму связи и сообщения (успех, ошибка)

**Comment by ArtemHovsky** [comment]
@sorokoumov 
Добавил два дополнительных блока: Фото галерея, Отель
Посмотри пожалуйста

**Comment by dakand** [comment]
@sorokoumov какой у вас этап? Когда закончите и Артём будет свободен?

**Comment by dakand** [comment]
> @sorokoumov какой у вас этап? Когда закончите и Артём будет свободен?

@sorokoumov ?

**Comment by sorokoumov** [comment]
@dakand Ты можешь забирать его.
Мне он нужен будет ток если мелочи какие то будут всплывать в процессе вёрстки и  завтра-послезавтра ещё одну страницу (несколько блоков) нарисовать.

**Comment by dakand** [comment]
@sorokoumov Закрываем?
