### ISSUE TITLE
Отрисовка страниц магазина

### ISSUE THREAD

**Issue by sorokoumov** [atls/design#40]
Магазин — это:

- Каталог
- Карточка товара
- Псевдо-корзина, из которой нельзя будет купить товар
// фактически, нужно иметь возможность собирать товары в корзину, но пользователь не сможет купить товары из корзины, а сможет скинуть нам заказ на оценку на почту / позвонить на телефон..
- Sucess экран.
Обязательно:
**Текст:**
Менеджер свяжется с вами в ближайшее время, но если торопитесь — можете связаться с нами самостоятельно.
**Иконочки**
whatsapp, telegram и номер телефона.

**Необязательно (v2):**
- Хочу, чтобы ты добавил предложение узнать о нашем отеле (тут можно и с фото)

+ нужно favicon и sharing-картинку.
Знаешь размеры?

**Comment by sorokoumov** [comment]
@ArtemHovsky [Product page prot](https://www.figma.com/file/Bq09XHhlhNGnu9NT2Hsw7e/Work?node-id=81%3A968) обновил карточку.
Вынес неверх преиммущества, раскрыл калькулятор.

Он нужен в открытом виде.
Важную инфу оставил в нужном порядке.
Убрал неважную.

Хочу, чтобы ты оформил.

**Comment by sorokoumov** [comment]
![IMAGE 2022-06-30 15:48:45](https://user-images.githubusercontent.com/16300249/176680771-9b0f2d09-eb20-4a67-a2a9-fd522d605b79.jpg)
@ArtemHovsky попробуй карточку товара в эту сторону увести, пжлста

**Comment by sorokoumov** [comment]
@ArtemHovsky апдейтнул описание.
Добавил sucess-экран и обязательную информацию на нем. Также попробуй на sucess-экране добавить промо страницы отеля.

**Comment by ArtemHovsky** [comment]
@sorokoumov 
Посмотри: адаптив каталога, корзины, переделал вариант карточки товара

**Comment by dakand** [comment]
@sorokoumov закрываем?
