### ISSUE TITLE
Анализ Сети цветочных магазинов Флоренция

### ISSUE THREAD

**Issue by TorinAsakura** [atls/design#45]
# Запрос
Поступил запрос на цифровую трансформацию сети цветочных магазинов Флоренция в городе Электросталь.

## Что это всё значит?
От нас нужны
- разработка бренда - @atls/design 
- автоматизация и цифровизация рабочих мест @TorinAsakura 
- подключение или разработка CRM @atls/lab 
- интеграция с маркетплейсами @atls/lab

## Задача
На данный момент мы проводим стандартный анализ конкурентов, делаем срезы, смотрим можно ли (нужно ли) с этим работать.

Также надо прикинуть по цветовой подаче и фирменному стилю на котором будет формироваться бренд.

# Информация
Примерно через год (по её словам это 9-12 месяцев), владелица хочет открыть двухэтажный цветочный "дворец", там тебе и собственная речушка, и всякого рода цветения, короче "дворец", да.

На данный момент там всё работает по принципу 90-х, всё на звонках: "Петя! Ты почему трубку не берёшь?? Давай, езжай, собери наличку, и обязательно напиши на бамажке скох там денех!!" (реальный кейс почти дословно переданный, лично слышал в машине)

…и тех самых бумажках, нет никакой централизованной системы закупки/складского учёта, ну, и, конечно же, WhatsApp

Тем не менее они выжили всех конкурентов из Электростали и хотят начать экспансию. По словам владелицы - у них даже из Москвы заказывают.

# Материалы
- https://disk.yandex.ru/d/SX4qD5-w2ZgLcA - здесь материалы которые я вчера отфотал по 4-м цветочным магазинам в разных концах города.
- https://yandex.ru/maps/org/florentsiya/1787835213/?ll=38.447046%2C55.780425&z=15.94 по запросу "флоренция цветы" можно найти ещё два магазина, где четвёртый - не понятно

**Comment by dakand** [comment]
https://disk.yandex.ru/i/RuxiJvzQQ4D7ow Леночка негодует

**Comment by dakand** [comment]
@TorinAsakura @taqyon @sorokoumov Я посмотрел всё, что касается Флоренции. Какие выводы я могу сделать?

### Конкуренция
По их позиционированию можно предположить, что они забирают себе определённый сегмент клиентов и скорее всего этот сегмент лучше всего определяется возрастом. Происходит это скорее всего из-за её "цветочного" авторитета в Электростали. Поэтому, когда она говорит о том, что вытеснила других цветочников, то скорее всего речь идёт о конкуренции в рамках описанного сегмента. В Электростали есть и другие цветочные магазины (и даже с несколькими точками, что аналогично Флоренции), а это значит, что конкуренты есть - значит вытеснения не произошло.
Я не вижу необходимости взаимодействовать с их текущей аудиторией. Скорее всего консервативный процесс их устраивает, а попытавшись его как-то изменить есть вероятность тотального провала. Наша задача привлечь новых пользователей.

### Бренд
Название хорошее у них, а цветочки на вывесках не очень. На этом их брендинг заканчивается.
_Что мы тут сможем сделать?_ В теории мы можем сделать в логотипе тонкий золотой гротеск с большими отступами между буквами, сделать мягкий нежный бренд, но всё это будет ломаться после того как клиент зайдёт внутрь. Не самый свежий интерьер, полки заваленные игрушками, склад цветов прям в помещении, балоны (сужу только по фото по ссылке). Я не хочу сказать, что это плохо, просто это достаточно самобытно. Сомневаюсь, что она захочет заниматься сменой интерьера только потому что мы ей брендбук выкатим. Поэтому скорее всего направление придётся оставить, переделать на современный лад и выкатить брендбук - сделать одинаковые обложки, фоны и другие материалы (например, лого для крафтовой бумаги, мб захочет), описать правила использования. Так мы не создадим диссонанса и не отпугнём наш сегмент. Тут будет важно провести хорошую работу с фото товаров - от этого будет многое зависеть.

### Бизнес
Вот тут как раз мы и проявим наши сильные стороны. В первую очередь нужно провести работу над сайтом ([вот](
cvetokvip.ru) кстати их текущий). Нам будет необходимо сделать простой с точки зрения UX каталог c удобной формой заказа. Также нам будет необходимо сформировать сегменты по потребностям, чтобы все товары на сайте можно было по ним разделять. Далее я бы занимался полным редизайном соц. сетей - их нужно привести к единому виду, описать правила ведения соц. сетей и наладить связь с формой заказа. Также можем сделать несколько промо-страниц и таргетировать их на сегменты по потребностям (свадьбы, др). Скорее всего, что все эти шаги приведут нас к приросту новых пользователей. У Флоренции станет больше клиентов, а мы выполним самую важную задачу. Риска обосраться почти нет, т.к. мы создаём новые каналы продаж, которые не должны влиять на основные текущие.

### Вопросы, которые меня интересуют на данный момент
1. Какой средний чек? 
2. Есть ли сегмент, о котором я писал выше? Если да, то как она его охарактеризует?
3. Есть ли у них специальное направление (свадьбы, др, мб похороны… из 90-х же) или они универсальные?
4. Есть ли оптовые продажи? Если есть, то какая доля относительно всей выручки? Кто заказывает? И что можно считать оптом?
5. Предзаказов по телефону больше, чем просто пришёл-купил?
6. Кроме телефона есть ещё какие-то инструменты для взаимодействия с ними, которые работают на данный момент?

### Какой итог
Это из тех проектов, которые не стоит добавлять в портфолио, он будет достаточно заурядным и бренд неизвестный. Но если этот проект несёт за собой нормальную финансовую составляющую, то его нужно брать. Мы точно знаем какие шаги нужно предпринять, чтобы выполнить свою задачу и можем точно оценивать ресурсы.
- **Брендинг.** Как и говорил, лучше бы на аутсорсе взять кого-то, дать вводные, пусть рисует. Нам дешевле обойдётся, а тех кто сможет оформить бренд для цветов не сложно найти.
- **Дизайн сайта.** Я бы часов 100 заложил с запасом. Вполне хватит.
- **Оформление социальных сетей.** Часов 30. Ну и возможно на перспективу помогать первое время вести, но лучше пусть сразу заводят сммщика.
- **Промо страницы.** За 40 часов сделать шаблон, который мы сможем множить.
- _Можно ещё допродать кастомизатор (онлайн сбор букетов). Но это нужно делать только с чёткой целью, т.к. это технически сложно и не факт, что нужно._
---


### Мой вывод
Проекту не нужно уделять много творческого внимания, он может оказаться достаточно простым для нас, от части рутинным. Но мы здесь можем попрактиковаться в смм и взаимодействии с граф. дизайнером на аутсорсе. _В штат нам не нужен пока такой, но если найдём кого-то, кого сможем подключать на проекты в дальнейшем будет збс._


---

По итогу. @TorinAsakura нам чёто надо будет делать прежде чем ты подпишешь Флоренцию? Концепт какой или мб рефы. Я на самом деле хз даже с чего начинать (возможно, с брендинга как раз таки)

**Comment by TorinAsakura** [comment]
# Бренд
Это всё круто, но, есть ведь инфа о готовящейся стройки, где нужен будет кастомный интерьер. А новые точки? Ты чот как-т подзабыл, что помимо этих 4-х, будут открываться новые, поэтому я бы не был столь консервативен, а напротив, разъебал бы всё, да сделал с огоньком.
