### ISSUE TITLE
Уборка номера

### ISSUE THREAD

**Issue by TorinAsakura** [atls/design#46]
Пожалуйста, приведи в порядок задачи в данной репе.

## ЧТО ВСЁ ЭТО ЗНАЧИТ?
- расставь лейблы соответствующие задачи
- формализуй заголовки, часто не понятно о чём задача
- проекты, если нужно
- собери сроки, расставь майлстоуны

## ЗАЧЕМ ВСЁ ЭТО?
Я не могу управлять командой не понимая сходу кто чем занимается и на каком оно этапе, не говоря уже про всё остальное.

Ходить по каждой задаче и перечитывать все ветки - занимает много времени, хочется получать контекст непосредственно из формулировки задачи, иногда даже из лейбла и заголовка+проект,а а по майлостоуну понимать когда это планируется катить.

Сейчас же мне приходится перечитывать каждую таску и лазать по фигма-проектам.

**Comment by taqyon** [comment]
> ?

забыл закрыть
