### ISSUE TITLE
Cover для readme.md файла репо

### ISSUE THREAD

**Issue by taqyon** [atls/design#48]
**hyperion** звучит мощнее, он, атлас мне тоже отчасти нравится, хотя это звучит очень мусорно atls/atlas Atlantis Atlas…брр

Остановимся на hyperion

Цвета всё те же, светло-голубые, лёгкие, чот небесных оттенков, не грузящее.

@dakand призываю

_Originally posted by @TorinAsakura in https://github.com/atls/uikit/issues/430#issuecomment-1169867705_

---

## Что нужно сделать, вкратце

Нужен cover для ридми файла репозитория. В стилистике и цветах организации. Текстовый лого если проще. 

Название: Hyperion

## Размер и пропорции

Что-то средних размеров до 1000px. В остальном на твоё усмотрение.

<details>
<summary>Примеры из репозиториев которые скинул Андрей Гостюхин</summary>

<img width="899" alt="Снимок экрана 2022-06-29 в 14 14 39" src="https://user-images.githubusercontent.com/14002721/176423723-1a9ef9c3-9422-4bd7-b566-15e1fc8d5855.png">
<img width="866" alt="Снимок экрана 2022-06-29 в 14 14 31" src="https://user-images.githubusercontent.com/14002721/176423737-e75bcde2-74e5-4ad9-a16a-a115d25f4b9d.png">

</details>

<details>
<summary>Как это выглядит у них</summary>

<img width="966" alt="Снимок экрана 2022-06-29 в 18 37 01" src="https://user-images.githubusercontent.com/14002721/176477764-54a6d053-747e-4044-b295-56c71ab027a0.png">
<img width="932" alt="Снимок экрана 2022-06-29 в 18 36 56" src="https://user-images.githubusercontent.com/14002721/176477775-4e876f8f-c260-42cf-99e8-c68d10117eee.png">

</details>

Ну и ссылка для того чтобы посмотреть самому: https://github.com/twbs/bootstrap

**Comment by taqyon** [comment]
@TorinAsakura в течение этой недели будет готово

**Comment by dakand** [comment]
простите, извините

@ArtemHovsky надо сделать обложку для ридми файла репозитория "Hyperion". Как и что:
- Создай в [этом](https://www.figma.com/file/wC1teRe7FsrQqWGAliXtQF/All-Identity?node-id=24%3A442) проекте новую страницу для этой работы
- Ширина будет 1000px, пропорцию высоты и ширины высчитай из примеров [выше](https://github.com/atls/design/issues/48#issue-1293273788).
- Для фона используй уже привычную нам текстуру, которую мы юзали на всех превью атлантиса.
- На переднем плане будет лого HYPERION. Лого будет текстовый, для его создания можешь использовать шрифты, которые юзаешь в роудмэпе.
- Сделай светлый вариант с фиолетовым лого и фиолетовый вариант с белым лого.

**Comment by ArtemHovsky** [comment]
https://www.figma.com/file/wC1teRe7FsrQqWGAliXtQF/All-Identity?node-id=1322%3A34

**Comment by dakand** [comment]
> https://www.figma.com/file/wC1teRe7FsrQqWGAliXtQF/All-Identity?node-id=1322%3A34

Коммент оставил

**Comment by ArtemHovsky** [comment]
@dakand 
Доработал варианты

**Comment by dakand** [comment]
> https://www.figma.com/file/wC1teRe7FsrQqWGAliXtQF/All-Identity?node-id=1322%3A34

@TorinAsakura @taqyon Артём сделал несколько вариантов. Чекните. Если всё ок - закройте задачу.

**Comment by TorinAsakura** [comment]
> > https://www.figma.com/file/wC1teRe7FsrQqWGAliXtQF/All-Identity?node-id=1322%3A34
> 
> @TorinAsakura @taqyon Артём сделал несколько вариантов. Чекните. Если всё ок - закройте задачу.

Больше минимализма. Хочу, чтобы шрифт минимально нагружал. Вспомни, как мы с тобой шрифт для Атлантиса резали.

**Comment by TorinAsakura** [comment]
Предлагаю проработать этот вариант https://www.figma.com/file/wC1teRe7FsrQqWGAliXtQF/All-Identity?node-id=1364%3A34

**Comment by ArtemHovsky** [comment]
> Предлагаю проработать этот вариант https://www.figma.com/file/wC1teRe7FsrQqWGAliXtQF/All-Identity?node-id=1364%3A34

Все буквы будет заглавные? Вариант с прописными не делаем?

**Comment by TorinAsakura** [comment]
> > Предлагаю проработать этот вариант https://www.figma.com/file/wC1teRe7FsrQqWGAliXtQF/All-Identity?node-id=1364%3A34
> 
> Все буквы будет заглавные? Вариант с прописными не делаем?

не делаем

**Comment by ArtemHovsky** [comment]
@TorinAsakura @dakand 
Доработал вариант 
https://www.figma.com/file/wC1teRe7FsrQqWGAliXtQF/All-Identity?node-id=1373%3A309

**Comment by dakand** [comment]
> @TorinAsakura @dakand Доработал вариант https://www.figma.com/file/wC1teRe7FsrQqWGAliXtQF/All-Identity?node-id=1373%3A309

Только вынеси понятно актуальный варианты, остальное можно задизейблить или в архив. Чтобы все кто зайдут, понимали на что смотреть.

**Comment by TorinAsakura** [comment]
> @TorinAsakura @dakand
> Доработал вариант
> https://www.figma.com/file/wC1teRe7FsrQqWGAliXtQF/All-Identity?node-id=1373%3A309

что-то я вообще не понял на что смотреть и что изменилось

**Comment by ArtemHovsky** [comment]
> > @TorinAsakura @dakand
> > Доработал вариант
> > https://www.figma.com/file/wC1teRe7FsrQqWGAliXtQF/All-Identity?node-id=1373%3A309
> 
> что-то я вообще не понял на что смотреть и что изменилось

Почему не понятно? Ссылка ведет на версию логотипа.

**Comment by TorinAsakura** [comment]
@ArtemHovsky Я не понимаю что изменилось в нём

**Comment by ArtemHovsky** [comment]
> @ArtemHovsky Я не понимаю что изменилось в нём

Теперь я не понимаю, что сделать. 
Нравится или не нравится вариант

**Comment by TorinAsakura** [comment]
@ArtemHovsky Я спрашиваю тебя в чём отличия этого варианта от предыдущего, по которому я оставлял комментарий. Ты гонишь?

**Comment by ArtemHovsky** [comment]
https://www.figma.com/file/wC1teRe7FsrQqWGAliXtQF/All-Identity?node-id=1411%3A34
Вот версия которую дорабатывали

**Comment by TorinAsakura** [comment]
@ArtemHovsky ещё раз - что-ты-там-дорабатывал? Ты понимаешь какой я вопрос ставлю? Я не ставлю вопрос **где**, я ставлю вопрос **что**.

Вот что изменилось с момента моего последнего коммента https://github.com/atls/design/issues/48#issuecomment-1199322101 ?

**Comment by ArtemHovsky** [comment]
> @ArtemHovsky ещё раз - что-ты-там-дорабатывал? Ты понимаешь какой я вопрос ставлю? Я не ставлю вопрос **где**, я ставлю вопрос **что**.
> 
> Вот что изменилось с момента моего последнего коммента [#48 (comment)](https://github.com/atls/design/issues/48#issuecomment-1199322101) ?

Отрисовал буквы в векторе. Буквах с горизонтальными линиями обрезал оставив одно пиксельное соединение. Внутренние углы в буквах скруглил на 4px, внешние на 12px. Выровнял трекинг.

**Comment by TorinAsakura** [comment]
Я бы дорезал эти остатки, выглядит оч не оч, как по мне

![Снимок экрана 2022-08-03 в 20 36 25](https://user-images.githubusercontent.com/3940885/182673040-f9b31416-2166-49e8-b0e1-0b075626ee1c.png)

Y смотрится оторванной от общей стилистики
E можно попробовать как у EVE Online

В остальном вроде ок

> > @ArtemHovsky ещё раз - что-ты-там-дорабатывал? Ты понимаешь какой я вопрос ставлю? Я не ставлю вопрос **где**, я ставлю вопрос **что**.
> > Вот что изменилось с момента моего последнего коммента [#48 (comment)](https://github.com/atls/design/issues/48#issuecomment-1199322101) ?
> 
> Отрисовал буквы в векторе. Буквах с горизонтальными линиями обрезал оставив одно пиксельное соединение. Внутренние углы в буквах скруглил на 4px, внешние на 12px. Выровнял трекинг.

**Comment by ArtemHovsky** [comment]
@TorinAsakura 
Внес правки. Оставил комменты. Посмотри пожалуйста

**Comment by TorinAsakura** [comment]
Если что, откомментил почти сразу, жду реакции.
1.3 деактивировал

**Comment by ArtemHovsky** [comment]
> Если что, откомментил почти сразу, жду реакции. 1.3 деактивировал

Добавил варианты

**Comment by TorinAsakura** [comment]
Об этой крестовине шла речь

![Снимок экрана 2022-08-05 в 11 13 40](https://user-images.githubusercontent.com/3940885/183033469-c2578287-3f7e-45ba-9860-f4e0b4aeb5ae.png)

**Comment by ArtemHovsky** [comment]
Добавил

**Comment by ArtemHovsky** [comment]
Попробуй поставить обложку

https://www.figma.com/file/wC1teRe7FsrQqWGAliXtQF/All-Identity?node-id=1350%3A34

**Comment by TorinAsakura** [comment]
@ArtemHovsky https://github.com/atls/uikit

**Comment by dakand** [comment]
@ArtemHovsky Тём давай ещё один вариант попробуем, это быстро. Мне оч не нравится буква "Y" - её срез выглядит как дефект, давай срежем по другой части, как здесь https://disk.yandex.ru/i/-YHXHxpqd97sKQ.

**Comment by ArtemHovsky** [comment]
Я показывал похожий вариант. Не приняли
![image](https://user-images.githubusercontent.com/103929181/183352975-d7e455f4-2be1-48f4-89c3-b47524c42750.png)
