### ISSUE TITLE
Atlantis Jobs

### ISSUE THREAD

**Issue by sorokoumov** [atls/design#49]
Собрать данные и флоу по инхаус HR-tech стартапу

**Comment by sorokoumov** [comment]
[HR-Tech.pdf](https://github.com/atls/design/files/9054048/HR-Tech.pdf)
@TorinAsakura PDF

**Comment by taqyon** [comment]
**Дисклеймер!**

Это фидбек на документ HR-Tech.pdf. При прочтении я мог что-то интерпретировать не так, как задумывал автор. И поэтому где-то в своих выводах я могу ошибиться. Также я опираюсь на то, что получил в процессе диалога с @TorinAsakura.

---

## Проблемы

- С точки зрения соискателя всё в точку. Круто написано и раскрыто. Каждый пункт отзывался в моём сердце, а я чувствовал фантомную боль.
- С точки зрения работодателя, мне трудно сказать, но по ощущениям тоже близко. Даже если опираться банально на логику и на представление о тратах ресурсов (время, силы, ментальные силы). 

## Упрощение и добавление ценности

Я не понял. Ну, то есть я в **_ОБЩИХ_** чертах понял. Но детально не понял. 

Считаю что эта секция самая важная в документе и она должна быть раскрыта лучше, чем сейчас. Стоит в отдельном документе детализировать главные бизнес процессы: 

- Поиск работы (от лица соискателя)
- Найм сотрудника (от лица работодателя)

Я бы рисовал максимально детализированный флоучарт. И уже из валидированной и максимально детализированной информации выжал бы другую схему — попроще, но понятней и добавил бы сюда. Главное здесь — убедиться что она работает и её понимают другие люди. 

## Охват на MVP

Нужно полностью переделать. Этот пункт вытекает из представления о том, какой должен быть сервис. Если сказать проще: нужно постараться представить себе полностью сервис, в деталях и взаимодействиях, а потом резать. Здесь отмечу что, не нужно «выдавливать из себя сервис», а скорее отдаться творчеству и набрать максимальное представление о сервисе. А потом, как я уже сказал ранее — резать. 

Список может выглядеть вот так: 
- Пилим полностью процесс найма для соискателя
- Отсев кандидатов для работодателя
- Оплата того или сего

Я всегда себе представляю это метафорой: это как если бы электрический ток шёл по пути наименьшего сопротивления к своей конечной точке. То есть нужно выбрать то, что заставляло бы выполнять ключевые бизнес процессы, без излишеств. 

## Квалификационный отбор

В общем я проснулся сегодня и понял, что так и не понял кто кого должен проверять. Здесь нужно больше раскрыть эту тему: 
- Что такое Квалификационный отбор? 
- Кто такие эксперты?
- На каких этапах он будет являться? И кому? 
- И наверняка еще можно вопросы придумать, чтобы раскрыть больше 

## Анкета

То же самое что и с Квалификационным отбором. Но здесь я бы припорошил схемкой или простым прототипом. Чтобы быстро окинуть взглядом то, о чём идёт речь. Потому что когда говоришь анкета, представляешь анкету — визуал. 

## Подтверждение экспертизы сервиса

Здесь надо пару слов, о процессе подтверждения экспертизы. 

## Партнеры для трафика

Я полагаю что это каналы сбыта (дистрибуции). Может быть стоит немного переписать, более конкретно. 

## Монетизация

Здесь стоит добавить к каждому пункту пример. 

Например: 
- Работодатели платят за успешных кандидатов 
  - Работодатель нашёл кандидата и устроил к себе в компанию, заплатил 50% от стоимости вакансии. Что-то такое. 

## Почему ему не отправить отклик напрямую в кампанию?

Вот это крутой вопрос. Было бы круто, добавить еще подобных вопросов, но по существу. Наверняка они есть. И эта секция будет что-то типа «работа с возражениями».

---

## Вывод: 

По моему мнению текущий текст сыроват. Нужно больше представления о сервисе. Сейчас там много белых пятен. Рассказать об идее и при этом быть конкретным — тяжело. Сторонний слушатель не поймёт, особенно если он далёк от веб-сервисов. Но он может быть «близок к финансам» но и эта сторона не раскрыта. Цифр нет. 

_Каким-то образом_, надо получить цифры текущей ёмкости рынка найма, чтобы рассчитать монетизацию, какой-никакой финансовый план и бизнес-план. А дальше раскрыть лучше ценность предполагаемой услуги. Ну и написать больше рукописей по самому сервису: акторы, процессы, бизнес процессы, сущности, взаимодействия и так далее. Эта часть нужна скорее «для себя», чтобы быть более уверенным в своей собственной идее. Ну и иметь возможность хотя бы **_ОДНИМ_** абзацем нормально обѣяснить суть.

**Comment by sorokoumov** [comment]
@TorinAsakura из чего состоит квалификационный отбор?

>>За прохождение этого отбора мы можем гарантировать соискателю, что он сможет получить лучшее предложение, чем с обычного поиска.
Можешь сюда текстом написать, я помню, ты упоминал что у тебя была концепция.

>>инженер сможет оценить владение необходимыми программами и языками.
Тут тоже хочется понять что по итогу мы получим после прохождения квалификационного отбора.

>>Кто такие эксперты?
С какими экспертами ты сможешь подтвердить задание, которое будет выдаваться на квалификационный отбор

**Comment by TorinAsakura** [comment]
> @TorinAsakura из чего состоит квалификационный отбор?
> 
> > > За прохождение этого отбора мы можем гарантировать соискателю, что он сможет получить лучшее предложение, чем с обычного поиска.
> > > Можешь сюда текстом написать, я помню, ты упоминал что у тебя была концепция.
> 
> > > инженер сможет оценить владение необходимыми программами и языками.
> > > Тут тоже хочется понять что по итогу мы получим после прохождения квалификационного отбора.
> 
> > > Кто такие эксперты?
> > > С какими экспертами ты сможешь подтвердить задание, которое будет выдаваться на квалификационный отбор

Тесты будут формироваться исходя из предпочтений соискателя.

Основные критерии которые помогут подсветить компетентные стороны соискателя:
- работа с кодом (подсветка инженера)
	- знание апи
	- работа с памятью
	- асинхронность против синхронности и наоборот
	- применение паттернов
- проектирование (подсветка технического менеджера)
- работа с дизайном архитектуры (выделение слоёв с последующей декомпозицией) (подсветка архитектора)
- творческий подход к решению задач (задача решена нестандартным способом) (подсветка IQ -  такие штуки будут особым образом маркироваться, а человек будет помечен в системе особым маркером)
- задача решена при помощи третьей стороны (stackoverflow, habr qa, github) (подсветка менеджера)

**Comment by sorokoumov** [comment]
@TorinAsakura За прохождение этого отбора мы можем гарантировать соискателю, что он сможет получить лучшее предложение, чем с обычного поиска.

Тема не раскрыта в ответах)
Я понял что мы будем его скорить, но не понял за счет чего он получит больше бабох

**Comment by sorokoumov** [comment]
@bbbaso https://www.notion.so/asorokoumov/HR-Tech-5ca31f5d32ee4a2d862d773b87a6131f
Ноушн в котором я пишу.

**Готовы:**
- Блок с проблемами. Соискателя и работодателя
- Блок про продукт. Со стороны соискателя. Основной флоу.
Основной флоу нужно обязательно показать полностью на одном слайде, после чего давать по отдельному слайду на отдельный этап.
В конце блока про продукт со стороны соискателя добавь текстом большой слайд с текстом ВЫВОД большим шрифтом. @TorinAsakura импровизировать будешь, или придумывай сейчас чтобы Рома тебе че-то оформил)

Это все было бы классно оформить в презентацию пока до блока с монетизацией.

**Я дополняю**
- Монетизацию 
- Партнеры для трафика

**Comment by TorinAsakura** [comment]
## По подбору анкет под вакансию

### Анкеты будут предлагаться компаниям, по следующим критериям:

Пример: 
- ищут php разработчика
- не ниже middle
- ставка 125к/месяц
- обязательно symfony 4+
- doctrine 5+

- у соискателя ставка не больше 25к от ставки вакансии или равна ей (мы допускаем отклонения от ставки в бОльшую сторону чем хочет работодатель, **при** условии, что, соискатель подходит по всем критериям более, чем, на 90%, **и** готов выйти уже на этой недел)
- стаж разработки на php от 2-х лет (основные критерии базируются на фундаментальных навыках)
- стаж разработки с применением sql от года (основные критерии базируются на фундаментальных навыках)
- стаж разработки на symfony от года (вторичные критерии базируются на подтверждении фундаментальных навыков, то есть, не пройдя теста на php он не сможет указать ни одного фреймворка)
- стаж разработки с применением Doctrine ORM от полугода (вторичные критерии базируются на подтверждении фундаментальных навыков, не пройдя теста на sql он не сможет указать ни одну из ORM)

**Comment by sorokoumov** [comment]
![Снимок экрана 2022-07-09 в 15 05 49](https://user-images.githubusercontent.com/16300249/178104915-d73817e0-87fc-4006-8c1f-ac5617d9f119.png)
@bbbaso добавил блок с дополнительным собеседованием и получением оффера в блоки по физику

**Comment by sorokoumov** [comment]
![Снимок экрана 2022-07-09 в 15 08 12](https://user-images.githubusercontent.com/16300249/178105000-538af81d-50db-48b4-8c56-c72d45e08a00.png)
@bbbaso добавил монетизациюю на стороне соискателя

**Comment by sorokoumov** [comment]
![Снимок экрана 2022-07-09 в 15 09 56](https://user-images.githubusercontent.com/16300249/178105065-6a891402-81bc-47eb-b7e9-55a18ecc3e98.png)
@brusselboy блок с стороной HR-менеджера тоже добавил, и монетизацию со стороны работодателя тоже

**Comment by bbbaso** [comment]
Пока показываю обещанное - [Файл](https://www.figma.com/file/QBVZldMh0VUQYcJogl1vRJ/HR-Tech---Presentation?node-id=0%3A1)

И куда лучше положить его? (т.к. он пока в драфте)

**Comment by TorinAsakura** [comment]
@bbbaso Положи его в Atlantis и назови Jobs. P.S: отписал тебе комменты.

**Comment by bbbaso** [comment]
И мб стоит ссылку в строчке "Более развернутая информация" к чему-то конкретному в файле прикрепить, т.к будет бросать просто на артборд, а там "куда", "что" непонятно...
![image](https://user-images.githubusercontent.com/103942572/178107865-9cfc8c67-d694-401c-935f-c3ddfcb3bb97.png)

**Comment by TorinAsakura** [comment]
> И мб стоит ссылку в строчке "Более развернутая информация" к чему-то конкретному в файле прикрепить, т.к будет бросать просто на артборд, а там "куда", "что" непонятно...
> ![image](https://user-images.githubusercontent.com/103942572/178107865-9cfc8c67-d694-401c-935f-c3ddfcb3bb97.png)

Точно надо, да и артборд надо почистить, а то тут ад

**Comment by taqyon** [comment]
https://www.notion.so/asorokoumov/HR-Tech-5ca31f5d32ee4a2d862d773b87a6131f

**Comment by bbbaso** [comment]
Преза готова. 

Касаемо файла Fig Jam - мне там прибраться? _*прост чтобы я там не нарушил чей-то творческий хаос_

**Comment by TorinAsakura** [comment]
@bbbaso Приберись конечно

**Comment by bbbaso** [comment]
мне бы доступ туда

**Comment by TorinAsakura** [comment]
@bbbaso Done

**Comment by TorinAsakura** [comment]
Презентация ушла адресатам. Всем спасибо за работу.
