### ISSUE TITLE
Дизайн новой страницы услуги для сайта Misik.pro

### ISSUE THREAD

**Issue by taqyon** [atls/design#52]
## Что надо сделать?

Собрать макет страницы, посвященную новой услуге для сайта https://misik.pro/. 
Так как своего контента у владельца сайта нет, он дал добро на то, что бы мы взяли за основу контент его партнёров: https://immigrationmex.com/usa

## Что именно можно брать? 

- Весь текстовый контент 
- Изображения и фото можно взять, но иметь в виду, что они скорее всего будут заменены
- Структура: На своё усмотрение. Здесь на самом деле много не придумаешь, но если есть идеи получше — пожалуйста 

 ## Что должно быть в итоге? 

Свёрстанный макет страницы новой услуги в стиле сайта misik.pro с использованием контента из https://immigrationmex.com/usa

---

[Проект](https://www.figma.com/file/rk2ELp7UFqqvYJgfC07o6W/Misik-%7C-Web-site?node-id=250%3A2) в Figma.

**Comment by taqyon** [comment]
Жду контент

**Comment by taqyon** [comment]
#### Есть

- Партнёры, которые готовы делится деньгами

#### Цена

15 000 / 25 000 $

#### Самое главное

- Ответить на вопросы людей
- Дать информацию о том, с какой ситуацией они могут столкнуться

#### Описание, спич

- Адвокаты беру клиента
- Выслушивают
- Дают комментарии
- Готовят кейс
- Отправляют другу
- Друг передаёт в иммиграционную службу
- Клиент двигается на блок пост
- Клиента встречают и сопровождают при прохождении границы

На сегодня, ни одна из компаний не может этого делать. 

Самое главное — отклик от клиентов.

**Comment by TorinAsakura** [comment]
@taqyon status?

**Comment by taqyon** [comment]
> @taqyon status?

in progress

**Comment by ArtemHovsky** [comment]
Делать в структуре страницы как в примере, такие блоки: "Наши специалисты", "О компании"?

**Comment by taqyon** [comment]
> Делать в структуре страницы как в примере, такие блоки: "Наши специалисты", "О компании"?

Да. На сайте misik.pro таких секций нет, значит не будет дубляжа. На крайний случай, если что зарежем. Но шанс мал

**Comment by dakand** [comment]
> @dakand Посмотри пожалуйста макет страницы и адаптив

Збс в целом. Комменты оставил, нужно отработать.

**Comment by dakand** [comment]
@ArtemHovsky сегодня допилишь? Как внесёшь правки, организуй все макеты. После отпишись Ване, он проверит.

@taqyon я днём сегодня отвалюсь. Поэтому, чтобы вы меня не ждали, если Артём сделает всё до моего возвращения - проверь контент и отправь Борису, если считаешь нужным. С точки зрения дизайна я всё подтверждаю _(помимо правок, но Тёма с ними справится)_.

**Comment by ArtemHovsky** [comment]
@dakand Внес правки. Организовал макеты.

@taqyon Посмотри пожалуйста

**Comment by taqyon** [comment]
> @dakand Внес правки. Организовал макеты.
> 
> @taqyon Посмотри пожалуйста

Всё окей как по мне, я закину Борису посмотреть, нужно получить явное одобрение

**Comment by taqyon** [comment]
@ArtemHovsky @dakand 

Борис написал: 

>Мне нравится 👍

---

Запросил у него фотки и фио специалистов, жду материалов. Скину как будут.

**Comment by dakand** [comment]
@ArtemHovsky чекни один коммент в фигме

**Comment by taqyon** [comment]
@dakand @ArtemHovsky пришли некоторые правки: 

- Надо убрать полностью блок: Наши специалисты.

«Наши специалисты» побаиваются светить лицами. Поэтому блок просто убираем :)

**Comment by taqyon** [comment]
Еще нужно убрать слово «политическое»
![Снимок экрана 2022-07-16 в 02 26 30](https://user-images.githubusercontent.com/14002721/179323877-793e5830-a198-4130-97f8-24a6b2268c87.png)

**Comment by ArtemHovsky** [comment]
Внес правки

**Comment by taqyon** [comment]
@ArtemHovsky Нужно еще добавить номера телефонов в секцию свяжитесь с нами: 
- +7 (909) 998-26-26 (WhatsApp, Viber, Signal) 
- +1 (786) 961-47-21

**Comment by taqyon** [comment]
> Готово, добавил

Блин я не уточнил прости, номер +7 (916) 100-35-05 нужно убрать, это не наш номер
