### ISSUE TITLE
Atlantis Wallet

### ISSUE THREAD

**Issue by sorokoumov** [atls/design#53]
Собрать материалы для презентации по крипто-банку

**Comment by sorokoumov** [comment]
[CryptoCompany.pdf](https://github.com/atls/design/files/9066066/CryptoCompany.pdf)
@TorinAsakura qq, посмотри материалы, пожалуйста.

Хочешь чем-то дополнить, или могу отдать Саше.
Если нужно привести где-то к читабельному формату - пиши, я мож еще утром почитаю и подправлю че-то

**Comment by sorokoumov** [comment]
@taqyon @aroundblacksneverrelax мы продаём не Приложение.
Мы продаём технологию.
Приложение - то, что на этой технологии потом строится.
И в иерархии продажи я хочу чтобы это оставалось так.
Потому, что на базе технологии мы можем делать огромное количество приложений.

И для бизнеса и для физиков

**Comment by taqyon** [comment]
> @taqyon поинтересуйся у Бориса на эту тему. Он, вроде как, юрист

на какую?

**Comment by TorinAsakura** [comment]
> > @taqyon поинтересуйся у Бориса на эту тему. Он, вроде как, юрист
> 
> на какую?

"И к этому всему добавляются юридические сложности и знания работы с фиатом в других странах, это как быстрый пример."

**Comment by sorokoumov** [comment]
@taqyon Мне кажется на данном этапе, нужно чётко понимать за что именно берёмся. Каждая область — это невероятно сложная херня.

Если написать роадмэп что за чем делаем так будет лучше?

**Comment by taqyon** [comment]
> @taqyon Мне кажется на данном этапе, нужно чётко понимать за что именно берёмся. Каждая область — это невероятно сложная херня.
> 
> Если написать роадмэп что за чем делаем так будет лучше?

Честно говоря, не знаю, надо смотреть. 

После твоей фразы: 

>Мы продаём технологию.

Стало вообще ничего не понятно.

**Comment by TorinAsakura** [comment]
@taqyon Я думаю, для начала нужно описать продукт, упомянув в нём "некую" технологию собственного производства (тот же эппл всегда так делает и нихуя никому не рассказывает ни до продаж, ни после) и продолжать развивать текущий док, иначе завтра я никуда не поеду

**Comment by sorokoumov** [comment]
@taqyon 
**Но там везде важна техническая составляющая. Надо понять насколько это реально вообще.**

**Comment by sorokoumov** [comment]
@taqyon Но там везде важна техническая составляющая. Надо понять насколько это реально вообще.
это вопрос к @TorinAsakura, но Боря нам тоже нужен будет.
Потому, что как я понимаю мы должны будем получать банковскую лицензию в юрисдикциях стран, куда мы будем проводить экспансию и давать им возможность купить валюту на наш счет из любой юрисдикции.
Мы со свой стороны по идее можем со счета компании оплачивать его покупки внутри юрисдикции страны сделав ему виртуальную карту с нужным платежным эмитетом.

Но факт останется фактом, что мы сами попробуем оплатить с разных и сами будем считать какие комиссии выгодные. По факту у тебя будут почти все. Отключенные будут обходиться за счет того, что есть много вариантов изнутри. Факт останется фактом — перевод ты сделаешь.

**Comment by TorinAsakura** [comment]
@sorokoumov 1. В тех же штатах, если ты перебросил деньги с крипты, вывел их и хочешь положить на счёт в банке - у тебя начнут проверять источник их происхождения и все ли ты налоги за них заплатил, так что тут не всё так просто, впрочем и это я тоже учёл.

Это всё происходит посредством банка-корреспондента или иного брокера/провайдера. Пока не понятен предмет обсуждения. Трансграничные переводы это не такая большая проблема, вопрос чисто юридического характера.

**Comment by TorinAsakura** [comment]
@taqyon Вынести в фигму и можно закрывать

**Comment by taqyon** [comment]
> @taqyon Вынести в фигму и можно закрывать

pdf файл?

**Comment by TorinAsakura** [comment]
@taqyon скорее содержимое пдф файла, хотя бы в том же виде что и преза по HR, чтобы это были фреймы с объектами, мне с этим в ближайшее время работать предстоит

**Comment by taqyon** [comment]
> @taqyon скорее содержимое пдф файла, хотя бы в том же виде что и преза по HR, чтобы это были фреймы с объектами, мне с этим в ближайшее время работать предстоит

https://www.figma.com/file/C70JqLxKDYflYV6twZerkB/CryptoCompany?node-id=1%3A7
