### ISSUE TITLE
Доработка презентации Jobs

### ISSUE THREAD

**Issue by sorokoumov** [atls/design#54]
привет!
Я там графиков накидал в https://www.figma.com/file/QBVZldMh0VUQYcJogl1vRJ/Jobs?node-id=20%3A2 в draft.
их надо бы перевести в стилистику нашей презы.

Я докину еще монетизацию и окупаемость.
Покажу как на слайде нужно будет, чтобы выглядело.

**Comment by TorinAsakura** [comment]
@sorokoumov статус проставлять не забывай и таску актуализировать

**Comment by dakand** [comment]
@sorokoumov @TorinAsakura закрываем?
