### ISSUE TITLE
Доработка Misik pro

### ISSUE THREAD

**Issue by dakand** [atls/design#56]
- [x] Добавить в шапку ссылку на программу переезда и контакты. Якорные ссылки убираем. (десктоп)
- [x] Сделать инверсию скрол бара. Например, сейчас когда мы долистываем до карты, то элементы скрол бара накладываются на текст на карте. Нужно аккуратно избавиться от этой проблемы. (десктоп)
- [x] На странице программы переезда блок контактов не оч выглядит. Там разные отступы и иконки мессенджеров сильно утяжеляют дизайн. Нужно оптимизировать дизайн, переделать иконки или найти другое решение. (десктоп и мобилка)
- [x] Как следствие из предыдущего нужно подготовить пак популярных социальных сетей и разместить иконки в материалах (иконки можно стилизовать под нас).
- [x] Сделать бургер меню для адаптива, внутри которого буду ссылки на программу, контакты и заявку. (мобильная)
- [x] Объединить блок "Формат работы" и "отзывы" в один - "Работа"
- [x] Сделать превью для шейринга для трёх страниц: главная, программа переезда в США, контакты. Нужно их сделать отличными друг от друга.

**Comment by dakand** [comment]
@bbbaso твоя задача

**Comment by dakand** [comment]
@bbbaso Добавил комментарии. Некоторые комменты из десктопа относятся и к адаптиву.

**Comment by bbbaso** [comment]
@dakand Комменты отработал

**Comment by TorinAsakura** [comment]
@dakand status?

**Comment by dakand** [comment]
@bbbaso нужно добавить в блок отзывов кнопку "Показать полностью", если текст занимает много пространства. Для такого отзыва нужно предусмотреть модалку как на [dream team](https://www.figma.com/file/OFpidYSscy6NOYWpRsfdwt/DreamTeam-web-site?node-id=134%3A5477). Сделать как в дестопе, так и в адаптиве.

_P.S. Нужно АСАП, делов на пол часа. Сообщи, если по какой-то причине не можешь это сделать сейчас._

**Comment by dakand** [comment]
@TFK70 мб не видели, но картинки для шейринга [тут](https://www.figma.com/file/rk2ELp7UFqqvYJgfC07o6W/Misik-%7C-Web-site?node-id=2906%3A3358).

**Comment by dakand** [comment]
@brusselboy [модалка](https://www.figma.com/file/rk2ELp7UFqqvYJgfC07o6W/Misik-%7C-Web-site?node-id=3105%3A2072)

**Comment by bbbaso** [comment]
@dakand done
