### ISSUE TITLE
Разбивка лендинга академии по этапам

### ISSUE THREAD

**Issue by TFK70** [atls/design#57]
###  Задача

Разбить [лендинг](https://www.figma.com/file/TRNQoY3DBNRursnvMDwm02/Landing-page?node-id=887%3A2241) академии по этапам для верстки

**Comment by dakand** [comment]
[Ссылка на Figma](https://www.figma.com/file/SHoss54mn2SZLnI0e3OiJj/Practice?node-id=15%3A376)
