### ISSUE TITLE
Реорганизация проектов в фигме

### ISSUE THREAD

**Issue by TFK70** [atls/design#58]
###  Задача

Реорганизовать команды и проекты в организации Atlantis в фигме

### Проблема

- Содержание проектов в разных командах иногда может пересекаться
- Затруднительная навигация по конкретным проектам

###  Перечень текущих проектов и команд

<details>

# Misik

- `Misk | Web Site` - основной проект с лендингом
- `Test task` - насколько я понял, тестовое задание для кандидатов. В нем необходимо как раз сделать дизайн для сайта
- `Misik | Identity` - визитки

# Кинорепортер

- `Kinoreporter | Web-Site` - проект с самим сайтом
- `КР Distribution Schemes` - схема, в которой описан механизм "экспорта" контента с кинорепортера на другие ресурсы
- `Editor Prototype` - черновой прототип редактора статей
-  `КР JAM File` - пока не совсем понял что это, но выглядит как флоу создание статьи в WYSIWYG редакторе

# HR

- `HR Tech (Main Project)` - сейчас там есть стартовый экран, где регистрируется пользователь, и некоторые схемы описывающие флоу
- `Scenarios` - JAM со сценариями, возможными на ресурсе
- `HR Tech, Atlantis` - JAM где очень много доп.инфы о процессе работы с ресурсом, но, видимо, здесь разбирался флоу на ресурсе на примере атлантиса. Там находятся и грейды для кандидатов, и портреты идеальных кандидатов, и флоу со стороны работодателя и тд, пока сложно это в какую-то категорию определить
- `Business Processes` - JAM с 2-мя схемами: `Бизнес процес закрытия вакансии работодателем` и `Процесс поиска работы соискателем`
- `Matching` - описания процесса сопоставления вакансии и кандидата, видимо для реализации рекомендаций или что-то в этом духе
- `Specialists` - одна схема со скиллами и грейдами для typescript developer (которую я делал), но эта схема уже есть в проекте `HR Tech (Main Project)`
- `Atlantis HR` - дизайн, видимо, лендинга ресурса

# Atlantis

- `Roadmap` - проект "Башни"
- `Jobs` (design file) - схемы, диаграммы, какая-то аналитика связанная с jobs
- `Jobs` (JAM file) - поймал дежавю, потому что схемы в этом файле я уже видел в файле `Atlantis HR` в команде `HR`
- `All Identity` - иконки
- `Projects Identity` - opengraph превьюхи для follow the compass
- `Atlantis Design` - стартовая страница ресурса design
- `Landing Page` - лендинг атлантиса
- `Atlantis Design` (да, еще один) - дизайн ресурса design
- `Coming Soon` - видимо заглушка для сайта атлантиса с возможностью оповещения о запуске сайта
- `Identity (Archive)` - шрифт, мерч, визитки

# Torin Asakura

- `Banner` - баннер с самураем
- `Torin Asakura Web-Site` - дизайн сайта torin asakura
- `Torin Asakura web-site (not actual)` - неактуальный дизайн сайта torin asakura

# Чиним Возим

- `Work` - дизайн сайта чиним возим

# Drum In

- `Drum Instructor` - дизайн сайта drum in
- `Открытие ритма` - дизайн страницы курса 
- `Landing online course` - трудно сказать чем этот проект отличается от открытия ритма
- `Landing Lessons` - видимо, старая версия сайта drum in (которую судя по всему делала Olga Darenskaya)
- `Brand` - варианты логотипов

# Familia

- `Tender` - сайт для фамилии

# Dream Team

- `Dream Team web-site` - сайт дт

# YouThink

Пока не стал разгребать то, что внутри. Актуален ли юсинк вообще?

# Atlantis Design

- `Projects Presentation` - презентации для проектов (к слову, там есть и ЮС)
- `Projects Pages` - файл с референсами <на что-то>: там есть ссылки на альфу, луч, art&ux и прочие ресурсы

# Байкал сервис

- `Байкал сервис | ЛК` - дизайн личного кабинета сервиса

# BMW Group

- `BMW AS Shop` - дизайн сайта магазина BMW со всякими шмотками
- `MINI Cooper Online Sales` - страница покупки автомобиля
- `BMW AS Shop (Animations)` - анимации для сайта магазина
- `BMW F44 Online Sales` - страница покупки автомобиля

# BWT

- `Barrier Active` - дизайн сайта для барьера
- `Ecomix` - дизайн сайта для конкретного продукта барьера (ecomix - его  название)

# РусАтом

- `RusAtom` - дизайн сайта русатома
- `Edu RusAtom` - дизайн образовательного ресурса русатома

# Pump

- `PUMP App` - дизайн мобильного приложения PUMP

# Academy

- `Landing Page` - дизайн лендинга академии

# Tutorials

- `Spline - Tutorial` - презентация с туториалом по сплайну
- `3D Moodboards` - ссылки на разные 3д сцены

# РФРИТ

- `РФРИТ | Презентация`
- `РФРИТ | Структура обновления`
- `Untitiled` - анализ РФРИТовской презентации

# HRech (я не опечатался)

- `HRTech Flow` - описание проблемы, которую должен решать jobs
- `Untitled` - пустой JAM

# Шинный двор

- `Шинный двор` - видимо наброски для мобильного приложения шинки
- `Шинный Двор` (х2) - дизайн сайта шинки

# Banxe

- `Project analysis` - судя по всему анализ существующего дизайна в Banxe
- `Example of a structure` - референс к файлу выше

# Blog - Olga Gostyuhina

- `Logo - Olga Gostyuhina` - лого

# Epoch Crysis

- `Epoch Crysis - web-site` - дизайн сайта
- `Epoch Crysis - Identity` - лого и кавер

# Мастерок

- `Мастерок` - баннер, фоновое изображение, изображение профиля

# Beatster

- `Beatster | Version 1.2` - версия сайта 1.2
- `Beatster | Admin panel` - дизайн админ панели
- `Beatster | Admin panel` (x2) - иллюстрация сценариев в админке
- `Support` - трудно подогнать все, что там находится под одну категорию, так что вот список:

![image](https://user-images.githubusercontent.com/62806448/180756700-208bc228-70a5-47c5-8641-7859af76093e.png)

# Follow the Compass

- `Follow the Compass` - лого

# Aeterna

- `Admin panel` - дизайн админ панели

# Blondinka KSU

- `Identity` - баннеры, логотипы, фавиконки

# Serenity

- `Serenity` - дизайн серенити

# Pheonix

- `Pheonix` - дизайн платформы для покерстов

# Poker Service Analytics

- `PSA` - дизайн Poker Service Analytics

</details>

**Comment by TFK70** [comment]
@TorinAsakura 

Основная проблема - слишком большое количество команд

### Объединение сателлитов

Предлагаю поместить сателлиты в одну команду:

Команда - **Torin Asakura:**

- Misik
- Dream Team
- Drum In
- Shinny Dvor
- Blondinka KSU
- Follow the Compass
- Masterok
- Сайт https://torinasaskura.name

### Объединение проектов атлантиса

Здесь на мой взгляд объединение будет не целесообразным

Дело в том, что, например, юсинк содержит в себе 13 проектов (даже если почистить неактуальное - все-равно останется как минимкм порядка 5 проектов (может больше)), кинорепортер содержит в себе 4 проекта, с сайтами атлантиса (например jobs) аналогично.

Столько появляется из-за потребности рисовать схемы, которые оформляются как отдельный проект (потому что это JAM, а не Design), поэтому, я считаю, что если мы все эти проекты поместим в одну команду, то возникнет очень большая путаница и бардак, и ориентироваться в них станет еще труднее. С сателлитами такого как правило нет, в случае с ними все можно оформить в одном проекте тк они в основном поменьше

В связи с этим предлагаю оставить с этими проектами все как есть: оставить YouThink, Beatster, Кинорепортер и другие "большие" проекты в своих командах

### Очистка мусора

Однозначно нужно избавиться он ненужных команд/проектов. Здесь все просто - нужно просто синкаться и узнавать какие проекты есть смысл оставлять, а какие - нет.

### Остальные проекты

Под остальными проектами я подразумеваю Barrier, Pheonix, Pump  и прочие. Здесь нужен хелп @TorinAsakura тк я все эти проекты вижу впервые и не знаю какое их ожидает будущее.

**Comment by TorinAsakura** [comment]
Основная проблема - непонятность в процессах и во взаимосвязях, команд может быть много, но если будет понятно, что делает каждая из них - это ок.

Например, чем занимаются команды:
- Serenity
- Phoenix
- Aeterna

Список можно продолжать бесконечно, это ничего не даст как и тупое сокращение количества команд.

# Как я в это вижу

## Кластеры
- сделать кластера: atls, torinasakura, archive

## Стейты
- использовать префиксы как стейт, поясню: так как у фигмы нет никаких элементов для идентификации состояния и всё возложено на ручную писанину - будем использовать префиксы
- prod-, stage-

## Archive
- в Archive помещаем всё, что находится в состоянии консервации и не было запущено в релиз, например для атлантиса это будут: beatster, phoenix, aeterna, poker service analytics (PSA)
- в Archive torinasakura: мастерок 
- Для идентификации принадлежности проектов добавим префиксы atls, ta; например: ta-masterok, atls-beatster

## Prod
- соответственно, всё, что ушло в релиз
- например: prod-misik

## Stage
- то, что в работе
- например: stage-shynnyi-dvor

# Содержимое
## TorinAsakura
- Follow The Compass
- Blondinka Ksu
- Epoch Crysis
- Ghostuhins (Blog - Olga Gostyuhina)
- Torin Asakura
- Шинный Двор
- РФРИТ
- Dream Team
- Misik
- Drum In
- Kinoreporter

## Atlantis
- Atlantis
- Jobs (HR/HRech)
- Academy
- Serenity
- YouThink
- Familia

Tutorials, Banxe - узнай у @dakand что это и куда вообще.

По статусам узнай у @dakand 

Правила нейминга применяй наши: actual-best-naming

**Comment by TFK70** [comment]
@TorinAsakura 

Правильно понимаю, что кластер = команда в фигме?

Я упоминал, что у некоторых проектов есть несколько файлов, например файл с дизайном + JAM со схемой. Если мы все эти файлы скинем в одну большую кучу - мы там не потеряемся в итоге? Как пример - КР:

![image](https://user-images.githubusercontent.com/62806448/181080858-254e4440-4a43-490b-ae5a-efc643d6935d.png)

Причем, я боюсь, что префиксами эту проблему не решить. Такие проекты нужно объединять в кластеры поменьше, иначе все-равно будет каша

**Comment by TorinAsakura** [comment]
Да, предполагается, что кластер = команда, однако тут действительно нужно стратегически подумать, так как фигма вообще ни коим образом не помогает решать подобного рода задачи.

**Comment by TFK70** [comment]
Могу предложить взять твою идею и добавить к ней кластер со схемами

В целом к схемам префиксы prod- и stage- не применимы, они и так не вписываются в основные кластеры

**Comment by TorinAsakura** [comment]
atls, torinasakura, schemes? тогда уж protos, хз, надо начать

попробуй пока на torinasakura попрактиковаться
