### ISSUE TITLE
Обратная связь по Кинорепортёру

### ISSUE THREAD

**Issue by taqyon** [atls/design#62]
Алексей прислал обратную связь в виде нумерованных пунктов. Десятый пункт зачеркнутый, по просьбе @TorinAsakura. 

## Фидбэк

1. Шрифт без засечек! Посмотреть какой есть, предложить варианты (главное, чтобы в старых материалах при перезаливке заменились новые шрифты)

2. Правая колонка в слайдере скролится?

3. Новостей в блоке сайдера нет?

4. Даты материалов на главной не нужны, только внутри материала

5. На главной у картинок три варианта соотношения сторон картинок — много, нужно максимум два, должно коррелироваться с форматами картинок сейчас иначе картинки старых материалов будут отображаться не корректно

6. Плашка "подкаст" — не нужно, меняем на "колонка главного редактора" (нужно сделать, в т.ч. внутреннюю, референс - колонка редактора из журнала https://kinoreporter.ru/glavnyj-redaktor-kinoreportera-mariya-lemesheva-o-prestizhnoj-kinopremii-sobytie-goda-i-budushhem-kinoindustrii/). 
   - Картинка справа - это коллаж или отдельные кликабельные фото? 
   - Формат картинки? Нужно подумать куда лучше в "Основные типы страниц"

7. Под "колонкой главного редактора" блок "рецензии"  - 4 сниппета + скролл или кнопка "ещё" с переходом на страницу рубрики "рецензии"

8. Главная - "рецензии" - убрать, Вместо неё делаем "интервью", размер фото как в "кино/сериалы", 3 колонки х 2 ряда фото+имя+цитата +. кнопка "ещё" с переходом в рубрику "интервью"

9.  Главная — ближайшие премьеры:  писали ранее, что эта рубрика не нужна. 

10. ~~Подписка на рассылку новостей - как реализовано? mailchimp или встроенный в WP плагин? Что за коронавирус на плашке?~~

11. Страница статьи - опять новый формат заходного фото. Как будут отображаться старые материалы? 
Слишком много форматов размера фото, избыточная работа для фоторедактора

12. Article page collection (подборки) - пока нет базы не можем сделать обновление с картинками

13. Article page review (рецензии) - у автора оставляем только имя и фамилию, подложку и регалии не нужен

14. Основные типы страниц - в отдельных категориях должны быть шаблоны "Главный редактор" и "Интервью, ", либо, как обсуждали, чтобы в разные инструменты (имя автора, оглавление и пр.) можно было использовать везде. 

15. Оценку фильму ставит редакция

16. Авторизация только через соцсети, никакой почты/телефона и пр. персональных данных

17. В итоге как формируем базу?

18. График премьер не нужен!

19. Magazine info - В номере (без "новом")

20. Личный кабинет - profile: убрать слово "мои" -  Статьи (не "мои"), Подкасты (не "мои")

**Comment by dakand** [comment]
#### Вопрос 1
> Шрифт без засечек! ...

Это фундаментальная правка. Шрифт - один из самых важных стилеобразующих факторов. Изменив антикву на гротеск в заголовках, мы получим намного более пресный вариант дизайна. В этом можно убедиться взглянув на прототипы.

---

#### Вопрос 2
> Правая колонка в слайдере скролится?

В каком слайдере?

---

#### Вопрос 3
> Новостей в блоке сайдера нет?

В каком блоке сайдера?

---

#### Вопрос 4
> Даты материалов на главной не нужны, только внутри материала

Как вы это представляете? Это неприемлемо для информационного сайта, т.к. дата - базовый элемент для формирования представления о ресурсе. Возьмите 10 информационных порталов и, если из них один будет без дат публикации в превью, то это будет исключением.

---

#### Вопрос 5
> На главной у картинок три варианта соотношения сторон картинок

Если мы говорим про главную страницу, то сейчас разделяю 2 типа: Главный блок в "Подборках" и все остальные. Стоит заметить, что "все остальные" действительно отличаются по соотношению сторон, но это соотношение имеет погрешность до 20%, что равно погрешности при адаптивности элементов. Если вам принципиально, мы можем привести все к одному четкому размеру, но это не сделает блоки красивее, не решит проблему загрузки фото под разные соотношениях, ну и добавит нестабильности в блоки главной страницы и как результат мы получим пробелы между блоками и не гибкое решение.

---

#### Вопрос 6
> Плашка "подкаст" — не нужно, меняем на "колонка главного редактора" ...

Не понимаю как пользователь будет переходить на внутреннюю страницу (референс).
Внутренняя сейчас в рамках страницы материала, так же и оставляем?
Вас не смущает проблема с неймингом? Уже не первый раз вы предлагает поменять названия, удовлетворяющие руководство КР, но не очень понятное для пользователя. Мы можем поменять, не критично, но был должен поинтересоваться. _Результат в мелочах._
**Отвечаю на вопрос:**
1. Это промоблок, внутри анимированные некликабельные изображения.
2. Обе части вопроса не понятны. Уточните.

---

#### Вопрос 7
> Под "колонкой главного редактора" блок "рецензии" - 4 сниппета...

Ок

---

#### Вопрос 8
> Главная - "рецензии" - убрать, Вместо неё делаем "интервью"...

Если мы используем размеры как для обложек фильмов, то 3 колонки закрывают только половину области. Уточните.

---

#### Вопрос 9
> Главная — ближайшие премьеры: писали ранее, что эта рубрика не нужна.

*Справка:
Мы обсуждали необходимость календаря кинопремьер и подборок (по типу Кинопоиска) в рамках обсуждения сущности фильма. Было принято подборки убрать, т.к. они будут реализованы в рамках материала. Календарь кинопремьер было принято оставлять как основную точку входа в фильмы и сериалы. Об этом говорит наличии ваших неоднократных комментариев по поводу улучшения данного блока в прототипах и присутствие данного блока в дизайне мобильной версии и отсутствие комментариев касательно неактуальности данного блока.

---

#### Вопрос 11
> Страница статьи - опять новый формат заходного фото. Как будут отображаться старые материалы?
Не понимаю проблемы. Все изображения для материалов имеют горизонтальную ориентацию, хоть и разные разрешения. Достаточно загрузить одну хайрез фотографию для страницы статьи и для её превью. В зависимости от того какую фотографию вы загрузите,  изображение будет пропорционально скейлиться. Сейчас в дизайне мы специально добавили уникальные фотографии для каждого блока, чтобы вы могли увидеть как это будет работать.

---

#### Вопрос 12
> Article page collection (подборки) - пока нет базы не можем сделать обновление с картинками

Про какую базу идёт речь. Это страница подборки, которая формируется вручную редактором. Мы отказались от идеи подборок как у КП по вашей инициативе.

---

#### Вопрос 13
> Article page review (рецензии) - у автора оставляем только имя и фамилию, подложку и регалии не нужен

Регалии уберём. Подложку то почему убрать?)))

---

#### Вопрос 14
> Основные типы страниц - в отдельных категориях должны быть шаблоны "Главный редактор" и "Интервью...

Какие особенности будут иметь эти шаблоны?

---

#### Вопрос 15
> Оценку фильму ставит редакция

Всё верно. Если этот комментарий в сторону блока "Оцените фильм", то мы это уже обсуждали. Блок стоит оставить.

---

#### Вопрос 16
Авторизация только через соцсети, никакой почты/телефона и пр. персональных данных

Можем реализовать, тогда логично убрать всю историю с персональными данными для покупки журнала. Убираем?

_Отдельно от ответа: @sorokoumov @taqyon @TorinAsakura как считаете делать только черз соц. сети правильно?_

---

#### Вопрос 17
> В итоге как формируем базу?

_Отдельно от ответа: @TorinAsakura ты грамотнее ответишь как будем парсить это._

---

#### Вопрос 18
> График премьер не нужен!

Ранее отвечал

---

#### Вопрос 19
> Magazine info - В номере (без "новом")

Ок

---

#### Вопрос 20
> Личный кабинет - profile: убрать слово "мои" - Статьи (не "мои"), Подкасты (не "мои")

Ок

**Comment by TorinAsakura** [comment]
16. Однозначно нет. Это бред.
17. Уже ответил в личном разговоре. Продублирую резюме: они составляют список тайтлов, мы их парсим, сериализуем под формат ВП, они модерируют через админку = профит | изи катка.

**Comment by taqyon** [comment]
Я не туда свои писульки отправил :| 

---

### 1. Шрифт без засечек! Посмотреть какой есть, предложить варианты (главное, чтобы в старых материалах при перезаливке заменились новые шрифты)

- Вопрос не принципиальный
- Нужны обоснования, для главного редактора

### 2. Правая колонка в слайдере скролится?

Нет не скролится

### 4. Даты материалов на главной не нужны, только внутри материала

 **Что решили?** 

Алексей переговорит с руководством с целью узнать, возможен ли компонент.

### 5. На главной у картинок три варианта соотношения сторон картинок — много, нужно максимум два, должно коррелироваться с форматами картинок сейчас иначе картинки старых материалов будут отображаться не корректно


**Что решили?** Не принимается. 

### 6. Плашка "подкаст" — не нужно, меняем на "колонка главного редактора" (нужно сделать, в т.ч. внутреннюю, референс - колонка редактора из журнала [kinoreporter.ru/glavnyj-redaktor-kinoreportera-mariya-lemesheva-o-prestizhnoj-kinopremii-sobytie-goda-i-budushhem-kinoindustrii](https://kinoreporter.ru/glavnyj-redaktor-kinoreportera-mariya-lemesheva-o-prestizhnoj-kinopremii-sobytie-goda-i-budushhem-kinoindustrii/).
    
- Картинка справа - это коллаж или отдельные кликабельные фото
- Формат картинки? Нужно подумать куда лучше в "Основные типы страниц"


**Что решили?** Сделать альтернативный блок. Рабочее название — Колонка главного редактора. 

### 7. Под "колонкой главного редактора" блок "рецензии" - 4 сниппета + скролл или кнопка "ещё" с переходом на страницу рубрики "рецензии"


#### Что решили? 

##### Рецензии

[Kinoreporter | Web-site – Figma](https://www.figma.com/file/pUWwcuHo61RiwLEzNztoGZ?node-id=1227:37881#241659346)

- Сделать горизонтальный скролл в блоке рецензии
- Добавить картинки к рецензиям
- Поднять рецензии

### 8. Главная - "рецензии" - убрать, Вместо неё делаем "интервью", размер фото как в "кино/сериалы", 3 колонки х 2 ряда фото+имя+цитата +. кнопка "ещё" с переходом в рубрику "интервью"

**Что решили?** Обсуждение с редакцией

### 9. Главная — ближайшие премьеры: писали ранее, что эта рубрика не нужна.

**Что решили?** Упраздняем. Потому что мы физически это не сможем делать. 

### 12. Article page collection (подборки) - пока нет базы не можем сделать оглавление с картинками

**Что решили?** Вопрос не принципиальный

### 13. Article page review (рецензии) - у автора оставляем только имя и фамилию, подложку и регалии не нужен

**Что решили?** Решили на ходу

### 14. Основные типы страниц - в отдельных категориях должны быть шаблоны "Главный редактор" и "Интервью, ", либо, как обсуждали, чтобы в разные инструменты (имя автора, оглавление и пр.) можно было использовать везде.

**Что решили?**

- Виджет для подборки: жестко зафиксированный, менять можно только содержания

### 15. Оценку фильму ставит редакция

**Что решили?** 

- Оставить
- Поменять цвет плашки оценки КП

### 16. Авторизация только через соцсети, никакой почты/телефона и пр. персональных данных

**Что решили?**

- Оставляем регистрацию только через социальные сети
- Добавить авторизацию через соц сети

**Comment by taqyon** [comment]
>Алексей переговорит с руководством с целью узнать, возможен ли компромисс.

Возможен. Ставим везде, также используем булавку для закрепленных.

**Comment by bbbaso** [comment]
@dakand отработал комменты

**Comment by dakand** [comment]
> @dakand отработал комменты

@bbbaso оставил комментарии, нужно исправить. Ещё момент касательно покупки журнала. Полагаю, я сам тут тебе немного лишнего сказал. У нас покупка журнала будет возможно и чекаут нужно вернуть. Просто это не будет в рамках ЛК, т.е. даже не авторизованный пользователь сможет купить журнал и мы не привязываем его данные к ЛК.

**Comment by bbbaso** [comment]
@dakand отработал комменты, чекни как сможешь

**Comment by taqyon** [comment]
@TorinAsakura @dakand чё может грохнем тикет?
