### ISSUE TITLE
Заглушка для сайта

### ISSUE THREAD

**Issue by dakand** [atls/design#65]
[Здесь](https://www.figma.com/file/3CJjy7HyIrmA3wLPHVxPdh/Website?node-id=0%3A1) есть референсы и первые концепты.

@bbbaso  Мне нравится:
- Реф Advanced Team
- Verdana в заголовке

Мне не нравится:
- Сильный контраст элемента и фона
- Оттенок в целом. Хочется что-то более дружелюбного.
- Формулировка заголовка. Кнопка нужна в целом, но для единственного заголовка нужно придумать что-то более продвинутое. Какой-то заголовок, который отражает нашу концепцию/уникальность/рабочие проекты.

P.S. Давай для РУ изначально всё делать.

**Comment by dakand** [comment]
@bbbaso давай сначала спроектируем страницу без элемента на фоне, но с фоновым оттенком, который после будем юзать для создания модели.

**Comment by bbbaso** [comment]
@dakand закинул новые варианты

Verdana скорее всего мимо, потому что с 3дшкой на фоне нужен более геометрический гротеск

**Comment by dakand** [comment]
> @dakand закинул новые варианты
> 
> Verdana скорее всего мимо, потому что с 3дшкой на фоне нужен более геометрический гротеск

Оставил комменты
