### ISSUE TITLE
Обложки проектов

### ISSUE THREAD

**Issue by dakand** [atls/design#67]
@bbbaso Артём уже делал [обложки](https://www.figma.com/file/0UpfeaaX2PKRq9xKHl3ULt/Project-Covers?node-id=2%3A12). Мы их оставим для сайта. Но нам сейчас для других площадок нужно сделать обложки/шоты по шаблону.

Например, вот тут шоты Андрея выглядят мусорно, т.к. в превью они маленькие, разные и стоят рядом. А у чела сверху оно лучше выглядит. Вот нужно сделать как у него, но лучше ( у него древние мокапы).
![telegram-cloud-document-2-5193074549918278163](https://user-images.githubusercontent.com/75856342/185856819-6e043b04-12b7-4185-96ed-a5de0eea4e78.jpg)

**Comment by bbbaso** [comment]
@dakand нам нужны только 3 показательные обложки или для всех проектов?

**Comment by dakand** [comment]
> @dakand нам нужны только 3 показательные обложки или для всех проектов?

Одна обложка - один проект. Обложки по тем проектам, которые есть по ссылке.

**Comment by bbbaso** [comment]
@dakand есть пока первый [вариант](https://www.figma.com/file/0UpfeaaX2PKRq9xKHl3ULt/Project-Covers?node-id=154%3A4248) (мб даже удачней будет), чтобы совсем обложки не были однообразными

**Comment by TorinAsakura** [comment]
@bbbaso Это всё равно мусорка. Разные фоны/цвета. Нужен общий темплейт

**Comment by bbbaso** [comment]
@dakand добавил [варианты](https://www.figma.com/file/0UpfeaaX2PKRq9xKHl3ULt/Project-Covers?node-id=2%3A12)

**Comment by dakand** [comment]
> @dakand добавил [варианты](https://www.figma.com/file/0UpfeaaX2PKRq9xKHl3ULt/Project-Covers?node-id=2%3A12)

Вариант с заголовоком вверху ниче такой. Но это не то что нам нужно. У нас шаблон заголовок - изображение. Но у нас все изображения должны быть по шаблону. Т.е. мы в каждом шоте показываем интерфейс. Т.е. у нас на Русатоме не может быть 3д модели, нужен интерфейс.

**Comment by bbbaso** [comment]
@dakand обновил варианты, сохранил шаблонность, только вот у Русатома мало что привлекательного в интерфейсе, поэтому оставил там один из экранов с 3д

**Comment by TorinAsakura** [comment]
@bbbaso У русатома потрясающий хиро в кейсе

**Comment by bbbaso** [comment]
> Т.е. мы в каждом шоте показываем интерфейс. Т.е. у нас на Русатоме не может быть 3д модели, нужен интерфейс.

@TorinAsakura от Сани коммент был

**Comment by bbbaso** [comment]
@TorinAsakura добавил [обложки](https://www.figma.com/file/0UpfeaaX2PKRq9xKHl3ULt/Project-Covers?node-id=189%3A5947) в 2 вариантах 

_*отметишь проекты, в которых год неверный, поправлю (не было инфы)_

**Comment by TorinAsakura** [comment]
> @TorinAsakura добавил [обложки](https://www.figma.com/file/0UpfeaaX2PKRq9xKHl3ULt/Project-Covers?node-id=189%3A5947) в 2 вариантах
> 
> _*отметишь проекты, в которых год неверный, поправлю (не было инфы)_

безусловно второй вариант, а годы я и сам поправить могу, всё ок, пакуй

**Comment by bbbaso** [comment]
@TorinAsakura тебе их джипегами кинуть?

**Comment by TorinAsakura** [comment]
> @TorinAsakura тебе их джипегами кинуть?

боги, зачем? я сам прекрасно с фигмой работаю) Спасибо)
