### ISSUE TITLE
Армянские тачки

### ISSUE THREAD

**Issue by taqyon** [atls/design#68]
### 7. Какие юридические особенности (процедуры) ждут клиента?

**Comment by TorinAsakura** [comment]
1. Нет
2. Нет
3. Сарафанка

**Comment by taqyon** [comment]
@TorinAsakura это вопросы для чувака

**Comment by TorinAsakura** [comment]
> @TorinAsakura это вопросы для чувака

это мой хороший товарищ, и я немного в теме, поэтому сразу тебе дал ответы

**Comment by taqyon** [comment]
Пока ничего нет и ничего вытащить не получится
