### ISSUE TITLE
Обложка ТА

### ISSUE THREAD

**Issue by dakand** [atls/design#69]
@ArtemHovsky отвелкись плз от iHeal. 
Нужно обложку, которую ты делал для ТА адаптировать под обои для мобильных устройств.
Так же давай сделаем аватар (квадратный), на котором будет гораздо меньше деталей, но нужно будет оставить силуэт самурая - можно сделать вариант где самурай в полный рост и вариант где самурай кадрирован иначе (по бедра или по пояс)

**Comment by ArtemHovsky** [comment]
![image](https://user-images.githubusercontent.com/103929181/187192792-9464a699-20e5-49dd-923a-5f04058568ce.png)

Под какое разрешение экрана делать адаптив?

**Comment by dakand** [comment]
> ![image](https://user-images.githubusercontent.com/103929181/187192792-9464a699-20e5-49dd-923a-5f04058568ce.png)
> 
> 
> 
> Под какое разрешение экрана делать адаптив?

Под макс

**Comment by ArtemHovsky** [comment]
@TorinAsakura 
Добавил варианты обоев и аватары. Посмотри пожалуйста

**Comment by ArtemHovsky** [comment]
@TorinAsakura 
Внес правки, доработал варианты
Проверь пожалуйста варианты обоев и аватары

**Comment by dakand** [comment]
@bbbaso нужна помощь. Есть аватарки с самураем и он в растре не в самом лучшем качестве. Нужно перевести в вектор = трассировать изображение. Я обычно трассирую в люстре, но в фигме есть плагин для трассировки (правда я его не юзал).

**Comment by bbbaso** [comment]
@dakand, есть проблема, т.к. люстра автоматом добавляет белый бг при трассировке, элементы вокруг самурая меняют цвет + их просто становится больше

Я покрутил настройки, но качество не сильно улучшается. Растр скруглился, но ,опять же, разницы большой нет 

Лежит [тут](https://www.figma.com/file/yMAHxd8CkCh1BIYGFqzDIn/Banner?node-id=498%3A21402)

_P.s. Фигма не справилась толком_

**Comment by TorinAsakura** [comment]
@bbbaso Ром, основные тезисы для этой задачи следующие:
- объекты должны быть в векторе или в хайрезе, чтобы при скейлинге не было эффекта "мыла"
- ковры должны быть для десктопа, таблетки, мобилы
- объекты на лок скрине не должны пересекаться с элементами интерфейса
- объекты на хоум скрине должны быть минимализированны (как вариант мы рассмотрели или солнце, или калиграфию)

Подход очень простой: оно должно выглядеть хорошо, нужно всё проверить и уже потом сдавать, чтобы я потом не бегал и не занимался микроменеджментом который я так не люблю

**Comment by bbbaso** [comment]
@TorinAsakura 
Стоп, я понял что нужен самурай в векторе для аватарок. И к слову, зачем мне трассировать его, если у нас он уже есть в векторе на странице Banner? (только обнаружил это)

Не понимаю откуда тезисы про обложки для девайсов и обьекты на скринах?

**Comment by TorinAsakura** [comment]
> @TorinAsakura Стоп, я понял что нужен самурай в векторе для аватарок. И к слову, зачем мне трассировать его, если у нас он уже есть в векторе на странице Banner? (только обнаружил это)
> 
> Не понимаю откуда тезисы про обложки для девайсов и обьекты на скринах?

А что тебе не понятно? Я это буду паблить в воллпаперные стоки для мобильных девайсов и оформлю страничку на личном сайте для скачивания. Это должен быть полноценный wallpaper set.

Так яснее?

**Comment by bbbaso** [comment]
@TorinAsakura ну тк задача про трассировку, поэтому не понял для чего мне инфа о скринах и обложках

**Comment by TorinAsakura** [comment]
> @TorinAsakura ну тк задача про трассировку, поэтому не понял для чего мне инфа о скринах и обложках

Предвижу, что лучше тебе закончить начатую работу.

**Comment by dakand** [comment]
@bbbaso разобрались или остались актуальные вопросы?

**Comment by TorinAsakura** [comment]
@dakand всё норм, работаем

**Comment by bbbaso** [comment]
под какой IPad делаем обложку?

![image](https://user-images.githubusercontent.com/103942572/188472623-666bc120-195d-4abc-bc19-1ba0d3818ab2.png)

**Comment by TorinAsakura** [comment]
> под какой IPad делаем обложку?
> 
> ![image](https://user-images.githubusercontent.com/103942572/188472623-666bc120-195d-4abc-bc19-1ba0d3818ab2.png)

Ну, как я это вижу: сделать сцену побольше, чтобы было позволительно сжирать пространство на кроппинг, и делать от 1536, а для Mini, я полагаю, сойдёт вариант для iPhone

**Comment by bbbaso** [comment]
Добавил аватары: 400px и 800px, перевел самураев в вектор
Добавил ковры для айапада (композицию немного подправил под горизонтальный вариант, чтобы проще кропалась сама обложка по вертикали)

_*для десктопа, как я понял, уже все есть_

Все[ тут](https://www.figma.com/file/yMAHxd8CkCh1BIYGFqzDIn/Banner?node-id=147%3A2)

**Comment by TorinAsakura** [comment]
![IMG_0004](https://user-images.githubusercontent.com/3940885/189290732-8aefcbd9-bfc4-481b-8e37-7b4bb0ad8fc9.PNG)
![IMG_0005](https://user-images.githubusercontent.com/3940885/189290776-a3ad49b1-3b8d-4fb7-8fc5-46afe4b3c51c.PNG)
![IMG_0006](https://user-images.githubusercontent.com/3940885/189290781-19a53b80-3a2c-481d-bce3-38cedc04a035.PNG)
![IMG_0007](https://user-images.githubusercontent.com/3940885/189290788-5a9c67b4-e10d-401d-a132-f576553eda53.PNG)

**Comment by TorinAsakura** [comment]
@bbbaso везде проверил, меня не глючит, это артефакт статичен, что при выгрузке, что при генерации HEIC, надо понять откуда он появляется

![IMG_2957](https://user-images.githubusercontent.com/3940885/190856598-bca8191f-2d14-4542-859c-7d6b70b49a2b.jpeg)

В QHD разрешении (2560) на экране не помещаются иероглифы

![Снимок экрана 2022-09-17 в 15 26 17](https://user-images.githubusercontent.com/3940885/190856649-2cd193e5-0ef7-49e4-876c-67db0aef2ef8.png)

**Comment by bbbaso** [comment]
> везде проверил, меня не глючит, это артефакт статичен, что при выгрузке, что при генерации HEIC, надо понять откуда он появляется

Возможно вектор моросит при экспорте. Поправил, проверь как сможешь.

> В QHD разрешении (2560) на экране не помещаются иероглифы

Поправил (он почему-то в высоту был 1080 вместо 1440)
[Ссылка на обложку](https://www.figma.com/file/yMAHxd8CkCh1BIYGFqzDIn/Banner?node-id=532%3A8185)
