### ISSUE TITLE
Баннер для Torin Asakura (by the Bushido)

### ISSUE THREAD

**Issue by TorinAsakura** [atls/design#7]
## Баннер для Torin Asakura
Это бренд Андрея - под ним он и музыку пишет и код пишет. Ему нужен новый баннер. Его лого выглядит [так](https://www.figma.com/file/wC1teRe7FsrQqWGAliXtQF/All-Identity?node-id=305%3A9). Нам нужно сделать баннер в самурайском стиле с рванными красками ([пример](https://www.pinterest.ru/pin/372039619229396893/) и [пример](https://www.pinterest.ru/pin/488640628327356583/)). Баннер сделаем пока 1920 х 1080, потом будем тянуть под сервисы. Поэтому делай в фигме.

**Comment by TorinAsakura** [comment]
Свежий реф к моему баннеру 
![image](https://user-images.githubusercontent.com/3940885/162005621-cdf48919-7a87-4efb-8fb8-6b903a890f5c.png)

**Comment by dakand** [comment]
@ArtemHovsky найди время на неделе для этого

**Comment by ArtemHovsky** [comment]
Фигма:
https://www.figma.com/file/yMAHxd8CkCh1BIYGFqzDIn/Banner?node-id=2%3A3

**Comment by TorinAsakura** [comment]
@ArtemHovsky Ты же понимаешь, что это баннер для меня?) Это для бренда Torin Asakura

**Comment by TorinAsakura** [comment]
@ArtemHovsky https://www.figma.com/file/yMAHxd8CkCh1BIYGFqzDIn/Banner?node-id=20%3A2
1. Закат
2. на фоне заката Самурай
3. Частицы и всякие дисторшн/рип эффекты можешь раскидать на своё, сугубо "творческое" ощущение

**Comment by ArtemHovsky** [comment]
@TorinAsakura @dakand 
Посмотрите пожалуйста новый вариант после правок

**Comment by ArtemHovsky** [comment]
@TorinAsakura 
Внес правки, посмотри пожалуйста

**Comment by TorinAsakura** [comment]
> @TorinAsakura
> Внес правки, посмотри пожалуйста

Посмотрел. Свои комменты закрыл. В целом годно, но, слева, там где я опустошил пространство, я хочу сделать надписи. Нужно будет некоторое время чтобы правильно их составить на Като. Позже отпишусь сюда же.

**Comment by TorinAsakura** [comment]
@ArtemHovsky всегда к баннерам делай ещё аватарки комплектом, а то будет странно смотреться аватарка в стиле ретровейр и баннер бусидо https://vk.com/ta_pub

**Comment by TorinAsakura** [comment]
Ещё у нас есть файл со всеми айдентити, и там есть размеры под все значимые соц. сети, их тоже надо соблюсти, так как наш баннер очень сильно режется в том же вк

**Comment by ArtemHovsky** [comment]
Этот файл с размерами для соцсетей?
https://www.figma.com/file/fUiLb9kOkJhBJrWhEtkYF8/Projects-identity?node-id=2%3A153

И под какие соцсети делать баннера и аватары?

**Comment by TorinAsakura** [comment]
@ArtemHovsky Да, это он.
Для тех же.

**Comment by TorinAsakura** [comment]
Сделал калиграфию в мид-резе, надо векторизовать https://disk.yandex.ru/d/yWMAoY_Iegf_NQ
Вот в какой последовательности оно должно быть
![n7B8CSlQ6z_mE0Xn6AJz3VCCYPsWJ7ZX3Qmn7-zvZzO94p51AtDWkOTCC2J6DisrbASLD932lOopf3msfp_gokwS](https://user-images.githubusercontent.com/3940885/171987390-1d6d7edd-198c-4fe9-b5b2-da588cc742e2.jpg)

**Comment by dakand** [comment]
@ArtemHovsky нужно поработать с иероглифами. По-хорошему в иллюстраторе их нужно трассировать, чтобы у нас в запасе был вектор. Ну и добавь их в баннеры потом. Сделай это после YT.

**Comment by ArtemHovsky** [comment]
Перевел в вектор. Посмотрите качество
https://www.figma.com/file/yMAHxd8CkCh1BIYGFqzDIn/Banner?node-id=96%3A6

**Comment by dakand** [comment]
Давай дырки внутри уберем, ща комменты оставлю где

**Comment by ArtemHovsky** [comment]
Сделал

**Comment by TorinAsakura** [comment]
Новый размер для Ultimate Guitars 2172x560px

**Comment by ArtemHovsky** [comment]
@TorinAsakura 
Добавил на баннер, посмотри вариант

**Comment by TorinAsakura** [comment]
> @TorinAsakura
> Добавил на баннер, посмотри вариант

https://www.figma.com/file/yMAHxd8CkCh1BIYGFqzDIn?node-id=108:2#208640743

**Comment by TorinAsakura** [comment]
Новый размер для Kwork 1920x226px

**Comment by ArtemHovsky** [comment]
@TorinAsakura 
Посмотри пожалуйста вид и вариант стилизации

**Comment by TorinAsakura** [comment]
@ArtemHovsky Ты зачем-то три слова превратил в два.

**Comment by ArtemHovsky** [comment]
Сейчас все правильно?
Распространяем такой вид на все баннера?

**Comment by TorinAsakura** [comment]
@ArtemHovsky Да. Жду размеры.

**Comment by TorinAsakura** [comment]
@ArtemHovsky Аватар кстати тоже стилизуй пожалуйста, чтобы там не тупо цвет был, но и художественные деформации, так сказать, для поддержания образа.

**Comment by TorinAsakura** [comment]
@ArtemHovsky Обводку у баннера можно убрать, а фон деформировать в соответствии с баннером

**Comment by ArtemHovsky** [comment]
@TorinAsakura 
Готово.
Померяй аватарки по размеру знака, чтобы хорошо подходил

**Comment by TorinAsakura** [comment]
Всё ок. Забрал.

**Comment by TorinAsakura** [comment]
Facebook не заходит
![Снимок экрана 2022-06-11 в 00 14 17](https://user-images.githubusercontent.com/3940885/173152139-7a37c8e6-130c-47f3-95b2-9be2ab19bfcf.png)

https://www.facebook.com/help/125379114252045 - требования (размеры можно брать х4 сходу)
Сам не смог изменить размер без боли, сделайте что-нибудь с этим или сделайте мне гайд

**Comment by TorinAsakura** [comment]
Окантовку аватару нужно вернуть, выглядело намного лучше.

На будущее, такие вещи лучше версионировать, а то ты получается всё старое посносил, новое оставил и теперь даже примерить нельзя, только по версиям откатываться.

@dakand на контроль возьми пожалуйста

**Comment by TorinAsakura** [comment]
Ещё хочу обратить внимание, на то, что размеры аватара походу изменились. Так как первоначальная версия идеально подходила соц. сетям, а текущую версию приходится редактировать.

**Comment by dakand** [comment]
> https://www.facebook.com/help/125379114252045

Напомни для мобилки в фб есть возможность загрузить обложку отдельно?

**Comment by TorinAsakura** [comment]
> > https://www.facebook.com/help/125379114252045
> 
> 
> 
> Напомни для мобилки в фб есть возможность загрузить обложку отдельно?

Не-а

**Comment by dakand** [comment]
> Ещё хочу обратить внимание, на то, что размеры аватара походу изменились. Так как первоначальная версия идеально подходила соц. сетям, а текущую версию приходится редактировать. ![Снимок экрана 2022-06-11 в 00 20 49](https://user-images.githubusercontent.com/3940885/173152920-0a3f7afe-9895-4b0e-b2d3-2726195d7adf.png) ![Снимок экрана 2022-06-11 в 00 21 00](https://user-images.githubusercontent.com/3940885/173152925-491988c9-cf4d-4f6f-abb2-cd9f743e27ec.png)

Минимальный размер тот же. Я проверил - эта область вначале по дефолту никак не зависит от разрешения загружаемой миниатюры. Придётся тянуть.

**Comment by TorinAsakura** [comment]
Всё равно оставьте две версии, тем более мне не понравилось как выглядит новая

**Comment by dakand** [comment]
> Окантовку аватару нужно вернуть, выглядело намного лучше.
> 
> На будущее, такие вещи лучше версионировать, а то ты получается всё старое посносил, новое оставил и теперь даже примерить нельзя, только по версиям откатываться.
> 
> @dakand на контроль возьми пожалуйста

@ArtemHovsky перенеси все сайзы в один проект. Добавь на странице с сайзами одну или несколько колонок, где расположи аналогичные варианты, которые делал до (про которые пишет Андрей).

**Comment by dakand** [comment]
@TorinAsakura [тут](https://www.figma.com/file/fUiLb9kOkJhBJrWhEtkYF8/Projects-identity?node-id=601%3A1009) два варианта, попробуй оба и чекни мобилку обязательно (но скорее всего второй подойдет).

**Comment by TorinAsakura** [comment]
> @TorinAsakura [тут](https://www.figma.com/file/fUiLb9kOkJhBJrWhEtkYF8/Projects-identity?node-id=601%3A1009) два варианта, попробуй оба и чекни мобилку обязательно (но скорее всего второй подойдет).

Встало очень хорошо. Спасибо дружище. https://www.facebook.com/TorinAsakura

**Comment by TorinAsakura** [comment]
> Всё равно оставьте две версии, тем более мне не понравилось как выглядит новая

И тут шла речь об аватаре. Ну какой смысл оставлять версию, которая не подходит?

**Comment by dakand** [comment]
@ArtemHovsky посмотри как правильно оформить обложку для ютуба. Разрешение у тебя правильное, а позиционирование внутри нет, т.к. с десктопа будет люто заскейлено.

**Comment by ArtemHovsky** [comment]
Стары варианты аватарок остались в скрытых

**Comment by TorinAsakura** [comment]
> Стары варианты аватарок остались в скрытых

Я их не вижу. Где?
![Снимок экрана 2022-06-12 в 12 02 06](https://user-images.githubusercontent.com/3940885/173225673-585d114e-c9b1-4b73-8f2b-9e55e8de897c.png)

**Comment by dakand** [comment]
> Стары варианты аватарок остались в скрытых

Все сайзы должны быть в [этом](https://www.figma.com/file/yMAHxd8CkCh1BIYGFqzDIn/Banner?node-id=108%3A2) проекте, а у тебя они в [этом](https://www.figma.com/file/fUiLb9kOkJhBJrWhEtkYF8/Projects-identity?node-id=516%3A2).
Верни варианты автатарок из скрытых и расположи их как я описывал выше.

**Comment by ArtemHovsky** [comment]
![image](https://user-images.githubusercontent.com/103929181/173225772-1cf1c9e6-7c03-491a-a1fc-2169e7ce3836.png)

**Comment by TorinAsakura** [comment]
> ![image](https://user-images.githubusercontent.com/103929181/173225772-1cf1c9e6-7c03-491a-a1fc-2169e7ce3836.png)

Мне зачем этот сайдбар? Я должен работать с центральной областью, мне нужны только изображения. Ты не для дизайнеров делаешь, а для дальнейшего потребления и делать должен, чтобы тем, кто будет это потреблять - было удобно.

**Comment by ArtemHovsky** [comment]
Перенес, поправил, добавил

**Comment by dakand** [comment]
Переоткрою задачу на время. @ArtemHovsky как будет время - сделай инвертированную (тёмную) версию. Сначала сделай на примере одно баннера, пингани меня и Андрея. Только потом под сайзы будем делать.

**Comment by TorinAsakura** [comment]
@ArtemHovsky Оставил комменты.
@dakand присоединишься?

**Comment by dakand** [comment]
@ArtemHovsky получилось эффектно. Но с комментами Андрея я согласен. Надо чуть светлее. При чём я не знаю как будет лучше фон сделать ещё светлее, чем объекты на переднем плане или наоборот фон затемнить, а объекты затемнить. Но так или иначе контраста немного побольше. И иероглифы я бы сделал посветлее.

**Comment by ArtemHovsky** [comment]
@TorinAsakura 
А что это значит, что сделать?
![image](https://user-images.githubusercontent.com/103929181/176399395-d96dbd88-9745-4d51-a749-2cb0c74f01ee.png)

**Comment by TorinAsakura** [comment]
> @TorinAsakura
> А что это значит, что сделать?
> ![image](https://user-images.githubusercontent.com/103929181/176399395-d96dbd88-9745-4d51-a749-2cb0c74f01ee.png)

это я расставил тебе акценты, башня называется пагодой, а строение рядом называется Додзе

**Comment by ArtemHovsky** [comment]
@TorinAsakura 
Посмотри пожалуйста измененный вариант

**Comment by TorinAsakura** [comment]
Аранж в порядке. Не хватает разрешения, нужно делать 4-8к

**Comment by TorinAsakura** [comment]
@ArtemHovsky я понял в чём дело - в белой версии не разрешение другое, там аранж объектов другой, обрати на это внимание пожалуйста

**Comment by TorinAsakura** [comment]
Пожалуйста, не "поднимай" так сильно землю, в оригинальной версии она выглядит отлично, а тут очень выпукло

**Comment by ArtemHovsky** [comment]
По поводу качества ни чем не могу помочь. Изначально все элементы сделаны из растрового изображения

**Comment by TorinAsakura** [comment]
> По поводу качества ни чем не могу помочь. Изначально все элементы сделаны из растрового изображения

Почему не можешь ничем помочь? Тут растр не сложный, его вполне можно векторизовать.

**Comment by TorinAsakura** [comment]
@ArtemHovsky Это необходимо, так как я буду делать macOS Dynamic Wallpaper, для этого мне нужно будет их перевести в HEIC и после специальным вызовом из API собрать. Не хочу тратить столько времени на мыло. Идея всем зашла, концепция получилась, осталось это дотьюнить до хайреза.

**Comment by ArtemHovsky** [comment]
Понял. Возьмем в работу

**Comment by ArtemHovsky** [comment]
@TorinAsakura 
Сделал векторный вариант баннера, посмотри качество
https://www.figma.com/file/yMAHxd8CkCh1BIYGFqzDIn/Banner?node-id=232%3A2

**Comment by TorinAsakura** [comment]
@ArtemHovsky 

https://user-images.githubusercontent.com/3940885/176668857-26d8d003-0857-4101-9476-af8f376c8458.mov


https://user-images.githubusercontent.com/3940885/176668869-2e89daa3-f634-409f-bdd9-675b01e57464.mov

**Comment by TorinAsakura** [comment]
@dakand Это одно и то же изображение на разных мониторах. Что белая что тёмная, они разные

**Comment by dakand** [comment]
Сорри парни, что так поздно.  @ArtemHovsky нужно баннер, который Андрей ставит на рабочий стол растянуть на 2560px (макет оставил). Я хотел сам, но видимо ты в люстре делал и в фигме свг получается невозможный для редактирования. Цвета кайф, мне кажется получилось просто охиренно. По итогу нам нужно:
1. Сделать векторный банер 2560x1080 темный и белый. Обрати внимание, что иероглифы должны будут видны и при 1920, поэтому их положение по оси X не  нужно смещать, а вот по Y я бы по центру поставил.
2. Сделать баннеры для всех соц. сетей аналогично светлой теме. Здесь как и в светлой теме используй растр, так легче будет редактироват в дальнейшем.

Я думаю, что на всё на это не должно уйти больше двух часов, поэтому давай в начале рабочего дня всё допилим.

**Comment by ArtemHovsky** [comment]
Добавил векторные варианты и все соц. сети темную версию

**Comment by TorinAsakura** [comment]
> Добавил векторные варианты и все соц. сети темную версию

оставил комменты

попробуй поставить сам и посмотреть

@dakand - это на яблочном мониторе с разрешением 2560х1440
![Снимок экрана 2022-07-02 в 00 50 07](https://user-images.githubusercontent.com/3940885/176971645-8300369c-ad54-44e4-9e3f-0c5fe985c265.png)

Я говорил, что разрешение лучше делать 4к

**Comment by dakand** [comment]
@ArtemHovsky 2560x1080 ок - правильный размер, вектор. 1920x1080 почему в растре? Я же написал в предыдущем комменте, чтобы позиционирование иероглифов было одинаковое, чтобы заставку 21:9, можно было применять к 16:9. Ты решил сделать два отдельных - я только за, но давай тогда уж оба сделаем векторных. 
@TorinAsakura я бы написал что ты мог бы экспортнуть x1.5, но т.к. у нас основной банер в растре изменится только разрешение, а качество будет недостаточным.

**Comment by ArtemHovsky** [comment]
Добавил векторный вариант баннера 1920

**Comment by TorinAsakura** [comment]
> Добавил векторный вариант баннера 1920

Проверь пожалуйста светлую версию, там какие-то артефакты по краям идут. В остальном - можно забирать я думаю. Внеси последние фиксы и я буду их уже в HEIC переводить.

Не забудь пожалуйста про 4к версию, это важно.

**Comment by ArtemHovsky** [comment]
Исправил баги
Добавил размер 4к

**Comment by dakand** [comment]
@TorinAsakura закрываем?

**Comment by TorinAsakura** [comment]
+
