### ISSUE TITLE
2022-30-08 Разведка — Radio Record

### ISSUE THREAD

**Issue by taqyon** [atls/design#70]
# 2022-30-08 Разведка — Radio Record

|    Дата    | Кто предоставляет информацию | Цель                                                                            |
|:----------:| ---------------------------- | ------------------------------------------------------------------------------- |
| 2022-30-08 | [[@Верди Атибайеба]]         | Понять текущее состояние работы, собрать информацию для предварительной оценки | 

Позвонил [[@Андрей Гостюхин]] и сообщил что с ним связался представитель Radio Record – [[@Верди Атибайеба]], который сообщил Андрею о том, что у сайта всё плохо с back end'ом. 

#### Входная информация со стороны [[@Верди Атибайеба]]: 

- a. Работа с пользователями
	- i. Добавление / удаление / редактирование
	- ii. Группы по возможностям
- b. Сервис отправки почтовых уведомлений
	- i. Добавление пользователей в список рассылки согласно параметрам
	- ii. Планировщик
- c. Кастомные свойства для всех типов элементов
- d. Радиоканалы (добавление / удаление / редактирование)
- e. Треки (добавление / удаление / редактирование)
- f. Плейлисты
	- i. Добавление / удаление / редактирование
	- ii. Добавление / удаление треков в плейлисты
- g. События
- h. Туры / Фесты / акции
	- i. Добавление/редактирование/удаление
	- ii. Присоединение событий
- i. Новости
- j. Города
- k. Чарты
	- i. Добавление / редактирование / удаление
	- ii. Присоединение событий
- l. Статические странички
- m. Сервис отправки пуш уведомлений
	- i. Добавление пользователей в список рассылки согласно параметрам
	- ii. Планировщик

## Интервью

[[@Верди Атибайеба]] — Руководитель разработки [Radio Record — слушать онлайн](https://www.radiorecord.ru/), поддержка сайта, отвечает за решения на продукте. 

### Проблема

- Есть ресурс: [Radio Record — слушать онлайн](https://www.radiorecord.ru/)
- Функционально работает, в каком-то виде
- Ресурс начинался не совсем корректно (работает на 1С Битриксе)
- К Битриксу прикручена есть прослойка авторизации через соц сети (кастомная) — **Ключевой болевой момент**
- Есть админка Битрикса для управления контентом и при этом есть API (написана как модуль битрикса), которая выдаёт информацию для fronend'а и для приложений

### Дополнительные сервисы

1. Сервис который забирает информацию с вещательных серверов и выводит информацию о том какой трек на какой станции играет (есть более 80 вещательных станций, для этих станций выводится информация о том какой трек играет для каждой станции)
2. Сервис для парсинга метаданных для треков: 
	1. Обложка
	2. Название исполнитель 
	3. И прочее
3. Сервис который формирует XML для сервисов подкастов:
	1. Apple Podcasts
	2. Google Podcasts
	3. Прочее

### Желания

- Перетащить на *нодовские сервисы*
- Перетащить это всё на nodejs вместо php 
- Дополнительные сервисы трогать не нужно, потому что [[@Верди Атибайеба]] является мейнтейнером этих сервисов 
- **По сути нужна миграция с Битрикса на кастомную CMS**
- Нужен бэк и к нему нужна админка

### Есть ли на примете что-то? 

- Нет 

### Ожидания 

- Есть предположение 1 – 2 месяца для реализации
- Под бюджету: сложно сказать

### Риски и проблемы

- Проблемы битрикса: 
	- Добавление кастомных полей в битриксе, связанное с юзером и которое нельзя закэшировать, происходит очень медленно и ресурсов сервера не хватает. CloudFlare кэширует 13 терабайт трафика. 
- Медленность обработки данных Битриксом
- Часть с юзерами важна и рискованна особенно
- Миграция данных — неизвестно. Самое главное это перетащить юзеров (на вскидку есть 2-3 таблицу связанных с юзерами и есть 1 (кастомная), очень важная).
- Треки и хранение данных: треки тоже надо переносить, и всё что по ним сохранено нужно перенести. 
	- Описание треков, метаданные
	- Таблица с историей проигрывания трека по станциям. Таблица примерно 3 000 000 записей
- Добавление Плейлиста (подкаста) реализовано кастомно, кастомная страничка админки, но в рамках Битрикса. 
	- При добавлении плейлиста, файл отправляется на другой сервер, а информация о нём добавляется в текущую базу

**Comment by taqyon** [comment]
### Мои выводы

- Надо особое внимание обратить на область с пользователями и собрать правильно архитектуру. Потому что в последствии нужно будет организовать миграцию данных
- Тоже самое касается данных по трекам
- Остальные разделы и участки довольно простые

**Comment by TorinAsakura** [comment]
Начальство не дало денех. Расходимся.
