### ISSUE TITLE
Анализ чуваков с nodejs/react

### ISSUE THREAD

**Issue by taqyon** [atls/design#71]
Анализ чуваков с nesjs/react

**Comment by TorinAsakura** [comment]
@taqyon Вообще я говорил nodejs/nestjs + reactjs, так как один только нест это очень узко, таких, я боюсь или нет или очень мало

**Comment by taqyon** [comment]
> @taqyon Вообще я говорил nodejs/nestjs + reactjs, так как один только нест это очень узко, таких, я боюсь или нет или очень мало

да в меня чёто бес вселился, я вообще не понял откуда nest взялся

**Comment by taqyon** [comment]
[Я думаю я закончил.](https://docs.google.com/spreadsheets/d/1JSdN6Pquxwfs_5FpY8wNJDP3axUD_SaHBf7bklYZUHc/edit?usp=sharing) Получилось меньше чем 10 (7). Искать их не просто, потому что часто встречаются гиганты (1000 сотрудников) либо иностранные компании. 

## Выводы 

### 1. Как правило, это **СИЛЬНЫЕ** компании

У которых есть свои продукты, либо школы обучения персонала. Они владеют продуктовой разработкой.

### 2. Компании средней руки, не означает «среднячок»

Несмотря на то, что у них нет своих продуктов или своих направлений (школа например), компании также сильны в работе. Это видно по портфолио и клиентам. 

### 3. Компании знают что умеют делать

Чаще всего они сразу сообщают о том, чем они занимаются и **указывают специализацию.** Это может быть отрасль, либо направление, либо технологии. 

### 4. Фокусируются на своих умениях 

Упаковывают услуги в «продукт» и пушат. 

### 5. Стоимость человеко-часа разработки более-менее похожа

В среднем это 2 200 руб. 

### 6. Форма обратной связи абсолютно стандратная

Включает: 

- Имя
- Телефон
- Email 
- Сообщение
