### ISSUE TITLE
Спроектировать Backend архитектуру SaaS сервиса

### ISSUE THREAD

**Issue by taqyon** [atls/design#74]
|    Дата    | Кто предоставляет информацию | Цель                                                |
|:----------:| ---------------------------- | --------------------------------------------------- |
| 2022-09-02 | Константин                   | Понять, что за проект, особенности. Взять интервью. | 

## Вводные от Андрея Гостюхина

- Есть десктопное приложение 
- К ним заходит чувак
- Он хочет купить на WB, Ozon
- Заходит с одной точки
- Регистрируется, создаёт задание на покупку
- Сервис идёт создавать аккаунт, под этот аккаунт
- Алгоритм работает через Selenium
- Находит позицию
- Купить

## Вводные от Хабр Фриланс

[Спроектировать Backend архитектуру SaaS сервиса — Заказы — Хабр Фриланс](https://freelance.habr.com/tasks/455097)

> Ищем специалиста уровня Senior! Необходимо спроектировать Backend архитектуру для SaaS сервиса.  

>Вот для примера сайты таких сервисов:  
>- [mpboost.pro](mpboost.pro)  
>- [togotop.ru](togotop.ru)  
>- [ozprod.ru](ozprod.ru)  
>- [wbprod.ru](wbprod.ru)  
>- [topstore.pro](topstore.pro)  
  
>По этой архитектуре мы будем строить похожий сервис. Архитектура даст понимание по ежемесячным затратам на инфраструктуру: например сколько серверов нам нужно проплачивать и с какими мощностями, какие решения использовать для скрытия IP и уникализации сессий и т.д.  
  
>Ищем специалиста уровня Senior с большим опытом проектирования и разработки.  
Условия обсуждаются.

## Интервью

- **ЦА:** Сервис для продавцов на маркетплейсах 
- **Преимущество:** Логистика, забор товара
- **Задача:** уйти из desktop приложения, хотим сделать web сервис
- **Цель:** Найти деньги у инвесторов
- **У нас другая модель монетизации:** тарифная сетка

### Расскажите об проекте

- Занимается продвижением на WB
- На WB товары продвигаются в топ, если выкупать товары у себя
- Сами у себя покупаем товары
- Уже есть сервис

**Базовая логика:** 

- Пользователь вводит данные для выкупа
- Нажимает запуск
- Система заходит на WB, добавляет в корзину, выкупает, товар выкупается
- Выкупы делаются многопоточно, сразу много артикулов
- Можно отставлять отзывы (часть бизнеса)
- Собрать данные для получения (есть парсер)
- Аккаунты регать

**MVP:** 

- Сделали MVP на десктоп приложении
- Написана на Java, работает на Selenium 
- **Она продаётся**
- Есть сообщество в телеграме

### Ожидания по срокам на разработку архитектуры?

- Неделя-две

### Ожидания по стоимости на разработку архитектуры?

- 60 000 руб. 

### Уточнение 

- Пользователь работает с desktop приложением, делает «выкуп» самостоятельно. 

### Как вы себе представляете эту архитектуру? Форма

- Текст, графика, плюс финансовые расчёты 

### Ключевой вопрос: Почему мы не можем посчитать затраты? Уникализация аккаунтов

- Непонятно какое решение необходимо использовать для создания новых уникальных аккаунтов. 

**Сейчас решение:** покупаем на каждый аккаунт новый аккаунт новый прокси.

### Площадки борются с выкупами? 

- С выкупами не борются, WB выгодно
- Они борются с отзывами, удаляют отзывы
- Чтобы отзывы не удаляют если пользователь уникальный 
- Ozon: **выкупают товары здесь ради отзывов** 

### На что стоит обратить внимание

- Каждый 4й выкуп зависает (Selenium)

### Чем вы будете руководствоваться при выборе с кем будете сотрудничать?

- Компетенциями: 
	- Обзвонил компании из поиска Яндекса
	- Чеки заряжают большие
	- Не вникают в суть
- Что хотим: 
	- Понимаем что разработка сервиса по ТЗ займёт месяцев 6
		- Хотим чтобы за месяца 2-3 получить MVP 

### На чём можно сэкономить при разработке MVP

- На интерфейсе: Можно взять дизайн интерфейс у конкурентов
- Можно отказаться от лишних функций

**Comment by TorinAsakura** [comment]
@taqyon как закончишь - потом дополни таску и прикрепи сюда Андрея, ну или сделай новую с закрытием этой если контексты расходятся…крч

**Comment by taqyon** [comment]
Расчёты https://docs.google.com/spreadsheets/d/1BTTO0HHGs7sm2zYC9G-kX9vLCcy93RKheXmh7LNlG3s/edit#gid=1483986997
