### ISSUE TITLE
Разобраться с анимированными мокапами

### ISSUE THREAD

**Issue by dakand** [atls/design#77]
_Все 3D мокапы, которые я делал для YT на Behance были сделаны в сплайне. К сожалению, там нет рендера, а только запись видео модели, поэтому создание там анимированного мокапа не имеет особого смысла - банально модель выходит не в лучшем качестве, появляются постоянные баги текстуры, если выбирать перспективу, ну и я в целом не смог выгрузить видос из-за ошибки._

---

### Задача

Кароче, нам нужно самим научиться делать качественные мокапы. @bbbaso тебе нужно в этом мне помочь. Для этого нам нужно выяснить какие способы для создания существуют, какие из них лучше и рациональнее. Уточню, что мы должны получить в итоге: Анимированный 3D-мокап (например, телефон) на экран которого наложена текстура с анимацией (анимация интерфейса).

**Сейчас я выявил 4 возможных способа:**
1. Плагин для AE "Element 3D". Но он стоит 200-300$ и при этом информации о нём после 2020 года практически нет. Но этот плагин решает проблему так как нужно.
2. Cinema 4D. У меня кореш моушен дизайнер сказал, что там можно накладывать видео-текстуру.
3. Cinema 4D + cineware (встроенный плагин АЕ). Делаем модель в синьке, загружаем её в АЕ и в нём добавляем текстуру. Такой подход мне больше нравится, т.к. он системнее.
4. Blender. Видел видосик, что можно добавить текстуру анимации.

**Что нужно сделать:**
1. В теории проверить возможность применения каждого метода (с 4 по 2, п.1 нам не нужен).
2. Проверить на практике п.4.
3. Если результат нас устроит, то остановимся на этом. Если нет, то проверим п.3 и п.2.
4. Сделать гайд по созданию модели.

_P.S. Особое внимание обрати на то как будет отражаться свет на модели. Чтобы при повороте модели в какой-то момент не появлялись стрёмные блики._

**Comment by bbbaso** [comment]
@dakand почти финиш

1. Да, в теории все способы рабочие.
2. Приложил видос ниже. Это результат вчерашних танцев с бубном. Модельку брал готовую, чтобы быстрее протестить видео текстуру (сначала простую анимацию сделал в АЕ). Эти 2 секунды у меня рендерились 3 часа, то есть быстро протестить не вышло (др. словами могло быть лучше), а результат я смог увидеть только после рендера. 

Тут есть пару моментов:
 - текстура (фото или видео) не всегда грамотно ложится, нужно бывает слегка редактировать, но иногда я не совсем понимаю зависимость этих настроек
 - сам факт, что я ради двух секунд мучался почти весь день, вообще не радует + это явно too much для бедной видюхи, которая у меня в проце

https://user-images.githubusercontent.com/103942572/189363339-3ec5a6e6-0a99-4437-9e4c-68351d9bc65e.mp4


3. На счет проверки в C4D: честно говоря, совершенно не вижу причину мне изучать еще и её
4. Сделал адекватный мокап в статике. Гайд делал по нему. Фотка мокапа в хай резе и гайд [тут](https://www.figma.com/file/TokycSIbsNRq6Eyx6O7SgN/Mockup-Guide?node-id=1%3A13)

**Comment by dakand** [comment]
> @dakand почти финиш
> 
> 1. Да, в теории все способы рабочие.
> 2. Приложил видос ниже. Это результат вчерашних танцев с бубном. Модельку брал готовую, чтобы быстрее протестить видео текстуру (сначала простую анимацию сделал в АЕ). Эти 2 секунды у меня рендерились 3 часа, то есть быстро протестить не вышло (др. словами могло быть лучше), а результат я смог увидеть только после рендера.
> 
> Тут есть пару моментов:
> 
> * текстура (фото или видео) не всегда грамотно ложится, нужно бывает слегка редактировать, но иногда я не совсем понимаю зависимость этих настроек
> * сам факт, что я ради двух секунд мучался почти весь день, вообще не радует + это явно too much для бедной видюхи, которая у меня в проце
> 
>  render1.mp4 
> 3. На счет проверки в C4D: честно говоря, совершенно не вижу причину мне изучать еще и её
> 4. Сделал адекватный мокап в статике. Гайд делал по нему. Фотка мокапа в хай резе и гайд [тут](https://www.figma.com/file/TokycSIbsNRq6Eyx6O7SgN/Mockup-Guide?node-id=1%3A13)

@bbbaso Хорош, спасибо!

**Comment by dakand** [comment]
@bbbaso только вот создание модели в блендере не так важно, она может быть любая. А вот само наложение текстуры с видео важно. Т.е. непонятно это сейчас работает как должно или через какой-то костыль. Честно скажу с нодами не работал, но по последнему скрину гайда не вижу, чтобы там где-то упоминалось что-то вроде "mp4", вижу только PNG в image texture. Поэтому вот этот момент бы понять. Кмк, лучше было бы скринкастом.

**Comment by bbbaso** [comment]
@dakand Ноды совсем базовые, пару кликов всего придется делать. Работает без костылей, то есть нод "Image texture" и есть нужная нам текстура (подгружается как фото так и  видео, мой файл из АЕ был в формате "mp4") 

На счет проблем с настройками имел ввиду отражение фотки/видоса после наложения текстуры, иногда она тупо была вверх ногами или оверсайз, и вот хз почему

Скринкаст сделаю, без проблем

**Comment by bbbaso** [comment]
**Обещанный скринкаст** (*создание нового нода - Shift+A)


https://user-images.githubusercontent.com/103942572/189630838-c81d92cd-00f4-4f2f-adec-79a36c2f0a61.mp4

**Comment by TorinAsakura** [comment]
@dakand ?
