### ISSUE TITLE
Структуризация компонентов в Orbitto

### ISSUE THREAD

**Issue by dakand** [atls/design#83]
@bbbaso надо [тут](https://www.figma.com/file/fpoeezViAZJSXXhizspqof/Orbitto-%7C-Service?node-id=106%3A12434) все в порядок привести. Такая же система как и для КР: нейминг и группировка. 

Можешь начать на след неделе, если сегодня нет желания переключаться.

**Comment by bbbaso** [comment]
@dakand можешь дать права на редактирование?

**Comment by dakand** [comment]
> @dakand можешь дать права на редактирование?

done

**Comment by bbbaso** [comment]
> @bbbaso надо [тут](https://www.figma.com/file/fpoeezViAZJSXXhizspqof/Orbitto-%7C-Service?node-id=106%3A12434) все в порядок привести. Такая же система как и для КР: нейминг и группировка.

Done
