### ISSUE TITLE
2022-09-27, Вячеслав

### ISSUE THREAD

**Issue by taqyon** [atls/design#88]
## Части процесса

1. Программа которая для захвата видеострима - стрим
2. Программа которая занимается обработкой картинки стрима - распознаватель
3. Солвер - программа которая занимается решением задач

## 1. Задача: Скопировать программу

Программа скачивается по ссылке, по которой она открывается. Есть админка, видеострим и передача сигнала онлайн. Также надо будет доработать функционал. 

### О программе

Программа захвата видео со смартфорна. И отправка картинки куда-то дальше.

## 2. Задача: Написать вторую часть

Программу, которая будет распознавать изображение из стрима первой программы.

## 3. Задача

Взять информацию выведеную с помощью распознования, загоняет её в калькулятор.

Калькулятор придумывать не надо, он уже есть. Он есть в виде программы, которая устанавливается на компьютер. 

## Ключевые требования

1. Качество стрима должно быть не хуже чем в оригинале.
2. Качество распознавания должно быть высоким, ошибки в распозновании не должны быть больше чем 1%. 
3. Скорость распознования должна быть не больше чем 0,5 секунды.
4. Важна скорость рассчёта. Чем быстрее тем лучше. Не больше 1 секунды. 

## Бюджет на первые две задачи

Нет бюджета. Конкурс. 

## Вопросы

1. Кто будет источником данных по информации о программе.
Вячеслав

**Comment by taqyon** [comment]
@TorinAsakura провели вчера беседу с Вячеславом. Он попросил сразу не отправлять тебе результат. Подождать. Но прошло время, он ничего не ответил. Поэтому вот результат.

**Comment by TorinAsakura** [comment]
@taqyon К сожалению, ничего нового, даже меньше чем было у меня с ним на первом созвоне. Попробуй это обсудить с @monstrs
