### ISSUE TITLE
Знакомство с проектом Atlantis Academy

### ISSUE THREAD

**Issue by dakand** [atls/design#9]
Я уже рассказывал про проект на созвоне и то как мы планируем его разработку. Ещё раз коротко - мы создаём сайт в рамках 7 этапов, каждый из которых обоснован используемой технологией.

[Здесь](https://www.figma.com/file/Z8m03nUsEoolW0WcLMU93h/Work-project?node-id=796%3A8) проект в Figma. [Здесь](https://github.com/atls-academy/web/wiki/План-разработки-по-этапам-для-студентов) структура сайта и порядок разработки.

Твои задачи:

- [ ] **Изучить проект.** Постарайся визуализровать у себя в голове что именно будут представлять из себя этапы и как они будут отличаться. Возможно, ты для себя что-то нарисуешь или напишешь чтобы лучше понять это. Если ты правильно отнесёшься к этому пункту, то скорее всего у тебя возникнут вопросы. Предыдущий стажёр только сказал, что сделал эту задачу, но по факту представления не было абсолютно и от этого работа над задачей была бессмысленной.

- [ ] **Собрать референсы.** У нас нет четкого отделения этапа прототипирования и этапа дизайна. Поэтому абстрактно мы должны понимать, что у нас должно получиться на последнем этапе. Собери референсы, но учитывай, что нам не нужен набор красивых картинок. Референсы нужно искать в одной стилистике. Например, на первом сайте типографика и композиция, на втором сайте цветовое решение и ритм, на третьем нравится блок с перечислением чего-то (мы сможем применить для направлений). В идеале описывать кусок на сайте (как он к нам применим). Поэтому в рамках этой задачи я советовал был юзать для поиска референсов https://www.awwwards.com/. Мудборд располагай [здесь](https://www.figma.com/file/Z8m03nUsEoolW0WcLMU93h/Work-project?node-id=1044%3A374). PS мое видение сайта можно понять вот [здесь](https://www.figma.com/file/Z8m03nUsEoolW0WcLMU93h/Work-project?node-id=870%3A478), будет 3д фон, который будет взаимодействовать со скролом, весь сайт будет в фиолетовых оттенках, создавать "швы" между блоками не хочется.

**Comment by dakand** [comment]
@ArtemHovsky [ссылка](https://github.com/atls-academy/web/wiki/Atlantis-Academy) на инфу об академии от Андрея. Если нужно будет добавить другие текстовые блоки (а это скорее всего будет нужно), то юзай рыбу - допишем.

**Comment by ArtemHovsky** [comment]
Собрал референсы, мудборд. Набросал прототип. 
Нужно созвониться обсудить направление по стилю, уточнить по блокам в которых нет информации.
https://www.figma.com/file/zRa6BEvuB2FeAB1XawC6WU/Atlantis-Academy?node-id=12%3A13

**Comment by TorinAsakura** [comment]
> Собрал референсы, мудборд. Набросал прототип.
> Нужно созвониться обсудить направление по стилю, уточнить по блокам в которых нет информации.
> https://www.figma.com/file/zRa6BEvuB2FeAB1XawC6WU/Atlantis-Academy?node-id=12%3A13

доступа нет

**Comment by TorinAsakura** [comment]
@ArtemHovsky @dakand хочу от тебя услышать ревью. 

Выглядит так, что снова тема про магазин курсов, у нас тема противоположная, мы ничего не продаём, мы учим, то есть, кейс должен исходить из курса, много контента о процессе внутри непосредственно курса, на главной лишь "мягкие ссылки" для перехода в описание/детализацию курса, то есть - главная страница просто должна приоткрывать то, что внутри курса и быть удобным СТА

**Comment by ArtemHovsky** [comment]
Посмотри пожалуйста прототип главной и немного начал страницу курса:
https://www.figma.com/file/zRa6BEvuB2FeAB1XawC6WU/Atlantis-Academy?node-id=12%3A13
