### ISSUE TITLE
MP Rating, Рекламный кабинет — Grand Theft Service

### ISSUE THREAD

**Issue by taqyon** [atls/design#91]
Привет! 

Я сейчас работаю с клиентом и у нас есть некоторая проблема с тем, как бы начать работу над концепцией сервиса эффективно. 

## В чём дело?
Суть заключается в том, что мы сами до конца не можем понять что писать и как писать для предстоящего сервиса. Поэтому наши разговоры не очень эффективны. Но! Так как предполагаемый сервис, это не «ноу хау» и у него уже есть конкуренты, мы приняли решение, что для исследования и обсуждения, прощего всего будет слизать существующий сервис. И в последствии адаптировать его под нас и самое главное разобрать его на косточки. 

## Что нужно? И для чего?

Тупо срисовать сервис как есть, не думая. Нам этот материал понадобится, для дальнейшей мозговой работы. 

## В каком режиме будет работа?

Я сам не до конца понимаю, но скорее всего парт тайм. То есть нам нужна будет помощь не вся сразу, а кусками. Но я не до конца уверен. 
Из-за того что работа скорее всего будет кусковая с этим будут неудобства, сорри. 

## Что за сервис? 

- https://fullstats.ru/
- Есть доступ от личного кабинета, но он пока не проплачен
- Первый экран можно слизать с [видоса](https://www.youtube.com/watch?v=uYH6DlMblyI&t=19s)
- Я форсирую покупку платного доступа, чтобы не было проблем с материалом

## В каком виде нужно?

Figma. Цвета нужно убрать, предпочтительно всё серое и его оттенки. Это будет вайрфрейм, который мы сможем вертеть как хотим, чтобы добиться нужных целей. 

## Как скоро? Есть сроки? Требования? 

- Нужно начать сегодня, пойдёт даже не завершенная работа и набросок, для старта нужен буквально один экран
- Я закладываю на всю работу целиком — 2 недели. Из них твоего времени там, 3-4 рабочих дня. 
- Требований не много:
  - Экраны и их материалы нужны в организованном виде, как обычно
  - Цвета не нужны, лого не нужны, можно заменить плейсхолдерами

**Comment by taqyon** [comment]
Я сам это буду делать просто утомительно долго, поэтому мне нужна помощь.

**Comment by dakand** [comment]
@taqyon адаптив не нужен?

**Comment by taqyon** [comment]
> @taqyon адаптив не нужен?

Вообще нет, достаточно десктопа одного разрешения

**Comment by dakand** [comment]
@ArtemHovsky подключаем тебя на проект. Завтра тогда начни с этого. _Айдентику пока отложи._

Перед началом проектирования, созвонись с @taqyon (Вань, назначь созвон с Тёмой) и собери структуру - буквально какие нужны страницы. Отобрази список всех страниц в этом issue.

**Comment by taqyon** [comment]
Номер телефона для авторизации на fullstats: +7 (977) 425-83-46
