### ISSUE TITLE
Orbitto: баг с калькулятором

### ISSUE THREAD

**Issue by dakand** [atls/design#96]
@TorinAsakura @TFK70 Парни хелп нужен. Не закапывайтесь в проблему, мб вы просто вы знаете как сходу её решить.
Сайт https://www.orbitto.tech/
Там есть калькулятор в котором есть баг:
При выделенном radiobutton из второй группы, при изменении radiobutton не считается результат. 

В скрипте чето не так и я вроде бы понимаю, но как именно изменить алгоритм не знаю.

Сам скрипт:
```
<script>
$('.radio-label').click(function(){
  let sum;
  let spread = 1.015;
  let cyc;
  let time;
  
  if($(this).prev().is('[name="Deposit"]')){
    sum = Number($(this).prev().attr('add-value')) * Math.pow(spread, (Number($('input[name="Cycle"]:checked').attr('add-value')) || 0)) - Number($(this).prev().attr('add-value'));
  	cyc = Number($('input[name="Cycle"]:checked').attr('add-value'));
  }
  else { 
    sum = Math.pow(spread, Number($(this).prev().attr('add-value'))) * (Number($('input[name="Deposit"]:checked').attr('add-value')) || 0) - Number($('input[name="Deposit"]:checked').attr('add-value'));
  	cyc = Number($(this).prev().attr('add-value'));
  }
  
  if (cyc == 2){
  	time = '~ 2 часа';
  }
	if (cyc == 5){
  	time = '~ 4 часа';
  }
  if (cyc == 10){
  	time = '~ 9 часов';
  }
  if (cyc == 20){
  	time = '~ 15 часов';
  }  
  
  sum = Math.ceil(sum);
  const formattedSum = new Intl.NumberFormat('ru-RU').format(sum);  
  $('.added-value').text(formattedSum);
  $('.added-time').text(time);
});
</script>
```

Наверное классы элементов можно посмотреть в инспекторе. Или я могу дать доступ на редактирование в вебфлоу, как Андрею.

**Comment by dakand** [comment]
Скринкаст 
https://user-images.githubusercontent.com/75856342/195896356-c798ef1c-09c8-4413-8b46-6e723030caef.mov

**Comment by TFK70** [comment]
@dakand там вроде опечатка в названии второй группы радио

`ycle`, вместо `Cycle`, скрипт выглядит рабочим

![image](https://user-images.githubusercontent.com/62806448/195903639-9bb9fe9c-fa6b-4d3b-a3ae-0c43e794075c.png)

**Comment by dakand** [comment]
> @dakand там вроде опечатка в названии второй группы радио
> 
> `ycle`, вместо `Cycle`, скрипт выглядит рабочим
> 
> ![image](https://user-images.githubusercontent.com/62806448/195903639-9bb9fe9c-fa6b-4d3b-a3ae-0c43e794075c.png)

Неа, груп нейм ок https://disk.yandex.ru/i/HmmoLq-Ag1DyWA

Я думаю, если бы была опечатка, то он бы не работал, но он работает збс, но только в последовательном порядке

**Comment by TFK70** [comment]
@dakand он работает только в том случае, когда ему не нужно обращаться по имени к группе `Cycle`

То есть в этом куске

```javascript
  if($(this).prev().is('[name="Deposit"]')){
    sum = Number($(this).prev().attr('add-value')) * Math.pow(spread, (Number($('input[name="Cycle"]:checked').attr('add-value')) || 0)) - Number($(this).prev().attr('add-value'));
  	cyc = Number($('input[name="Cycle"]:checked').attr('add-value'));
  }
```

Он берёт значение из радио группы cycle: `Number($('input[name="Cycle"]:checked').attr('add-value')`, но он её не может получить, так как инпаты в группе называются `ycle`

Но условие в else:

```javascript
  else { 
    sum = Math.pow(spread, Number($(this).prev().attr('add-value'))) * (Number($('input[name="Deposit"]:checked').attr('add-value')) || 0) - Number($('input[name="Deposit"]:checked').attr('add-value'));
  	cyc = Number($(this).prev().attr('add-value'));
  }
```

Отрабатывает, так как ему не нужно обращаться к группе `Cycle` по названию, он уже находится в ней и получает значение через селектор `$(this).prev().attr('add-value')`

Так вот первое условие (if) отрабатывает когда ты кликаешь на элемент в группе `Deposit`, а второе (else) отрабатывает когда ты кликаешь на элемент в группе `Cycle`. Поэтому когда ты кликаешь на `Deposit` у тебя перерасчёт происходит криво, он просто не может получить значение из `Cycle`

Это с `99%` вероятностью факап где-то в билдере сайтов, и с `1%` вероятностью баг вебфлоу, как-то так)
